// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "maxpool1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic maxpool1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic maxpool1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<14> maxpool1::ap_ST_fsm_state1 = "1";
const sc_lv<14> maxpool1::ap_ST_fsm_state2 = "10";
const sc_lv<14> maxpool1::ap_ST_fsm_state3 = "100";
const sc_lv<14> maxpool1::ap_ST_fsm_state4 = "1000";
const sc_lv<14> maxpool1::ap_ST_fsm_state5 = "10000";
const sc_lv<14> maxpool1::ap_ST_fsm_state6 = "100000";
const sc_lv<14> maxpool1::ap_ST_fsm_state7 = "1000000";
const sc_lv<14> maxpool1::ap_ST_fsm_state8 = "10000000";
const sc_lv<14> maxpool1::ap_ST_fsm_state9 = "100000000";
const sc_lv<14> maxpool1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<14> maxpool1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<14> maxpool1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<14> maxpool1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<14> maxpool1::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<32> maxpool1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> maxpool1::ap_const_lv32_4 = "100";
const sc_lv<32> maxpool1::ap_const_lv32_7 = "111";
const sc_lv<32> maxpool1::ap_const_lv32_A = "1010";
const sc_lv<32> maxpool1::ap_const_lv32_1 = "1";
const sc_lv<1> maxpool1::ap_const_lv1_0 = "0";
const sc_lv<32> maxpool1::ap_const_lv32_2 = "10";
const sc_lv<32> maxpool1::ap_const_lv32_3 = "11";
const sc_lv<32> maxpool1::ap_const_lv32_5 = "101";
const sc_lv<32> maxpool1::ap_const_lv32_6 = "110";
const sc_lv<32> maxpool1::ap_const_lv32_8 = "1000";
const sc_lv<32> maxpool1::ap_const_lv32_9 = "1001";
const sc_lv<32> maxpool1::ap_const_lv32_B = "1011";
const sc_lv<32> maxpool1::ap_const_lv32_C = "1100";
const sc_lv<5> maxpool1::ap_const_lv5_0 = "00000";
const sc_lv<1> maxpool1::ap_const_lv1_1 = "1";
const sc_lv<32> maxpool1::ap_const_lv32_D = "1101";
const sc_lv<4> maxpool1::ap_const_lv4_0 = "0000";
const sc_lv<5> maxpool1::ap_const_lv5_1F = "11111";
const sc_lv<5> maxpool1::ap_const_lv5_1 = "1";
const sc_lv<7> maxpool1::ap_const_lv7_0 = "0000000";
const sc_lv<2> maxpool1::ap_const_lv2_0 = "00";
const sc_lv<6> maxpool1::ap_const_lv6_1 = "1";
const sc_lv<6> maxpool1::ap_const_lv6_0 = "000000";
const sc_lv<3> maxpool1::ap_const_lv3_0 = "000";
const sc_lv<4> maxpool1::ap_const_lv4_8 = "1000";
const sc_lv<4> maxpool1::ap_const_lv4_1 = "1";
const sc_lv<32> maxpool1::ap_const_lv32_17 = "10111";
const sc_lv<32> maxpool1::ap_const_lv32_1E = "11110";
const sc_lv<8> maxpool1::ap_const_lv8_FF = "11111111";
const sc_lv<23> maxpool1::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> maxpool1::ap_const_lv5_2 = "10";
const bool maxpool1::ap_const_boolean_1 = true;

maxpool1::maxpool1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    topp_fcmp_32ns_32dEe_U11 = new topp_fcmp_32ns_32dEe<1,1,32,32,1>("topp_fcmp_32ns_32dEe_U11");
    topp_fcmp_32ns_32dEe_U11->din0(grp_fu_184_p0);
    topp_fcmp_32ns_32dEe_U11->din1(grp_fu_184_p1);
    topp_fcmp_32ns_32dEe_U11->opcode(ap_var_for_const0);
    topp_fcmp_32ns_32dEe_U11->dout(grp_fu_184_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_200_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_200_p2 );

    SC_METHOD(thread_c_2_fu_322_p2);
    sensitive << ( c_reg_162 );

    SC_METHOD(thread_ch_2_fu_425_p2);
    sensitive << ( ch_reg_173 );

    SC_METHOD(thread_exitcond1_fu_316_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( c_reg_162 );

    SC_METHOD(thread_exitcond2_fu_200_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_reg_151 );

    SC_METHOD(thread_exitcond_fu_419_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ch_reg_173 );

    SC_METHOD(thread_f1_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_84_fu_469_p1 );
    sensitive << ( tmp_91_reg_903 );
    sensitive << ( tmp_90_fu_608_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( maxv_2_reg_951 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_f1_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_85_fu_474_p2 );
    sensitive << ( maxv_8_reg_914 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( maxv_1_reg_935 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_f1_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_f1_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_grp_fu_184_p0);
    sensitive << ( reg_188 );
    sensitive << ( reg_194 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_grp_fu_184_p1);
    sensitive << ( reg_188 );
    sensitive << ( reg_194 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_maxv_1_fu_697_p3);
    sensitive << ( maxv_8_reg_914 );
    sensitive << ( tmp_90_reg_920 );
    sensitive << ( tmp_53_fu_691_p2 );

    SC_METHOD(thread_maxv_1_to_int_fu_721_p1);
    sensitive << ( reg_194 );

    SC_METHOD(thread_maxv_2_fu_787_p3);
    sensitive << ( tmp_91_reg_903 );
    sensitive << ( maxv_1_reg_935 );
    sensitive << ( tmp_62_fu_781_p2 );

    SC_METHOD(thread_maxv_8_fu_596_p3);
    sensitive << ( tmp_84_reg_873 );
    sensitive << ( tmp_85_reg_883 );
    sensitive << ( tmp_44_fu_590_p2 );

    SC_METHOD(thread_maxv_8_to_int_fu_631_p1);
    sensitive << ( reg_194 );

    SC_METHOD(thread_notlhs3_fu_739_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_54_fu_707_p4 );

    SC_METHOD(thread_notlhs4_fu_566_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_38_fu_534_p4 );

    SC_METHOD(thread_notlhs5_fu_757_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_56_fu_725_p4 );

    SC_METHOD(thread_notlhs6_fu_649_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_45_fu_617_p4 );

    SC_METHOD(thread_notlhs8_fu_667_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_47_fu_635_p4 );

    SC_METHOD(thread_notlhs_fu_548_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_s_fu_516_p4 );

    SC_METHOD(thread_notrhs3_fu_745_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_97_fu_717_p1 );

    SC_METHOD(thread_notrhs4_fu_763_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_98_fu_735_p1 );

    SC_METHOD(thread_notrhs5_fu_572_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_94_fu_544_p1 );

    SC_METHOD(thread_notrhs7_fu_655_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_95_fu_627_p1 );

    SC_METHOD(thread_notrhs9_fu_673_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_96_fu_645_p1 );

    SC_METHOD(thread_notrhs_fu_554_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_93_fu_526_p1 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_97_cast_fu_793_p1 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( f1_q0 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_p_shl1_cast_fu_268_p1);
    sensitive << ( tmp_64_fu_260_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_280_p1);
    sensitive << ( tmp_65_fu_272_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_228_p1);
    sensitive << ( tmp_55_fu_220_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_240_p1);
    sensitive << ( tmp_57_fu_232_p3 );

    SC_METHOD(thread_p_shl_cast_fu_306_p1);
    sensitive << ( tmp_67_fu_298_p3 );

    SC_METHOD(thread_r_2_fu_206_p2);
    sensitive << ( r_reg_151 );

    SC_METHOD(thread_tmp_1_fu_254_p2);
    sensitive << ( tmp_fu_212_p3 );

    SC_METHOD(thread_tmp_38_fu_534_p4);
    sensitive << ( v0_to_int_fu_530_p1 );

    SC_METHOD(thread_tmp_3_cast_fu_294_p1);
    sensitive << ( r_reg_151 );

    SC_METHOD(thread_tmp_40_fu_560_p2);
    sensitive << ( notrhs_fu_554_p2 );
    sensitive << ( notlhs_fu_548_p2 );

    SC_METHOD(thread_tmp_41_fu_578_p2);
    sensitive << ( notrhs5_fu_572_p2 );
    sensitive << ( notlhs4_fu_566_p2 );

    SC_METHOD(thread_tmp_42_fu_584_p2);
    sensitive << ( tmp_40_fu_560_p2 );
    sensitive << ( tmp_41_fu_578_p2 );

    SC_METHOD(thread_tmp_44_fu_590_p2);
    sensitive << ( tmp_42_fu_584_p2 );
    sensitive << ( grp_fu_184_p2 );

    SC_METHOD(thread_tmp_45_fu_617_p4);
    sensitive << ( v2_to_int_fu_613_p1 );

    SC_METHOD(thread_tmp_47_fu_635_p4);
    sensitive << ( maxv_8_to_int_fu_631_p1 );

    SC_METHOD(thread_tmp_49_fu_661_p2);
    sensitive << ( notrhs7_fu_655_p2 );
    sensitive << ( notlhs6_fu_649_p2 );

    SC_METHOD(thread_tmp_4_fu_328_p3);
    sensitive << ( c_reg_162 );

    SC_METHOD(thread_tmp_50_fu_679_p2);
    sensitive << ( notrhs9_fu_673_p2 );
    sensitive << ( notlhs8_fu_667_p2 );

    SC_METHOD(thread_tmp_51_fu_685_p2);
    sensitive << ( tmp_49_fu_661_p2 );
    sensitive << ( tmp_50_fu_679_p2 );

    SC_METHOD(thread_tmp_53_fu_691_p2);
    sensitive << ( grp_fu_184_p2 );
    sensitive << ( tmp_51_fu_685_p2 );

    SC_METHOD(thread_tmp_54_fu_707_p4);
    sensitive << ( v3_to_int_fu_703_p1 );

    SC_METHOD(thread_tmp_55_fu_220_p3);
    sensitive << ( r_reg_151 );

    SC_METHOD(thread_tmp_56_fu_725_p4);
    sensitive << ( maxv_1_to_int_fu_721_p1 );

    SC_METHOD(thread_tmp_57_fu_232_p3);
    sensitive << ( r_reg_151 );

    SC_METHOD(thread_tmp_58_fu_751_p2);
    sensitive << ( notrhs3_fu_745_p2 );
    sensitive << ( notlhs3_fu_739_p2 );

    SC_METHOD(thread_tmp_59_fu_769_p2);
    sensitive << ( notrhs4_fu_763_p2 );
    sensitive << ( notlhs5_fu_757_p2 );

    SC_METHOD(thread_tmp_5_cast_fu_336_p1);
    sensitive << ( tmp_4_fu_328_p3 );

    SC_METHOD(thread_tmp_60_fu_775_p2);
    sensitive << ( tmp_58_fu_751_p2 );
    sensitive << ( tmp_59_fu_769_p2 );

    SC_METHOD(thread_tmp_62_fu_781_p2);
    sensitive << ( grp_fu_184_p2 );
    sensitive << ( tmp_60_fu_775_p2 );

    SC_METHOD(thread_tmp_63_fu_244_p2);
    sensitive << ( p_shl3_cast_fu_228_p1 );
    sensitive << ( p_shl4_cast_fu_240_p1 );

    SC_METHOD(thread_tmp_64_fu_260_p3);
    sensitive << ( tmp_1_fu_254_p2 );

    SC_METHOD(thread_tmp_65_fu_272_p3);
    sensitive << ( tmp_1_fu_254_p2 );

    SC_METHOD(thread_tmp_66_cast_fu_250_p1);
    sensitive << ( tmp_63_fu_244_p2 );

    SC_METHOD(thread_tmp_66_fu_284_p2);
    sensitive << ( p_shl1_cast_fu_268_p1 );
    sensitive << ( p_shl2_cast_fu_280_p1 );

    SC_METHOD(thread_tmp_67_fu_298_p3);
    sensitive << ( r_reg_151 );

    SC_METHOD(thread_tmp_68_fu_310_p2);
    sensitive << ( p_shl_cast_fu_306_p1 );
    sensitive << ( tmp_3_cast_fu_294_p1 );

    SC_METHOD(thread_tmp_69_cast_fu_290_p1);
    sensitive << ( tmp_66_fu_284_p2 );

    SC_METHOD(thread_tmp_69_fu_340_p2);
    sensitive << ( tmp_66_cast_reg_805 );
    sensitive << ( tmp_5_cast_fu_336_p1 );

    SC_METHOD(thread_tmp_6_fu_358_p2);
    sensitive << ( tmp_4_fu_328_p3 );

    SC_METHOD(thread_tmp_70_fu_345_p1);
    sensitive << ( tmp_69_fu_340_p2 );

    SC_METHOD(thread_tmp_71_fu_349_p2);
    sensitive << ( tmp_69_cast_reg_811 );
    sensitive << ( tmp_5_cast_fu_336_p1 );

    SC_METHOD(thread_tmp_72_fu_354_p1);
    sensitive << ( tmp_71_fu_349_p2 );

    SC_METHOD(thread_tmp_73_fu_368_p2);
    sensitive << ( tmp_66_cast_reg_805 );
    sensitive << ( tmp_7_cast_fu_364_p1 );

    SC_METHOD(thread_tmp_74_fu_373_p3);
    sensitive << ( tmp_73_fu_368_p2 );

    SC_METHOD(thread_tmp_75_fu_381_p1);
    sensitive << ( tmp_74_fu_373_p3 );

    SC_METHOD(thread_tmp_76_fu_385_p2);
    sensitive << ( tmp_69_cast_reg_811 );
    sensitive << ( tmp_7_cast_fu_364_p1 );

    SC_METHOD(thread_tmp_77_fu_390_p3);
    sensitive << ( tmp_76_fu_385_p2 );

    SC_METHOD(thread_tmp_78_fu_398_p1);
    sensitive << ( tmp_77_fu_390_p3 );

    SC_METHOD(thread_tmp_79_fu_406_p2);
    sensitive << ( tmp_68_reg_817 );
    sensitive << ( tmp_8_cast_fu_402_p1 );

    SC_METHOD(thread_tmp_7_cast_fu_364_p1);
    sensitive << ( tmp_6_fu_358_p2 );

    SC_METHOD(thread_tmp_80_fu_439_p3);
    sensitive << ( tmp_70_reg_835 );

    SC_METHOD(thread_tmp_81_fu_446_p2);
    sensitive << ( ch_reg_173 );
    sensitive << ( tmp_80_fu_439_p3 );

    SC_METHOD(thread_tmp_82_fu_452_p4);
    sensitive << ( tmp_69_reg_830 );

    SC_METHOD(thread_tmp_83_fu_461_p3);
    sensitive << ( tmp_82_fu_452_p4 );
    sensitive << ( tmp_81_fu_446_p2 );

    SC_METHOD(thread_tmp_84_fu_469_p1);
    sensitive << ( tmp_83_fu_461_p3 );

    SC_METHOD(thread_tmp_85_fu_474_p2);
    sensitive << ( tmp_75_reg_850 );
    sensitive << ( tmp_9_fu_431_p1 );

    SC_METHOD(thread_tmp_86_cast_fu_411_p3);
    sensitive << ( tmp_79_fu_406_p2 );

    SC_METHOD(thread_tmp_86_fu_480_p3);
    sensitive << ( tmp_72_reg_845 );

    SC_METHOD(thread_tmp_87_fu_487_p2);
    sensitive << ( ch_reg_173 );
    sensitive << ( tmp_86_fu_480_p3 );

    SC_METHOD(thread_tmp_89_fu_602_p3);
    sensitive << ( tmp_87_reg_893 );
    sensitive << ( tmp_88_reg_898 );

    SC_METHOD(thread_tmp_8_cast_fu_402_p1);
    sensitive << ( c_reg_162 );

    SC_METHOD(thread_tmp_90_fu_608_p1);
    sensitive << ( tmp_89_fu_602_p3 );

    SC_METHOD(thread_tmp_91_fu_502_p2);
    sensitive << ( tmp_78_reg_855 );
    sensitive << ( tmp_9_fu_431_p1 );

    SC_METHOD(thread_tmp_92_fu_507_p2);
    sensitive << ( tmp_86_cast_reg_860 );
    sensitive << ( tmp_9_cast_fu_435_p1 );

    SC_METHOD(thread_tmp_93_fu_526_p1);
    sensitive << ( v1_to_int_fu_512_p1 );

    SC_METHOD(thread_tmp_94_fu_544_p1);
    sensitive << ( v0_to_int_fu_530_p1 );

    SC_METHOD(thread_tmp_95_fu_627_p1);
    sensitive << ( v2_to_int_fu_613_p1 );

    SC_METHOD(thread_tmp_96_fu_645_p1);
    sensitive << ( maxv_8_to_int_fu_631_p1 );

    SC_METHOD(thread_tmp_97_cast_fu_793_p1);
    sensitive << ( tmp_92_reg_909 );

    SC_METHOD(thread_tmp_97_fu_717_p1);
    sensitive << ( v3_to_int_fu_703_p1 );

    SC_METHOD(thread_tmp_98_fu_735_p1);
    sensitive << ( maxv_1_to_int_fu_721_p1 );

    SC_METHOD(thread_tmp_9_cast_fu_435_p1);
    sensitive << ( ch_reg_173 );

    SC_METHOD(thread_tmp_9_fu_431_p1);
    sensitive << ( ch_reg_173 );

    SC_METHOD(thread_tmp_fu_212_p3);
    sensitive << ( r_reg_151 );

    SC_METHOD(thread_tmp_s_fu_516_p4);
    sensitive << ( v1_to_int_fu_512_p1 );

    SC_METHOD(thread_v0_to_int_fu_530_p1);
    sensitive << ( reg_188 );

    SC_METHOD(thread_v1_to_int_fu_512_p1);
    sensitive << ( reg_194 );

    SC_METHOD(thread_v2_to_int_fu_613_p1);
    sensitive << ( reg_188 );

    SC_METHOD(thread_v3_to_int_fu_703_p1);
    sensitive << ( reg_188 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_200_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond1_fu_316_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_419_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "maxpool1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, f1_address0, "(port)f1_address0");
    sc_trace(mVcdFile, f1_ce0, "(port)f1_ce0");
    sc_trace(mVcdFile, f1_q0, "(port)f1_q0");
    sc_trace(mVcdFile, f1_address1, "(port)f1_address1");
    sc_trace(mVcdFile, f1_ce1, "(port)f1_ce1");
    sc_trace(mVcdFile, f1_q1, "(port)f1_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_188, "reg_188");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, reg_194, "reg_194");
    sc_trace(mVcdFile, r_2_fu_206_p2, "r_2_fu_206_p2");
    sc_trace(mVcdFile, r_2_reg_800, "r_2_reg_800");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_66_cast_fu_250_p1, "tmp_66_cast_fu_250_p1");
    sc_trace(mVcdFile, tmp_66_cast_reg_805, "tmp_66_cast_reg_805");
    sc_trace(mVcdFile, exitcond2_fu_200_p2, "exitcond2_fu_200_p2");
    sc_trace(mVcdFile, tmp_69_cast_fu_290_p1, "tmp_69_cast_fu_290_p1");
    sc_trace(mVcdFile, tmp_69_cast_reg_811, "tmp_69_cast_reg_811");
    sc_trace(mVcdFile, tmp_68_fu_310_p2, "tmp_68_fu_310_p2");
    sc_trace(mVcdFile, tmp_68_reg_817, "tmp_68_reg_817");
    sc_trace(mVcdFile, c_2_fu_322_p2, "c_2_fu_322_p2");
    sc_trace(mVcdFile, c_2_reg_825, "c_2_reg_825");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_69_fu_340_p2, "tmp_69_fu_340_p2");
    sc_trace(mVcdFile, tmp_69_reg_830, "tmp_69_reg_830");
    sc_trace(mVcdFile, exitcond1_fu_316_p2, "exitcond1_fu_316_p2");
    sc_trace(mVcdFile, tmp_70_fu_345_p1, "tmp_70_fu_345_p1");
    sc_trace(mVcdFile, tmp_70_reg_835, "tmp_70_reg_835");
    sc_trace(mVcdFile, tmp_71_fu_349_p2, "tmp_71_fu_349_p2");
    sc_trace(mVcdFile, tmp_71_reg_840, "tmp_71_reg_840");
    sc_trace(mVcdFile, tmp_72_fu_354_p1, "tmp_72_fu_354_p1");
    sc_trace(mVcdFile, tmp_72_reg_845, "tmp_72_reg_845");
    sc_trace(mVcdFile, tmp_75_fu_381_p1, "tmp_75_fu_381_p1");
    sc_trace(mVcdFile, tmp_75_reg_850, "tmp_75_reg_850");
    sc_trace(mVcdFile, tmp_78_fu_398_p1, "tmp_78_fu_398_p1");
    sc_trace(mVcdFile, tmp_78_reg_855, "tmp_78_reg_855");
    sc_trace(mVcdFile, tmp_86_cast_fu_411_p3, "tmp_86_cast_fu_411_p3");
    sc_trace(mVcdFile, tmp_86_cast_reg_860, "tmp_86_cast_reg_860");
    sc_trace(mVcdFile, ch_2_fu_425_p2, "ch_2_fu_425_p2");
    sc_trace(mVcdFile, ch_2_reg_868, "ch_2_reg_868");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_84_fu_469_p1, "tmp_84_fu_469_p1");
    sc_trace(mVcdFile, tmp_84_reg_873, "tmp_84_reg_873");
    sc_trace(mVcdFile, exitcond_fu_419_p2, "exitcond_fu_419_p2");
    sc_trace(mVcdFile, tmp_85_fu_474_p2, "tmp_85_fu_474_p2");
    sc_trace(mVcdFile, tmp_85_reg_883, "tmp_85_reg_883");
    sc_trace(mVcdFile, tmp_87_fu_487_p2, "tmp_87_fu_487_p2");
    sc_trace(mVcdFile, tmp_87_reg_893, "tmp_87_reg_893");
    sc_trace(mVcdFile, tmp_88_reg_898, "tmp_88_reg_898");
    sc_trace(mVcdFile, tmp_91_fu_502_p2, "tmp_91_fu_502_p2");
    sc_trace(mVcdFile, tmp_91_reg_903, "tmp_91_reg_903");
    sc_trace(mVcdFile, tmp_92_fu_507_p2, "tmp_92_fu_507_p2");
    sc_trace(mVcdFile, tmp_92_reg_909, "tmp_92_reg_909");
    sc_trace(mVcdFile, maxv_8_fu_596_p3, "maxv_8_fu_596_p3");
    sc_trace(mVcdFile, maxv_8_reg_914, "maxv_8_reg_914");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_90_fu_608_p1, "tmp_90_fu_608_p1");
    sc_trace(mVcdFile, tmp_90_reg_920, "tmp_90_reg_920");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, maxv_1_fu_697_p3, "maxv_1_fu_697_p3");
    sc_trace(mVcdFile, maxv_1_reg_935, "maxv_1_reg_935");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, maxv_2_fu_787_p3, "maxv_2_fu_787_p3");
    sc_trace(mVcdFile, maxv_2_reg_951, "maxv_2_reg_951");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, r_reg_151, "r_reg_151");
    sc_trace(mVcdFile, c_reg_162, "c_reg_162");
    sc_trace(mVcdFile, ch_reg_173, "ch_reg_173");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_97_cast_fu_793_p1, "tmp_97_cast_fu_793_p1");
    sc_trace(mVcdFile, grp_fu_184_p0, "grp_fu_184_p0");
    sc_trace(mVcdFile, grp_fu_184_p1, "grp_fu_184_p1");
    sc_trace(mVcdFile, tmp_55_fu_220_p3, "tmp_55_fu_220_p3");
    sc_trace(mVcdFile, tmp_57_fu_232_p3, "tmp_57_fu_232_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_228_p1, "p_shl3_cast_fu_228_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_240_p1, "p_shl4_cast_fu_240_p1");
    sc_trace(mVcdFile, tmp_63_fu_244_p2, "tmp_63_fu_244_p2");
    sc_trace(mVcdFile, tmp_fu_212_p3, "tmp_fu_212_p3");
    sc_trace(mVcdFile, tmp_1_fu_254_p2, "tmp_1_fu_254_p2");
    sc_trace(mVcdFile, tmp_64_fu_260_p3, "tmp_64_fu_260_p3");
    sc_trace(mVcdFile, tmp_65_fu_272_p3, "tmp_65_fu_272_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_268_p1, "p_shl1_cast_fu_268_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_280_p1, "p_shl2_cast_fu_280_p1");
    sc_trace(mVcdFile, tmp_66_fu_284_p2, "tmp_66_fu_284_p2");
    sc_trace(mVcdFile, tmp_67_fu_298_p3, "tmp_67_fu_298_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_306_p1, "p_shl_cast_fu_306_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_294_p1, "tmp_3_cast_fu_294_p1");
    sc_trace(mVcdFile, tmp_4_fu_328_p3, "tmp_4_fu_328_p3");
    sc_trace(mVcdFile, tmp_5_cast_fu_336_p1, "tmp_5_cast_fu_336_p1");
    sc_trace(mVcdFile, tmp_6_fu_358_p2, "tmp_6_fu_358_p2");
    sc_trace(mVcdFile, tmp_7_cast_fu_364_p1, "tmp_7_cast_fu_364_p1");
    sc_trace(mVcdFile, tmp_73_fu_368_p2, "tmp_73_fu_368_p2");
    sc_trace(mVcdFile, tmp_74_fu_373_p3, "tmp_74_fu_373_p3");
    sc_trace(mVcdFile, tmp_76_fu_385_p2, "tmp_76_fu_385_p2");
    sc_trace(mVcdFile, tmp_77_fu_390_p3, "tmp_77_fu_390_p3");
    sc_trace(mVcdFile, tmp_8_cast_fu_402_p1, "tmp_8_cast_fu_402_p1");
    sc_trace(mVcdFile, tmp_79_fu_406_p2, "tmp_79_fu_406_p2");
    sc_trace(mVcdFile, tmp_80_fu_439_p3, "tmp_80_fu_439_p3");
    sc_trace(mVcdFile, tmp_82_fu_452_p4, "tmp_82_fu_452_p4");
    sc_trace(mVcdFile, tmp_81_fu_446_p2, "tmp_81_fu_446_p2");
    sc_trace(mVcdFile, tmp_83_fu_461_p3, "tmp_83_fu_461_p3");
    sc_trace(mVcdFile, tmp_9_fu_431_p1, "tmp_9_fu_431_p1");
    sc_trace(mVcdFile, tmp_86_fu_480_p3, "tmp_86_fu_480_p3");
    sc_trace(mVcdFile, tmp_9_cast_fu_435_p1, "tmp_9_cast_fu_435_p1");
    sc_trace(mVcdFile, v1_to_int_fu_512_p1, "v1_to_int_fu_512_p1");
    sc_trace(mVcdFile, v0_to_int_fu_530_p1, "v0_to_int_fu_530_p1");
    sc_trace(mVcdFile, tmp_s_fu_516_p4, "tmp_s_fu_516_p4");
    sc_trace(mVcdFile, tmp_93_fu_526_p1, "tmp_93_fu_526_p1");
    sc_trace(mVcdFile, notrhs_fu_554_p2, "notrhs_fu_554_p2");
    sc_trace(mVcdFile, notlhs_fu_548_p2, "notlhs_fu_548_p2");
    sc_trace(mVcdFile, tmp_38_fu_534_p4, "tmp_38_fu_534_p4");
    sc_trace(mVcdFile, tmp_94_fu_544_p1, "tmp_94_fu_544_p1");
    sc_trace(mVcdFile, notrhs5_fu_572_p2, "notrhs5_fu_572_p2");
    sc_trace(mVcdFile, notlhs4_fu_566_p2, "notlhs4_fu_566_p2");
    sc_trace(mVcdFile, tmp_40_fu_560_p2, "tmp_40_fu_560_p2");
    sc_trace(mVcdFile, tmp_41_fu_578_p2, "tmp_41_fu_578_p2");
    sc_trace(mVcdFile, tmp_42_fu_584_p2, "tmp_42_fu_584_p2");
    sc_trace(mVcdFile, grp_fu_184_p2, "grp_fu_184_p2");
    sc_trace(mVcdFile, tmp_44_fu_590_p2, "tmp_44_fu_590_p2");
    sc_trace(mVcdFile, tmp_89_fu_602_p3, "tmp_89_fu_602_p3");
    sc_trace(mVcdFile, v2_to_int_fu_613_p1, "v2_to_int_fu_613_p1");
    sc_trace(mVcdFile, maxv_8_to_int_fu_631_p1, "maxv_8_to_int_fu_631_p1");
    sc_trace(mVcdFile, tmp_45_fu_617_p4, "tmp_45_fu_617_p4");
    sc_trace(mVcdFile, tmp_95_fu_627_p1, "tmp_95_fu_627_p1");
    sc_trace(mVcdFile, notrhs7_fu_655_p2, "notrhs7_fu_655_p2");
    sc_trace(mVcdFile, notlhs6_fu_649_p2, "notlhs6_fu_649_p2");
    sc_trace(mVcdFile, tmp_47_fu_635_p4, "tmp_47_fu_635_p4");
    sc_trace(mVcdFile, tmp_96_fu_645_p1, "tmp_96_fu_645_p1");
    sc_trace(mVcdFile, notrhs9_fu_673_p2, "notrhs9_fu_673_p2");
    sc_trace(mVcdFile, notlhs8_fu_667_p2, "notlhs8_fu_667_p2");
    sc_trace(mVcdFile, tmp_49_fu_661_p2, "tmp_49_fu_661_p2");
    sc_trace(mVcdFile, tmp_50_fu_679_p2, "tmp_50_fu_679_p2");
    sc_trace(mVcdFile, tmp_51_fu_685_p2, "tmp_51_fu_685_p2");
    sc_trace(mVcdFile, tmp_53_fu_691_p2, "tmp_53_fu_691_p2");
    sc_trace(mVcdFile, v3_to_int_fu_703_p1, "v3_to_int_fu_703_p1");
    sc_trace(mVcdFile, maxv_1_to_int_fu_721_p1, "maxv_1_to_int_fu_721_p1");
    sc_trace(mVcdFile, tmp_54_fu_707_p4, "tmp_54_fu_707_p4");
    sc_trace(mVcdFile, tmp_97_fu_717_p1, "tmp_97_fu_717_p1");
    sc_trace(mVcdFile, notrhs3_fu_745_p2, "notrhs3_fu_745_p2");
    sc_trace(mVcdFile, notlhs3_fu_739_p2, "notlhs3_fu_739_p2");
    sc_trace(mVcdFile, tmp_56_fu_725_p4, "tmp_56_fu_725_p4");
    sc_trace(mVcdFile, tmp_98_fu_735_p1, "tmp_98_fu_735_p1");
    sc_trace(mVcdFile, notrhs4_fu_763_p2, "notrhs4_fu_763_p2");
    sc_trace(mVcdFile, notlhs5_fu_757_p2, "notlhs5_fu_757_p2");
    sc_trace(mVcdFile, tmp_58_fu_751_p2, "tmp_58_fu_751_p2");
    sc_trace(mVcdFile, tmp_59_fu_769_p2, "tmp_59_fu_769_p2");
    sc_trace(mVcdFile, tmp_60_fu_775_p2, "tmp_60_fu_775_p2");
    sc_trace(mVcdFile, tmp_62_fu_781_p2, "tmp_62_fu_781_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

maxpool1::~maxpool1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete topp_fcmp_32ns_32dEe_U11;
}

void maxpool1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv5_2;
}

void maxpool1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_419_p2.read(), ap_const_lv1_1))) {
        c_reg_162 = c_2_reg_825.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_200_p2.read(), ap_const_lv1_0))) {
        c_reg_162 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_316_p2.read()))) {
        ch_reg_173 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        ch_reg_173 = ch_2_reg_868.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_316_p2.read(), ap_const_lv1_1))) {
        r_reg_151 = r_2_reg_800.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_reg_151 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c_2_reg_825 = c_2_fu_322_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ch_2_reg_868 = ch_2_fu_425_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        maxv_1_reg_935 = maxv_1_fu_697_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        maxv_2_reg_951 = maxv_2_fu_787_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        maxv_8_reg_914 = maxv_8_fu_596_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        r_2_reg_800 = r_2_fu_206_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        reg_188 = f1_q0.read();
        reg_194 = f1_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond2_fu_200_p2.read(), ap_const_lv1_0))) {
        tmp_66_cast_reg_805 = tmp_66_cast_fu_250_p1.read();
        tmp_68_reg_817 = tmp_68_fu_310_p2.read();
        tmp_69_cast_reg_811 = tmp_69_cast_fu_290_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_316_p2.read()))) {
        tmp_69_reg_830 = tmp_69_fu_340_p2.read();
        tmp_70_reg_835 = tmp_70_fu_345_p1.read();
        tmp_71_reg_840 = tmp_71_fu_349_p2.read();
        tmp_72_reg_845 = tmp_72_fu_354_p1.read();
        tmp_75_reg_850 = tmp_75_fu_381_p1.read();
        tmp_78_reg_855 = tmp_78_fu_398_p1.read();
        tmp_86_cast_reg_860 = tmp_86_cast_fu_411_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_419_p2.read()))) {
        tmp_84_reg_873 = tmp_84_fu_469_p1.read();
        tmp_85_reg_883 = tmp_85_fu_474_p2.read();
        tmp_87_reg_893 = tmp_87_fu_487_p2.read();
        tmp_88_reg_898 = tmp_71_reg_840.read().range(13, 1);
        tmp_91_reg_903 = tmp_91_fu_502_p2.read();
        tmp_92_reg_909 = tmp_92_fu_507_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_90_reg_920 = tmp_90_fu_608_p1.read();
    }
}

void maxpool1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void maxpool1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void maxpool1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void maxpool1::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void maxpool1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void maxpool1::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void maxpool1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void maxpool1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void maxpool1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void maxpool1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void maxpool1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void maxpool1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void maxpool1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void maxpool1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void maxpool1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_200_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void maxpool1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void maxpool1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_200_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void maxpool1::thread_c_2_fu_322_p2() {
    c_2_fu_322_p2 = (!c_reg_162.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(c_reg_162.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void maxpool1::thread_ch_2_fu_425_p2() {
    ch_2_fu_425_p2 = (!ch_reg_173.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ch_reg_173.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void maxpool1::thread_exitcond1_fu_316_p2() {
    exitcond1_fu_316_p2 = (!c_reg_162.read().is_01() || !ap_const_lv5_1F.is_01())? sc_lv<1>(): sc_lv<1>(c_reg_162.read() == ap_const_lv5_1F);
}

void maxpool1::thread_exitcond2_fu_200_p2() {
    exitcond2_fu_200_p2 = (!r_reg_151.read().is_01() || !ap_const_lv5_1F.is_01())? sc_lv<1>(): sc_lv<1>(r_reg_151.read() == ap_const_lv5_1F);
}

void maxpool1::thread_exitcond_fu_419_p2() {
    exitcond_fu_419_p2 = (!ch_reg_173.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ch_reg_173.read() == ap_const_lv4_8);
}

void maxpool1::thread_f1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        f1_address0 =  (sc_lv<15>) (maxv_2_reg_951.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        f1_address0 =  (sc_lv<15>) (tmp_91_reg_903.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        f1_address0 =  (sc_lv<15>) (tmp_90_fu_608_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        f1_address0 =  (sc_lv<15>) (tmp_84_fu_469_p1.read());
    } else {
        f1_address0 = "XXXXXXXXXXXXXXX";
    }
}

void maxpool1::thread_f1_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        f1_address1 =  (sc_lv<15>) (maxv_1_reg_935.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        f1_address1 =  (sc_lv<15>) (maxv_8_reg_914.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        f1_address1 =  (sc_lv<15>) (tmp_85_fu_474_p2.read());
    } else {
        f1_address1 = "XXXXXXXXXXXXXXX";
    }
}

void maxpool1::thread_f1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        f1_ce0 = ap_const_logic_1;
    } else {
        f1_ce0 = ap_const_logic_0;
    }
}

void maxpool1::thread_f1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        f1_ce1 = ap_const_logic_1;
    } else {
        f1_ce1 = ap_const_logic_0;
    }
}

void maxpool1::thread_grp_fu_184_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        grp_fu_184_p0 = reg_188.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_184_p0 = reg_194.read();
    } else {
        grp_fu_184_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void maxpool1::thread_grp_fu_184_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        grp_fu_184_p1 = reg_194.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_184_p1 = reg_188.read();
    } else {
        grp_fu_184_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void maxpool1::thread_maxv_1_fu_697_p3() {
    maxv_1_fu_697_p3 = (!tmp_53_fu_691_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_53_fu_691_p2.read()[0].to_bool())? tmp_90_reg_920.read(): maxv_8_reg_914.read());
}

void maxpool1::thread_maxv_1_to_int_fu_721_p1() {
    maxv_1_to_int_fu_721_p1 = reg_194.read();
}

void maxpool1::thread_maxv_2_fu_787_p3() {
    maxv_2_fu_787_p3 = (!tmp_62_fu_781_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_62_fu_781_p2.read()[0].to_bool())? tmp_91_reg_903.read(): maxv_1_reg_935.read());
}

void maxpool1::thread_maxv_8_fu_596_p3() {
    maxv_8_fu_596_p3 = (!tmp_44_fu_590_p2.read()[0].is_01())? sc_lv<64>(): ((tmp_44_fu_590_p2.read()[0].to_bool())? tmp_85_reg_883.read(): tmp_84_reg_873.read());
}

void maxpool1::thread_maxv_8_to_int_fu_631_p1() {
    maxv_8_to_int_fu_631_p1 = reg_194.read();
}

void maxpool1::thread_notlhs3_fu_739_p2() {
    notlhs3_fu_739_p2 = (!tmp_54_fu_707_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_54_fu_707_p4.read() != ap_const_lv8_FF);
}

void maxpool1::thread_notlhs4_fu_566_p2() {
    notlhs4_fu_566_p2 = (!tmp_38_fu_534_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_38_fu_534_p4.read() != ap_const_lv8_FF);
}

void maxpool1::thread_notlhs5_fu_757_p2() {
    notlhs5_fu_757_p2 = (!tmp_56_fu_725_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_56_fu_725_p4.read() != ap_const_lv8_FF);
}

void maxpool1::thread_notlhs6_fu_649_p2() {
    notlhs6_fu_649_p2 = (!tmp_45_fu_617_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_45_fu_617_p4.read() != ap_const_lv8_FF);
}

void maxpool1::thread_notlhs8_fu_667_p2() {
    notlhs8_fu_667_p2 = (!tmp_47_fu_635_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_47_fu_635_p4.read() != ap_const_lv8_FF);
}

void maxpool1::thread_notlhs_fu_548_p2() {
    notlhs_fu_548_p2 = (!tmp_s_fu_516_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_s_fu_516_p4.read() != ap_const_lv8_FF);
}

void maxpool1::thread_notrhs3_fu_745_p2() {
    notrhs3_fu_745_p2 = (!tmp_97_fu_717_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_97_fu_717_p1.read() == ap_const_lv23_0);
}

void maxpool1::thread_notrhs4_fu_763_p2() {
    notrhs4_fu_763_p2 = (!tmp_98_fu_735_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_98_fu_735_p1.read() == ap_const_lv23_0);
}

void maxpool1::thread_notrhs5_fu_572_p2() {
    notrhs5_fu_572_p2 = (!tmp_94_fu_544_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_94_fu_544_p1.read() == ap_const_lv23_0);
}

void maxpool1::thread_notrhs7_fu_655_p2() {
    notrhs7_fu_655_p2 = (!tmp_95_fu_627_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_95_fu_627_p1.read() == ap_const_lv23_0);
}

void maxpool1::thread_notrhs9_fu_673_p2() {
    notrhs9_fu_673_p2 = (!tmp_96_fu_645_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_96_fu_645_p1.read() == ap_const_lv23_0);
}

void maxpool1::thread_notrhs_fu_554_p2() {
    notrhs_fu_554_p2 = (!tmp_93_fu_526_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_93_fu_526_p1.read() == ap_const_lv23_0);
}

void maxpool1::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<13>) (tmp_97_cast_fu_793_p1.read());
}

void maxpool1::thread_out_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void maxpool1::thread_out_r_d0() {
    out_r_d0 = f1_q0.read();
}

void maxpool1::thread_out_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void maxpool1::thread_p_shl1_cast_fu_268_p1() {
    p_shl1_cast_fu_268_p1 = esl_zext<13,12>(tmp_64_fu_260_p3.read());
}

void maxpool1::thread_p_shl2_cast_fu_280_p1() {
    p_shl2_cast_fu_280_p1 = esl_zext<13,7>(tmp_65_fu_272_p3.read());
}

void maxpool1::thread_p_shl3_cast_fu_228_p1() {
    p_shl3_cast_fu_228_p1 = esl_zext<13,12>(tmp_55_fu_220_p3.read());
}

void maxpool1::thread_p_shl4_cast_fu_240_p1() {
    p_shl4_cast_fu_240_p1 = esl_zext<13,7>(tmp_57_fu_232_p3.read());
}

void maxpool1::thread_p_shl_cast_fu_306_p1() {
    p_shl_cast_fu_306_p1 = esl_zext<11,10>(tmp_67_fu_298_p3.read());
}

void maxpool1::thread_r_2_fu_206_p2() {
    r_2_fu_206_p2 = (!r_reg_151.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(r_reg_151.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void maxpool1::thread_tmp_1_fu_254_p2() {
    tmp_1_fu_254_p2 = (tmp_fu_212_p3.read() | ap_const_lv6_1);
}

void maxpool1::thread_tmp_38_fu_534_p4() {
    tmp_38_fu_534_p4 = v0_to_int_fu_530_p1.read().range(30, 23);
}

void maxpool1::thread_tmp_3_cast_fu_294_p1() {
    tmp_3_cast_fu_294_p1 = esl_zext<11,5>(r_reg_151.read());
}

void maxpool1::thread_tmp_40_fu_560_p2() {
    tmp_40_fu_560_p2 = (notrhs_fu_554_p2.read() | notlhs_fu_548_p2.read());
}

void maxpool1::thread_tmp_41_fu_578_p2() {
    tmp_41_fu_578_p2 = (notrhs5_fu_572_p2.read() | notlhs4_fu_566_p2.read());
}

void maxpool1::thread_tmp_42_fu_584_p2() {
    tmp_42_fu_584_p2 = (tmp_40_fu_560_p2.read() & tmp_41_fu_578_p2.read());
}

void maxpool1::thread_tmp_44_fu_590_p2() {
    tmp_44_fu_590_p2 = (tmp_42_fu_584_p2.read() & grp_fu_184_p2.read());
}

void maxpool1::thread_tmp_45_fu_617_p4() {
    tmp_45_fu_617_p4 = v2_to_int_fu_613_p1.read().range(30, 23);
}

void maxpool1::thread_tmp_47_fu_635_p4() {
    tmp_47_fu_635_p4 = maxv_8_to_int_fu_631_p1.read().range(30, 23);
}

void maxpool1::thread_tmp_49_fu_661_p2() {
    tmp_49_fu_661_p2 = (notrhs7_fu_655_p2.read() | notlhs6_fu_649_p2.read());
}

void maxpool1::thread_tmp_4_fu_328_p3() {
    tmp_4_fu_328_p3 = esl_concat<5,1>(c_reg_162.read(), ap_const_lv1_0);
}

void maxpool1::thread_tmp_50_fu_679_p2() {
    tmp_50_fu_679_p2 = (notrhs9_fu_673_p2.read() | notlhs8_fu_667_p2.read());
}

void maxpool1::thread_tmp_51_fu_685_p2() {
    tmp_51_fu_685_p2 = (tmp_49_fu_661_p2.read() & tmp_50_fu_679_p2.read());
}

void maxpool1::thread_tmp_53_fu_691_p2() {
    tmp_53_fu_691_p2 = (tmp_51_fu_685_p2.read() & grp_fu_184_p2.read());
}

void maxpool1::thread_tmp_54_fu_707_p4() {
    tmp_54_fu_707_p4 = v3_to_int_fu_703_p1.read().range(30, 23);
}

void maxpool1::thread_tmp_55_fu_220_p3() {
    tmp_55_fu_220_p3 = esl_concat<5,7>(r_reg_151.read(), ap_const_lv7_0);
}

void maxpool1::thread_tmp_56_fu_725_p4() {
    tmp_56_fu_725_p4 = maxv_1_to_int_fu_721_p1.read().range(30, 23);
}

void maxpool1::thread_tmp_57_fu_232_p3() {
    tmp_57_fu_232_p3 = esl_concat<5,2>(r_reg_151.read(), ap_const_lv2_0);
}

void maxpool1::thread_tmp_58_fu_751_p2() {
    tmp_58_fu_751_p2 = (notrhs3_fu_745_p2.read() | notlhs3_fu_739_p2.read());
}

void maxpool1::thread_tmp_59_fu_769_p2() {
    tmp_59_fu_769_p2 = (notrhs4_fu_763_p2.read() | notlhs5_fu_757_p2.read());
}

void maxpool1::thread_tmp_5_cast_fu_336_p1() {
    tmp_5_cast_fu_336_p1 = esl_zext<14,6>(tmp_4_fu_328_p3.read());
}

void maxpool1::thread_tmp_60_fu_775_p2() {
    tmp_60_fu_775_p2 = (tmp_58_fu_751_p2.read() & tmp_59_fu_769_p2.read());
}

void maxpool1::thread_tmp_62_fu_781_p2() {
    tmp_62_fu_781_p2 = (tmp_60_fu_775_p2.read() & grp_fu_184_p2.read());
}

void maxpool1::thread_tmp_63_fu_244_p2() {
    tmp_63_fu_244_p2 = (!p_shl3_cast_fu_228_p1.read().is_01() || !p_shl4_cast_fu_240_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl3_cast_fu_228_p1.read()) - sc_biguint<13>(p_shl4_cast_fu_240_p1.read()));
}

void maxpool1::thread_tmp_64_fu_260_p3() {
    tmp_64_fu_260_p3 = esl_concat<6,6>(tmp_1_fu_254_p2.read(), ap_const_lv6_0);
}

void maxpool1::thread_tmp_65_fu_272_p3() {
    tmp_65_fu_272_p3 = esl_concat<6,1>(tmp_1_fu_254_p2.read(), ap_const_lv1_0);
}

void maxpool1::thread_tmp_66_cast_fu_250_p1() {
    tmp_66_cast_fu_250_p1 = esl_sext<14,13>(tmp_63_fu_244_p2.read());
}

void maxpool1::thread_tmp_66_fu_284_p2() {
    tmp_66_fu_284_p2 = (!p_shl1_cast_fu_268_p1.read().is_01() || !p_shl2_cast_fu_280_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl1_cast_fu_268_p1.read()) - sc_biguint<13>(p_shl2_cast_fu_280_p1.read()));
}

void maxpool1::thread_tmp_67_fu_298_p3() {
    tmp_67_fu_298_p3 = esl_concat<5,5>(r_reg_151.read(), ap_const_lv5_0);
}

void maxpool1::thread_tmp_68_fu_310_p2() {
    tmp_68_fu_310_p2 = (!p_shl_cast_fu_306_p1.read().is_01() || !tmp_3_cast_fu_294_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_306_p1.read()) - sc_biguint<11>(tmp_3_cast_fu_294_p1.read()));
}

void maxpool1::thread_tmp_69_cast_fu_290_p1() {
    tmp_69_cast_fu_290_p1 = esl_sext<14,13>(tmp_66_fu_284_p2.read());
}

void maxpool1::thread_tmp_69_fu_340_p2() {
    tmp_69_fu_340_p2 = (!tmp_66_cast_reg_805.read().is_01() || !tmp_5_cast_fu_336_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp_66_cast_reg_805.read()) + sc_biguint<14>(tmp_5_cast_fu_336_p1.read()));
}

void maxpool1::thread_tmp_6_fu_358_p2() {
    tmp_6_fu_358_p2 = (tmp_4_fu_328_p3.read() | ap_const_lv6_1);
}

void maxpool1::thread_tmp_70_fu_345_p1() {
    tmp_70_fu_345_p1 = tmp_69_fu_340_p2.read().range(1-1, 0);
}

void maxpool1::thread_tmp_71_fu_349_p2() {
    tmp_71_fu_349_p2 = (!tmp_69_cast_reg_811.read().is_01() || !tmp_5_cast_fu_336_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp_69_cast_reg_811.read()) + sc_biguint<14>(tmp_5_cast_fu_336_p1.read()));
}

void maxpool1::thread_tmp_72_fu_354_p1() {
    tmp_72_fu_354_p1 = tmp_71_fu_349_p2.read().range(1-1, 0);
}

void maxpool1::thread_tmp_73_fu_368_p2() {
    tmp_73_fu_368_p2 = (!tmp_66_cast_reg_805.read().is_01() || !tmp_7_cast_fu_364_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp_66_cast_reg_805.read()) + sc_biguint<14>(tmp_7_cast_fu_364_p1.read()));
}

void maxpool1::thread_tmp_74_fu_373_p3() {
    tmp_74_fu_373_p3 = esl_concat<14,3>(tmp_73_fu_368_p2.read(), ap_const_lv3_0);
}

void maxpool1::thread_tmp_75_fu_381_p1() {
    tmp_75_fu_381_p1 = esl_sext<64,17>(tmp_74_fu_373_p3.read());
}

void maxpool1::thread_tmp_76_fu_385_p2() {
    tmp_76_fu_385_p2 = (!tmp_69_cast_reg_811.read().is_01() || !tmp_7_cast_fu_364_p1.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp_69_cast_reg_811.read()) + sc_biguint<14>(tmp_7_cast_fu_364_p1.read()));
}

void maxpool1::thread_tmp_77_fu_390_p3() {
    tmp_77_fu_390_p3 = esl_concat<14,3>(tmp_76_fu_385_p2.read(), ap_const_lv3_0);
}

void maxpool1::thread_tmp_78_fu_398_p1() {
    tmp_78_fu_398_p1 = esl_sext<64,17>(tmp_77_fu_390_p3.read());
}

void maxpool1::thread_tmp_79_fu_406_p2() {
    tmp_79_fu_406_p2 = (!tmp_68_reg_817.read().is_01() || !tmp_8_cast_fu_402_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_68_reg_817.read()) + sc_biguint<11>(tmp_8_cast_fu_402_p1.read()));
}

void maxpool1::thread_tmp_7_cast_fu_364_p1() {
    tmp_7_cast_fu_364_p1 = esl_zext<14,6>(tmp_6_fu_358_p2.read());
}

void maxpool1::thread_tmp_80_fu_439_p3() {
    tmp_80_fu_439_p3 = esl_concat<1,3>(tmp_70_reg_835.read(), ap_const_lv3_0);
}

void maxpool1::thread_tmp_81_fu_446_p2() {
    tmp_81_fu_446_p2 = (tmp_80_fu_439_p3.read() | ch_reg_173.read());
}

void maxpool1::thread_tmp_82_fu_452_p4() {
    tmp_82_fu_452_p4 = tmp_69_reg_830.read().range(13, 1);
}

void maxpool1::thread_tmp_83_fu_461_p3() {
    tmp_83_fu_461_p3 = esl_concat<13,4>(tmp_82_fu_452_p4.read(), tmp_81_fu_446_p2.read());
}

void maxpool1::thread_tmp_84_fu_469_p1() {
    tmp_84_fu_469_p1 = esl_sext<64,17>(tmp_83_fu_461_p3.read());
}

void maxpool1::thread_tmp_85_fu_474_p2() {
    tmp_85_fu_474_p2 = (!tmp_75_reg_850.read().is_01() || !tmp_9_fu_431_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(tmp_75_reg_850.read()) + sc_biguint<64>(tmp_9_fu_431_p1.read()));
}

void maxpool1::thread_tmp_86_cast_fu_411_p3() {
    tmp_86_cast_fu_411_p3 = esl_concat<11,3>(tmp_79_fu_406_p2.read(), ap_const_lv3_0);
}

void maxpool1::thread_tmp_86_fu_480_p3() {
    tmp_86_fu_480_p3 = esl_concat<1,3>(tmp_72_reg_845.read(), ap_const_lv3_0);
}

void maxpool1::thread_tmp_87_fu_487_p2() {
    tmp_87_fu_487_p2 = (tmp_86_fu_480_p3.read() | ch_reg_173.read());
}

void maxpool1::thread_tmp_89_fu_602_p3() {
    tmp_89_fu_602_p3 = esl_concat<13,4>(tmp_88_reg_898.read(), tmp_87_reg_893.read());
}

void maxpool1::thread_tmp_8_cast_fu_402_p1() {
    tmp_8_cast_fu_402_p1 = esl_zext<11,5>(c_reg_162.read());
}

void maxpool1::thread_tmp_90_fu_608_p1() {
    tmp_90_fu_608_p1 = esl_sext<64,17>(tmp_89_fu_602_p3.read());
}

void maxpool1::thread_tmp_91_fu_502_p2() {
    tmp_91_fu_502_p2 = (!tmp_78_reg_855.read().is_01() || !tmp_9_fu_431_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(tmp_78_reg_855.read()) + sc_biguint<64>(tmp_9_fu_431_p1.read()));
}

void maxpool1::thread_tmp_92_fu_507_p2() {
    tmp_92_fu_507_p2 = (!tmp_86_cast_reg_860.read().is_01() || !tmp_9_cast_fu_435_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_86_cast_reg_860.read()) + sc_biguint<14>(tmp_9_cast_fu_435_p1.read()));
}

void maxpool1::thread_tmp_93_fu_526_p1() {
    tmp_93_fu_526_p1 = v1_to_int_fu_512_p1.read().range(23-1, 0);
}

void maxpool1::thread_tmp_94_fu_544_p1() {
    tmp_94_fu_544_p1 = v0_to_int_fu_530_p1.read().range(23-1, 0);
}

void maxpool1::thread_tmp_95_fu_627_p1() {
    tmp_95_fu_627_p1 = v2_to_int_fu_613_p1.read().range(23-1, 0);
}

void maxpool1::thread_tmp_96_fu_645_p1() {
    tmp_96_fu_645_p1 = maxv_8_to_int_fu_631_p1.read().range(23-1, 0);
}

void maxpool1::thread_tmp_97_cast_fu_793_p1() {
    tmp_97_cast_fu_793_p1 = esl_zext<64,14>(tmp_92_reg_909.read());
}

void maxpool1::thread_tmp_97_fu_717_p1() {
    tmp_97_fu_717_p1 = v3_to_int_fu_703_p1.read().range(23-1, 0);
}

void maxpool1::thread_tmp_98_fu_735_p1() {
    tmp_98_fu_735_p1 = maxv_1_to_int_fu_721_p1.read().range(23-1, 0);
}

void maxpool1::thread_tmp_9_cast_fu_435_p1() {
    tmp_9_cast_fu_435_p1 = esl_zext<14,4>(ch_reg_173.read());
}

void maxpool1::thread_tmp_9_fu_431_p1() {
    tmp_9_fu_431_p1 = esl_zext<64,4>(ch_reg_173.read());
}

void maxpool1::thread_tmp_fu_212_p3() {
    tmp_fu_212_p3 = esl_concat<5,1>(r_reg_151.read(), ap_const_lv1_0);
}

void maxpool1::thread_tmp_s_fu_516_p4() {
    tmp_s_fu_516_p4 = v1_to_int_fu_512_p1.read().range(30, 23);
}

void maxpool1::thread_v0_to_int_fu_530_p1() {
    v0_to_int_fu_530_p1 = reg_188.read();
}

void maxpool1::thread_v1_to_int_fu_512_p1() {
    v1_to_int_fu_512_p1 = reg_194.read();
}

void maxpool1::thread_v2_to_int_fu_613_p1() {
    v2_to_int_fu_613_p1 = reg_188.read();
}

void maxpool1::thread_v3_to_int_fu_703_p1() {
    v3_to_int_fu_703_p1 = reg_188.read();
}

void maxpool1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond2_fu_200_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond1_fu_316_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond_fu_419_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
            break;
    }
}

}

