// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        out_0_din,
        out_0_full_n,
        out_0_write,
        out_1_din,
        out_1_full_n,
        out_1_write,
        out_2_din,
        out_2_full_n,
        out_2_write,
        out_3_din,
        out_3_full_n,
        out_3_write,
        out_4_din,
        out_4_full_n,
        out_4_write,
        out_5_din,
        out_5_full_n,
        out_5_write,
        out_6_din,
        out_6_full_n,
        out_6_write,
        out_7_din,
        out_7_full_n,
        out_7_write
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [13:0] in_r_address0;
output   in_r_ce0;
input  [31:0] in_r_q0;
output  [31:0] out_0_din;
input   out_0_full_n;
output   out_0_write;
output  [31:0] out_1_din;
input   out_1_full_n;
output   out_1_write;
output  [31:0] out_2_din;
input   out_2_full_n;
output   out_2_write;
output  [31:0] out_3_din;
input   out_3_full_n;
output   out_3_write;
output  [31:0] out_4_din;
input   out_4_full_n;
output   out_4_write;
output  [31:0] out_5_din;
input   out_5_full_n;
output   out_5_write;
output  [31:0] out_6_din;
input   out_6_full_n;
output   out_6_write;
output  [31:0] out_7_din;
input   out_7_full_n;
output   out_7_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg in_r_ce0;
reg out_0_write;
reg out_1_write;
reg out_2_write;
reg out_3_write;
reg out_4_write;
reg out_5_write;
reg out_6_write;
reg out_7_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    linbu_4_0_0_ce0;
reg    linbu_4_0_0_we0;
wire   [31:0] linbu_4_0_0_q0;
reg    linbu_4_0_1_ce0;
reg    linbu_4_0_1_we0;
wire   [31:0] linbu_4_0_1_q0;
reg    linbu_4_0_2_ce0;
reg    linbu_4_0_2_we0;
wire   [31:0] linbu_4_0_2_q0;
reg    linbu_4_1_0_ce0;
reg    linbu_4_1_0_we0;
wire   [31:0] linbu_4_1_0_q0;
reg    linbu_4_1_1_ce0;
reg    linbu_4_1_1_we0;
wire   [31:0] linbu_4_1_1_q0;
reg    linbu_4_1_2_ce0;
reg    linbu_4_1_2_we0;
wire   [31:0] linbu_4_1_2_q0;
reg    out_0_blk_n;
wire    ap_CS_fsm_state19;
reg   [2:0] tmp_74_reg_1450;
reg    out_1_blk_n;
reg    out_2_blk_n;
reg    out_3_blk_n;
reg    out_4_blk_n;
reg    out_5_blk_n;
reg    out_6_blk_n;
reg    out_7_blk_n;
wire   [6:0] r_1_fu_562_p2;
reg   [6:0] r_1_reg_1342;
wire    ap_CS_fsm_state2;
wire   [13:0] tmp_36_cast_fu_576_p1;
reg   [13:0] tmp_36_cast_reg_1347;
wire   [0:0] exitcond6_fu_556_p2;
wire   [0:0] icmp_fu_590_p2;
reg   [0:0] icmp_reg_1352;
wire   [6:0] c_1_fu_602_p2;
reg   [6:0] c_1_reg_1360;
wire    ap_CS_fsm_state3;
wire   [14:0] tmp_24_fu_643_p2;
reg   [14:0] tmp_24_reg_1365;
wire   [0:0] exitcond5_fu_596_p2;
reg   [5:0] linbu_4_0_0_addr_reg_1370;
reg   [5:0] linbu_4_0_1_addr_reg_1375;
reg   [5:0] linbu_4_0_2_addr_reg_1380;
reg   [5:0] linbu_4_1_0_addr_reg_1385;
reg   [5:0] linbu_4_1_1_addr_reg_1390;
reg   [5:0] linbu_4_1_2_addr_reg_1395;
wire   [1:0] ic_6_fu_655_p2;
reg   [1:0] ic_6_reg_1403;
wire    ap_CS_fsm_state4;
wire   [0:0] exitcond4_fu_649_p2;
wire   [0:0] or_cond_fu_853_p2;
reg   [0:0] or_cond_reg_1413;
wire   [3:0] oc_2_fu_936_p2;
reg   [3:0] oc_2_reg_1420;
wire    ap_CS_fsm_state6;
wire   [1:0] kr_1_fu_948_p2;
reg   [1:0] kr_1_reg_1428;
wire    ap_CS_fsm_state7;
wire   [3:0] tmp_6_fu_966_p2;
reg   [3:0] tmp_6_reg_1433;
wire   [0:0] exitcond2_fu_942_p2;
wire   [31:0] sum_3_fu_1014_p3;
reg   [31:0] sum_3_reg_1438;
wire   [2:0] tmp_74_fu_1022_p1;
wire   [1:0] kc_1_fu_1032_p2;
reg   [1:0] kc_1_reg_1457;
wire    ap_CS_fsm_state8;
wire   [4:0] tmp_4_fu_1063_p2;
reg   [4:0] tmp_4_reg_1462;
wire   [0:0] exitcond1_fu_1026_p2;
wire   [1:0] ic_5_fu_1075_p2;
reg   [1:0] ic_5_reg_1470;
wire    ap_CS_fsm_state9;
wire   [31:0] tmp_30_fu_1117_p29;
reg   [31:0] tmp_30_reg_1475;
wire   [0:0] exitcond_fu_1069_p2;
wire   [31:0] grp_fu_491_p2;
reg   [31:0] tmp_12_reg_1480;
wire    ap_CS_fsm_state13;
wire   [31:0] grp_fu_486_p2;
wire    ap_CS_fsm_state18;
reg   [6:0] r_reg_370;
reg    ap_block_state1;
reg   [6:0] c_reg_381;
wire   [0:0] exitcond3_fu_930_p2;
wire   [1:0] ap_phi_mux_ic_phi_fu_397_p4;
reg   [1:0] ic_reg_393;
wire    ap_CS_fsm_state5;
reg   [3:0] oc_reg_405;
wire    ap_CS_fsm_state20;
reg   [1:0] kr_reg_417;
reg   [31:0] sum7_reg_428;
reg   [1:0] kc_reg_440;
reg   [31:0] sum_1_reg_451;
reg   [1:0] ic_1_reg_463;
reg   [31:0] sum_2_reg_474;
wire   [63:0] tmp_1_fu_608_p1;
wire   [63:0] tmp_46_cast_fu_670_p1;
reg    ap_block_state19;
reg   [31:0] win_buf_0_0_2_fu_118;
wire   [31:0] win_buf_0_0_0_fu_675_p5;
reg   [31:0] win_buf_0_0_2_1_fu_122;
reg   [31:0] win_buf_0_0_2_2_fu_126;
reg   [31:0] win_buf_0_1_2_fu_130;
wire   [31:0] win_buf_0_1_0_fu_702_p5;
reg   [31:0] win_buf_0_1_2_1_fu_134;
reg   [31:0] win_buf_0_1_2_2_fu_138;
reg   [31:0] win_buf_0_2_2_fu_142;
wire   [31:0] win_buf_0_2_0_fu_858_p5;
reg   [31:0] win_buf_0_2_2_1_fu_146;
reg   [31:0] win_buf_0_2_2_2_fu_150;
reg   [31:0] win_buf_1_0_2_fu_154;
wire   [31:0] win_buf_1_0_0_fu_729_p5;
reg   [31:0] win_buf_1_0_2_1_fu_158;
reg   [31:0] win_buf_1_0_2_2_fu_162;
reg   [31:0] win_buf_1_1_2_fu_166;
wire   [31:0] win_buf_1_1_0_fu_756_p5;
reg   [31:0] win_buf_1_1_2_1_fu_170;
reg   [31:0] win_buf_1_1_2_2_fu_174;
reg   [31:0] win_buf_1_2_2_fu_178;
wire   [31:0] win_buf_1_2_0_fu_870_p5;
reg   [31:0] win_buf_1_2_2_1_fu_182;
reg   [31:0] win_buf_1_2_2_2_fu_186;
reg   [31:0] win_buf_2_0_2_fu_190;
wire   [31:0] win_buf_2_0_0_fu_783_p5;
reg   [31:0] win_buf_2_0_2_1_fu_194;
reg   [31:0] win_buf_2_0_2_2_fu_198;
reg   [31:0] win_buf_2_1_2_fu_202;
wire   [31:0] win_buf_2_1_0_fu_810_p5;
reg   [31:0] win_buf_2_1_2_1_fu_206;
reg   [31:0] win_buf_2_1_2_2_fu_210;
reg   [31:0] win_buf_2_2_2_fu_214;
reg   [31:0] win_buf_2_2_2_1_fu_218;
reg   [31:0] win_buf_2_2_2_2_fu_222;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state10;
wire   [12:0] tmp_fu_568_p3;
wire   [5:0] tmp_70_fu_580_p4;
wire   [13:0] tmp_1_cast_fu_618_p1;
wire   [13:0] tmp_s_fu_622_p2;
wire   [12:0] tmp_71_fu_631_p1;
wire   [14:0] p_shl2_cast_fu_635_p3;
wire   [14:0] tmp_37_cast_fu_627_p1;
wire   [14:0] tmp_3_cast_fu_661_p1;
wire   [14:0] tmp_26_fu_665_p2;
wire   [5:0] tmp_72_fu_837_p4;
wire   [0:0] icmp5_fu_847_p2;
wire   [3:0] p_shl1_fu_958_p3;
wire   [3:0] tmp_5_fu_954_p1;
wire   [31:0] sum7_to_int_fu_972_p1;
wire   [7:0] tmp_25_fu_976_p4;
wire   [22:0] tmp_73_fu_986_p1;
wire   [0:0] notrhs_fu_996_p2;
wire   [0:0] notlhs_fu_990_p2;
wire   [0:0] tmp_27_fu_1002_p2;
wire   [0:0] tmp_28_fu_496_p2;
wire   [0:0] tmp_29_fu_1008_p2;
wire   [3:0] tmp_7_fu_1038_p1;
wire   [3:0] tmp_8_fu_1042_p2;
wire   [2:0] tmp_75_fu_1051_p1;
wire   [4:0] p_shl_fu_1055_p3;
wire   [4:0] tmp_9_fu_1047_p1;
wire   [4:0] tmp_10_fu_1108_p1;
wire   [4:0] tmp_30_fu_1117_p28;
reg   [19:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 20'd1;
end

conv1_linbu_4_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
linbu_4_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_4_0_0_addr_reg_1370),
    .ce0(linbu_4_0_0_ce0),
    .we0(linbu_4_0_0_we0),
    .d0(win_buf_1_2_0_fu_870_p5),
    .q0(linbu_4_0_0_q0)
);

conv1_linbu_4_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
linbu_4_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_4_0_1_addr_reg_1375),
    .ce0(linbu_4_0_1_ce0),
    .we0(linbu_4_0_1_we0),
    .d0(win_buf_1_2_0_fu_870_p5),
    .q0(linbu_4_0_1_q0)
);

conv1_linbu_4_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
linbu_4_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_4_0_2_addr_reg_1380),
    .ce0(linbu_4_0_2_ce0),
    .we0(linbu_4_0_2_we0),
    .d0(win_buf_1_2_0_fu_870_p5),
    .q0(linbu_4_0_2_q0)
);

conv1_linbu_4_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
linbu_4_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_4_1_0_addr_reg_1385),
    .ce0(linbu_4_1_0_ce0),
    .we0(linbu_4_1_0_we0),
    .d0(in_r_q0),
    .q0(linbu_4_1_0_q0)
);

conv1_linbu_4_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
linbu_4_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_4_1_1_addr_reg_1390),
    .ce0(linbu_4_1_1_ce0),
    .we0(linbu_4_1_1_we0),
    .d0(in_r_q0),
    .q0(linbu_4_1_1_q0)
);

conv1_linbu_4_0_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
linbu_4_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_4_1_2_addr_reg_1395),
    .ce0(linbu_4_1_2_ce0),
    .we0(linbu_4_1_2_we0),
    .d0(in_r_q0),
    .q0(linbu_4_1_2_q0)
);

topp_fadd_32ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fadd_32ns_32bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_2_reg_474),
    .din1(tmp_12_reg_1480),
    .ce(1'b1),
    .dout(grp_fu_486_p2)
);

topp_fmul_32ns_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fmul_32ns_32cud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_30_reg_1475),
    .din1(32'd0),
    .ce(1'b1),
    .dout(grp_fu_491_p2)
);

topp_fcmp_32ns_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
topp_fcmp_32ns_32dEe_U3(
    .din0(sum7_reg_428),
    .din1(32'd0),
    .opcode(5'd4),
    .dout(tmp_28_fu_496_p2)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U4(
    .din0(win_buf_0_1_2_fu_130),
    .din1(win_buf_0_1_2_1_fu_134),
    .din2(win_buf_0_1_2_2_fu_138),
    .din3(ic_reg_393),
    .dout(win_buf_0_0_0_fu_675_p5)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U5(
    .din0(win_buf_0_2_2_fu_142),
    .din1(win_buf_0_2_2_1_fu_146),
    .din2(win_buf_0_2_2_2_fu_150),
    .din3(ic_reg_393),
    .dout(win_buf_0_1_0_fu_702_p5)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U6(
    .din0(win_buf_1_1_2_fu_166),
    .din1(win_buf_1_1_2_1_fu_170),
    .din2(win_buf_1_1_2_2_fu_174),
    .din3(ic_reg_393),
    .dout(win_buf_1_0_0_fu_729_p5)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U7(
    .din0(win_buf_1_2_2_fu_178),
    .din1(win_buf_1_2_2_1_fu_182),
    .din2(win_buf_1_2_2_2_fu_186),
    .din3(ic_reg_393),
    .dout(win_buf_1_1_0_fu_756_p5)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U8(
    .din0(win_buf_2_1_2_fu_202),
    .din1(win_buf_2_1_2_1_fu_206),
    .din2(win_buf_2_1_2_2_fu_210),
    .din3(ic_reg_393),
    .dout(win_buf_2_0_0_fu_783_p5)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U9(
    .din0(win_buf_2_2_2_fu_214),
    .din1(win_buf_2_2_2_1_fu_218),
    .din2(win_buf_2_2_2_2_fu_222),
    .din3(ic_reg_393),
    .dout(win_buf_2_1_0_fu_810_p5)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U10(
    .din0(linbu_4_0_0_q0),
    .din1(linbu_4_0_1_q0),
    .din2(linbu_4_0_2_q0),
    .din3(ic_reg_393),
    .dout(win_buf_0_2_0_fu_858_p5)
);

topp_mux_32_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
topp_mux_32_32_1_1_U11(
    .din0(linbu_4_1_0_q0),
    .din1(linbu_4_1_1_q0),
    .din2(linbu_4_1_2_q0),
    .din3(ic_reg_393),
    .dout(win_buf_1_2_0_fu_870_p5)
);

topp_mux_275_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
topp_mux_275_32_1_1_U12(
    .din0(win_buf_0_0_2_fu_118),
    .din1(win_buf_0_0_2_1_fu_122),
    .din2(win_buf_0_0_2_2_fu_126),
    .din3(win_buf_0_1_2_fu_130),
    .din4(win_buf_0_1_2_1_fu_134),
    .din5(win_buf_0_1_2_2_fu_138),
    .din6(win_buf_0_2_2_fu_142),
    .din7(win_buf_0_2_2_1_fu_146),
    .din8(win_buf_0_2_2_2_fu_150),
    .din9(win_buf_1_0_2_fu_154),
    .din10(win_buf_1_0_2_1_fu_158),
    .din11(win_buf_1_0_2_2_fu_162),
    .din12(win_buf_1_1_2_fu_166),
    .din13(win_buf_1_1_2_1_fu_170),
    .din14(win_buf_1_1_2_2_fu_174),
    .din15(win_buf_1_2_2_fu_178),
    .din16(win_buf_1_2_2_1_fu_182),
    .din17(win_buf_1_2_2_2_fu_186),
    .din18(win_buf_2_0_2_fu_190),
    .din19(win_buf_2_0_2_1_fu_194),
    .din20(win_buf_2_0_2_2_fu_198),
    .din21(win_buf_2_1_2_fu_202),
    .din22(win_buf_2_1_2_1_fu_206),
    .din23(win_buf_2_1_2_2_fu_210),
    .din24(win_buf_2_2_2_fu_214),
    .din25(win_buf_2_2_2_1_fu_218),
    .din26(win_buf_2_2_2_2_fu_222),
    .din27(tmp_30_fu_1117_p28),
    .dout(tmp_30_fu_1117_p29)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_fu_556_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & ((exitcond3_fu_930_p2 == 1'd1) | (or_cond_reg_1413 == 1'd0)))) begin
        c_reg_381 <= c_1_reg_1360;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_fu_556_p2 == 1'd0))) begin
        c_reg_381 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond1_fu_1026_p2 == 1'd0))) begin
        ic_1_reg_463 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        ic_1_reg_463 <= ic_5_reg_1470;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ic_reg_393 <= ic_6_reg_1403;
    end else if (((1'b1 == ap_CS_fsm_state3) & (exitcond5_fu_596_p2 == 1'd0))) begin
        ic_reg_393 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_1069_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        kc_reg_440 <= kc_1_reg_1457;
    end else if (((1'b1 == ap_CS_fsm_state7) & (exitcond2_fu_942_p2 == 1'd0))) begin
        kc_reg_440 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_reg_1413 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (exitcond3_fu_930_p2 == 1'd0))) begin
        kr_reg_417 <= 2'd0;
    end else if (((exitcond1_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        kr_reg_417 <= kr_1_reg_1428;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_853_p2 == 1'd1) & (exitcond4_fu_649_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        oc_reg_405 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        oc_reg_405 <= oc_2_reg_1420;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5_fu_596_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        r_reg_370 <= r_1_reg_1342;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        r_reg_370 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_reg_1413 == 1'd1) & (1'b1 == ap_CS_fsm_state6) & (exitcond3_fu_930_p2 == 1'd0))) begin
        sum7_reg_428 <= 32'd0;
    end else if (((exitcond1_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        sum7_reg_428 <= sum_1_reg_451;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_1069_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        sum_1_reg_451 <= sum_2_reg_474;
    end else if (((1'b1 == ap_CS_fsm_state7) & (exitcond2_fu_942_p2 == 1'd0))) begin
        sum_1_reg_451 <= sum7_reg_428;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond1_fu_1026_p2 == 1'd0))) begin
        sum_2_reg_474 <= sum_1_reg_451;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        sum_2_reg_474 <= grp_fu_486_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c_1_reg_1360 <= c_1_fu_602_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ic_5_reg_1470 <= ic_5_fu_1075_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ic_6_reg_1403 <= ic_6_fu_655_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_fu_556_p2 == 1'd0))) begin
        icmp_reg_1352 <= icmp_fu_590_p2;
        tmp_36_cast_reg_1347[12 : 6] <= tmp_36_cast_fu_576_p1[12 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        kc_1_reg_1457 <= kc_1_fu_1032_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        kr_1_reg_1428 <= kr_1_fu_948_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond5_fu_596_p2 == 1'd0))) begin
        linbu_4_0_0_addr_reg_1370 <= tmp_1_fu_608_p1;
        linbu_4_0_1_addr_reg_1375 <= tmp_1_fu_608_p1;
        linbu_4_0_2_addr_reg_1380 <= tmp_1_fu_608_p1;
        linbu_4_1_0_addr_reg_1385 <= tmp_1_fu_608_p1;
        linbu_4_1_1_addr_reg_1390 <= tmp_1_fu_608_p1;
        linbu_4_1_2_addr_reg_1395 <= tmp_1_fu_608_p1;
        tmp_24_reg_1365 <= tmp_24_fu_643_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_reg_1413 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        oc_2_reg_1420 <= oc_2_fu_936_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_649_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        or_cond_reg_1413 <= or_cond_fu_853_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_1_reg_1342 <= r_1_fu_562_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        sum_3_reg_1438 <= sum_3_fu_1014_p3;
        tmp_74_reg_1450 <= tmp_74_fu_1022_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_12_reg_1480 <= grp_fu_491_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (exitcond_fu_1069_p2 == 1'd0))) begin
        tmp_30_reg_1475 <= tmp_30_fu_1117_p29;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond1_fu_1026_p2 == 1'd0))) begin
        tmp_4_reg_1462 <= tmp_4_fu_1063_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond2_fu_942_p2 == 1'd0))) begin
        tmp_6_reg_1433 <= tmp_6_fu_966_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ic_phi_fu_397_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state4) & (exitcond4_fu_649_p2 == 1'd0))) begin
        win_buf_0_0_2_1_fu_122 <= win_buf_0_0_0_fu_675_p5;
        win_buf_0_1_2_1_fu_134 <= win_buf_0_1_0_fu_702_p5;
        win_buf_1_0_2_1_fu_158 <= win_buf_1_0_0_fu_729_p5;
        win_buf_1_1_2_1_fu_170 <= win_buf_1_1_0_fu_756_p5;
        win_buf_2_0_2_1_fu_194 <= win_buf_2_0_0_fu_783_p5;
        win_buf_2_1_2_1_fu_206 <= win_buf_2_1_0_fu_810_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_ic_phi_fu_397_p4 == 2'd1) & ~(ap_phi_mux_ic_phi_fu_397_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state4) & (exitcond4_fu_649_p2 == 1'd0))) begin
        win_buf_0_0_2_2_fu_126 <= win_buf_0_0_0_fu_675_p5;
        win_buf_0_1_2_2_fu_138 <= win_buf_0_1_0_fu_702_p5;
        win_buf_1_0_2_2_fu_162 <= win_buf_1_0_0_fu_729_p5;
        win_buf_1_1_2_2_fu_174 <= win_buf_1_1_0_fu_756_p5;
        win_buf_2_0_2_2_fu_198 <= win_buf_2_0_0_fu_783_p5;
        win_buf_2_1_2_2_fu_210 <= win_buf_2_1_0_fu_810_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ic_phi_fu_397_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state4) & (exitcond4_fu_649_p2 == 1'd0))) begin
        win_buf_0_0_2_fu_118 <= win_buf_0_0_0_fu_675_p5;
        win_buf_0_1_2_fu_130 <= win_buf_0_1_0_fu_702_p5;
        win_buf_1_0_2_fu_154 <= win_buf_1_0_0_fu_729_p5;
        win_buf_1_1_2_fu_166 <= win_buf_1_1_0_fu_756_p5;
        win_buf_2_0_2_fu_190 <= win_buf_2_0_0_fu_783_p5;
        win_buf_2_1_2_fu_202 <= win_buf_2_1_0_fu_810_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((ic_reg_393 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        win_buf_0_2_2_1_fu_146 <= win_buf_0_2_0_fu_858_p5;
        win_buf_1_2_2_1_fu_182 <= win_buf_1_2_0_fu_870_p5;
        win_buf_2_2_2_1_fu_218 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ic_reg_393 == 2'd1) & ~(ic_reg_393 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        win_buf_0_2_2_2_fu_150 <= win_buf_0_2_0_fu_858_p5;
        win_buf_1_2_2_2_fu_186 <= win_buf_1_2_0_fu_870_p5;
        win_buf_2_2_2_2_fu_222 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ic_reg_393 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        win_buf_0_2_2_fu_142 <= win_buf_0_2_0_fu_858_p5;
        win_buf_1_2_2_fu_178 <= win_buf_1_2_0_fu_870_p5;
        win_buf_2_2_2_fu_214 <= in_r_q0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_fu_556_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in_r_ce0 = 1'b1;
    end else begin
        in_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_fu_556_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linbu_4_0_0_ce0 = 1'b1;
    end else begin
        linbu_4_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ic_reg_393 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linbu_4_0_0_we0 = 1'b1;
    end else begin
        linbu_4_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linbu_4_0_1_ce0 = 1'b1;
    end else begin
        linbu_4_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ic_reg_393 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        linbu_4_0_1_we0 = 1'b1;
    end else begin
        linbu_4_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linbu_4_0_2_ce0 = 1'b1;
    end else begin
        linbu_4_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(ic_reg_393 == 2'd1) & ~(ic_reg_393 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linbu_4_0_2_we0 = 1'b1;
    end else begin
        linbu_4_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linbu_4_1_0_ce0 = 1'b1;
    end else begin
        linbu_4_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ic_reg_393 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linbu_4_1_0_we0 = 1'b1;
    end else begin
        linbu_4_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linbu_4_1_1_ce0 = 1'b1;
    end else begin
        linbu_4_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ic_reg_393 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        linbu_4_1_1_we0 = 1'b1;
    end else begin
        linbu_4_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        linbu_4_1_2_ce0 = 1'b1;
    end else begin
        linbu_4_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(ic_reg_393 == 2'd1) & ~(ic_reg_393 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        linbu_4_1_2_we0 = 1'b1;
    end else begin
        linbu_4_1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd0))) begin
        out_0_blk_n = out_0_full_n;
    end else begin
        out_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd0))) begin
        out_0_write = 1'b1;
    end else begin
        out_0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd1))) begin
        out_1_blk_n = out_1_full_n;
    end else begin
        out_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd1))) begin
        out_1_write = 1'b1;
    end else begin
        out_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd2))) begin
        out_2_blk_n = out_2_full_n;
    end else begin
        out_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd2))) begin
        out_2_write = 1'b1;
    end else begin
        out_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd3))) begin
        out_3_blk_n = out_3_full_n;
    end else begin
        out_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd3))) begin
        out_3_write = 1'b1;
    end else begin
        out_3_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd4))) begin
        out_4_blk_n = out_4_full_n;
    end else begin
        out_4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd4))) begin
        out_4_write = 1'b1;
    end else begin
        out_4_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd5))) begin
        out_5_blk_n = out_5_full_n;
    end else begin
        out_5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd5))) begin
        out_5_write = 1'b1;
    end else begin
        out_5_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd6))) begin
        out_6_blk_n = out_6_full_n;
    end else begin
        out_6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd6))) begin
        out_6_write = 1'b1;
    end else begin
        out_6_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd7))) begin
        out_7_blk_n = out_7_full_n;
    end else begin
        out_7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19) & (tmp_74_reg_1450 == 3'd7))) begin
        out_7_write = 1'b1;
    end else begin
        out_7_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_fu_556_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond5_fu_596_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond4_fu_649_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & ((exitcond3_fu_930_p2 == 1'd1) | (or_cond_reg_1413 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((exitcond2_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((exitcond1_fu_1026_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((exitcond_fu_1069_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state19 : begin
            if ((~(((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0))) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state19 = (((out_7_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd7)) | ((out_6_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd6)) | ((out_5_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd5)) | ((out_4_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd4)) | ((out_3_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd3)) | ((out_2_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd2)) | ((out_1_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd1)) | ((out_0_full_n == 1'b0) & (tmp_74_reg_1450 == 3'd0)));
end

assign ap_phi_mux_ic_phi_fu_397_p4 = ic_reg_393;

assign ap_ready = internal_ap_ready;

assign c_1_fu_602_p2 = (c_reg_381 + 7'd1);

assign exitcond1_fu_1026_p2 = ((kc_reg_440 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond2_fu_942_p2 = ((kr_reg_417 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond3_fu_930_p2 = ((oc_reg_405 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond4_fu_649_p2 = ((ic_reg_393 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond5_fu_596_p2 = ((c_reg_381 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond6_fu_556_p2 = ((r_reg_370 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond_fu_1069_p2 = ((ic_1_reg_463 == 2'd3) ? 1'b1 : 1'b0);

assign ic_5_fu_1075_p2 = (ic_1_reg_463 + 2'd1);

assign ic_6_fu_655_p2 = (ic_reg_393 + 2'd1);

assign icmp5_fu_847_p2 = ((tmp_72_fu_837_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_fu_590_p2 = ((tmp_70_fu_580_p4 != 6'd0) ? 1'b1 : 1'b0);

assign in_r_address0 = tmp_46_cast_fu_670_p1;

assign kc_1_fu_1032_p2 = (kc_reg_440 + 2'd1);

assign kr_1_fu_948_p2 = (kr_reg_417 + 2'd1);

assign notlhs_fu_990_p2 = ((tmp_25_fu_976_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_996_p2 = ((tmp_73_fu_986_p1 == 23'd0) ? 1'b1 : 1'b0);

assign oc_2_fu_936_p2 = (oc_reg_405 + 4'd1);

assign or_cond_fu_853_p2 = (icmp_reg_1352 & icmp5_fu_847_p2);

assign out_0_din = sum_3_reg_1438;

assign out_1_din = sum_3_reg_1438;

assign out_2_din = sum_3_reg_1438;

assign out_3_din = sum_3_reg_1438;

assign out_4_din = sum_3_reg_1438;

assign out_5_din = sum_3_reg_1438;

assign out_6_din = sum_3_reg_1438;

assign out_7_din = sum_3_reg_1438;

assign p_shl1_fu_958_p3 = {{kr_reg_417}, {2'd0}};

assign p_shl2_cast_fu_635_p3 = {{tmp_71_fu_631_p1}, {2'd0}};

assign p_shl_fu_1055_p3 = {{tmp_75_fu_1051_p1}, {2'd0}};

assign r_1_fu_562_p2 = (r_reg_370 + 7'd1);

assign start_out = real_start;

assign sum7_to_int_fu_972_p1 = sum7_reg_428;

assign sum_3_fu_1014_p3 = ((tmp_29_fu_1008_p2[0:0] === 1'b1) ? 32'd0 : sum7_reg_428);

assign tmp_10_fu_1108_p1 = ic_1_reg_463;

assign tmp_1_cast_fu_618_p1 = c_reg_381;

assign tmp_1_fu_608_p1 = c_reg_381;

assign tmp_24_fu_643_p2 = (p_shl2_cast_fu_635_p3 - tmp_37_cast_fu_627_p1);

assign tmp_25_fu_976_p4 = {{sum7_to_int_fu_972_p1[30:23]}};

assign tmp_26_fu_665_p2 = (tmp_24_reg_1365 + tmp_3_cast_fu_661_p1);

assign tmp_27_fu_1002_p2 = (notrhs_fu_996_p2 | notlhs_fu_990_p2);

assign tmp_29_fu_1008_p2 = (tmp_28_fu_496_p2 & tmp_27_fu_1002_p2);

assign tmp_30_fu_1117_p28 = (tmp_4_reg_1462 + tmp_10_fu_1108_p1);

assign tmp_36_cast_fu_576_p1 = tmp_fu_568_p3;

assign tmp_37_cast_fu_627_p1 = tmp_s_fu_622_p2;

assign tmp_3_cast_fu_661_p1 = ic_reg_393;

assign tmp_46_cast_fu_670_p1 = tmp_26_fu_665_p2;

assign tmp_4_fu_1063_p2 = (p_shl_fu_1055_p3 - tmp_9_fu_1047_p1);

assign tmp_5_fu_954_p1 = kr_reg_417;

assign tmp_6_fu_966_p2 = (p_shl1_fu_958_p3 - tmp_5_fu_954_p1);

assign tmp_70_fu_580_p4 = {{r_reg_370[6:1]}};

assign tmp_71_fu_631_p1 = tmp_s_fu_622_p2[12:0];

assign tmp_72_fu_837_p4 = {{c_reg_381[6:1]}};

assign tmp_73_fu_986_p1 = sum7_to_int_fu_972_p1[22:0];

assign tmp_74_fu_1022_p1 = oc_reg_405[2:0];

assign tmp_75_fu_1051_p1 = tmp_8_fu_1042_p2[2:0];

assign tmp_7_fu_1038_p1 = kc_reg_440;

assign tmp_8_fu_1042_p2 = (tmp_7_fu_1038_p1 + tmp_6_reg_1433);

assign tmp_9_fu_1047_p1 = tmp_8_fu_1042_p2;

assign tmp_fu_568_p3 = {{r_reg_370}, {6'd0}};

assign tmp_s_fu_622_p2 = (tmp_1_cast_fu_618_p1 + tmp_36_cast_reg_1347);

always @ (posedge ap_clk) begin
    tmp_36_cast_reg_1347[5:0] <= 6'b000000;
    tmp_36_cast_reg_1347[13] <= 1'b0;
end

endmodule //conv1
