// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        f4_address0,
        f4_ce0,
        f4_q0
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;
output  [11:0] f4_address0;
output   f4_ce0;
input  [31:0] f4_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ce0;
reg out_r_we0;
reg f4_ce0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] oc_2_fu_193_p2;
reg   [5:0] oc_2_reg_386;
wire    ap_CS_fsm_state2;
wire   [12:0] tmp_cast_fu_199_p1;
reg   [12:0] tmp_cast_reg_391;
wire   [0:0] exitcond5_fu_187_p2;
wire   [3:0] r_4_fu_209_p2;
reg   [3:0] r_4_reg_399;
wire    ap_CS_fsm_state3;
wire   [7:0] tmp_69_cast_fu_223_p1;
reg   [7:0] tmp_69_cast_reg_404;
wire   [0:0] exitcond4_fu_203_p2;
wire   [3:0] c_4_fu_233_p2;
reg   [3:0] c_4_reg_412;
wire    ap_CS_fsm_state4;
wire   [5:0] ic_2_fu_245_p2;
reg   [5:0] ic_2_reg_420;
wire    ap_CS_fsm_state5;
wire   [12:0] tmp_14_cast_fu_251_p1;
reg   [12:0] tmp_14_cast_reg_425;
wire   [0:0] exitcond2_fu_239_p2;
wire   [1:0] kr_1_fu_292_p2;
reg   [1:0] kr_1_reg_433;
wire    ap_CS_fsm_state6;
wire   [7:0] tmp_53_fu_328_p2;
reg   [7:0] tmp_53_reg_438;
wire   [0:0] exitcond1_fu_286_p2;
wire   [1:0] kc_1_fu_344_p2;
reg   [1:0] kc_1_reg_446;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond_fu_338_p2;
reg   [31:0] f4_load_reg_456;
wire    ap_CS_fsm_state8;
wire   [31:0] grp_fu_182_p2;
reg   [31:0] tmp_19_reg_461;
wire    ap_CS_fsm_state12;
wire   [31:0] grp_fu_177_p2;
wire    ap_CS_fsm_state17;
reg   [5:0] oc_reg_72;
reg   [3:0] r_reg_83;
wire   [0:0] exitcond3_fu_227_p2;
reg   [3:0] c_reg_95;
reg   [31:0] sum3_reg_107;
reg   [5:0] ic_reg_120;
reg   [31:0] sum_1_reg_131;
reg   [1:0] kr_reg_143;
reg   [31:0] sum_2_reg_154;
reg   [1:0] kc_reg_166;
wire   [63:0] tmp_73_cast_fu_277_p1;
wire   [63:0] tmp_80_cast_fu_378_p1;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state9;
wire   [6:0] tmp_s_fu_215_p3;
wire   [7:0] tmp_13_cast_fu_255_p1;
wire   [7:0] tmp_49_fu_259_p2;
wire   [12:0] tmp_72_cast_fu_264_p3;
wire   [12:0] tmp_50_fu_272_p2;
wire   [3:0] kr_cast2_fu_282_p1;
wire   [3:0] tmp_15_fu_298_p2;
wire   [6:0] tmp_51_fu_304_p3;
wire   [4:0] tmp_52_fu_316_p3;
wire   [7:0] p_shl1_cast_fu_324_p1;
wire   [7:0] p_shl_cast_fu_312_p1;
wire   [3:0] kc_cast1_fu_334_p1;
wire   [3:0] tmp_17_fu_350_p2;
wire   [7:0] tmp_18_cast_fu_356_p1;
wire   [7:0] tmp_54_fu_360_p2;
wire   [12:0] tmp_79_cast_fu_365_p3;
wire   [12:0] tmp_55_fu_373_p2;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
end

topp_fadd_32ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fadd_32ns_32bkb_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_2_reg_154),
    .din1(tmp_19_reg_461),
    .ce(1'b1),
    .dout(grp_fu_177_p2)
);

topp_fmul_32ns_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fmul_32ns_32cud_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(f4_load_reg_456),
    .din1(32'd0),
    .ce(1'b1),
    .dout(grp_fu_182_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_203_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        c_reg_95 <= 4'd0;
    end else if (((exitcond2_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        c_reg_95 <= c_4_reg_412;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_227_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ic_reg_120 <= 6'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond1_fu_286_p2 == 1'd1))) begin
        ic_reg_120 <= ic_2_reg_420;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        kc_reg_166 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        kc_reg_166 <= kc_1_reg_446;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_338_p2 == 1'd1))) begin
        kr_reg_143 <= kr_1_reg_433;
    end else if (((exitcond2_fu_239_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        kr_reg_143 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_203_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        oc_reg_72 <= oc_2_reg_386;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        oc_reg_72 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond3_fu_227_p2 == 1'd1))) begin
        r_reg_83 <= r_4_reg_399;
    end else if (((exitcond5_fu_187_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        r_reg_83 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_227_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sum3_reg_107 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (exitcond1_fu_286_p2 == 1'd1))) begin
        sum3_reg_107 <= sum_1_reg_131;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_338_p2 == 1'd1))) begin
        sum_1_reg_131 <= sum_2_reg_154;
    end else if (((exitcond2_fu_239_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        sum_1_reg_131 <= sum3_reg_107;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        sum_2_reg_154 <= sum_1_reg_131;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        sum_2_reg_154 <= grp_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_4_reg_412 <= c_4_fu_233_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        f4_load_reg_456 <= f4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ic_2_reg_420 <= ic_2_fu_245_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        kc_1_reg_446 <= kc_1_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kr_1_reg_433 <= kr_1_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        oc_2_reg_386 <= oc_2_fu_193_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        r_4_reg_399 <= r_4_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_239_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_14_cast_reg_425[5 : 0] <= tmp_14_cast_fu_251_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_19_reg_461 <= grp_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_286_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_53_reg_438[7 : 1] <= tmp_53_fu_328_p2[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_203_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_69_cast_reg_404[6 : 3] <= tmp_69_cast_fu_223_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5_fu_187_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_cast_reg_391[5 : 0] <= tmp_cast_fu_199_p1[5 : 0];
    end
end

always @ (*) begin
    if ((((exitcond5_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond5_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        f4_ce0 = 1'b1;
    end else begin
        f4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond5_fu_187_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond4_fu_203_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond3_fu_227_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond2_fu_239_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (exitcond1_fu_286_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_338_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign c_4_fu_233_p2 = (c_reg_95 + 4'd1);

assign exitcond1_fu_286_p2 = ((kr_reg_143 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond2_fu_239_p2 = ((ic_reg_120 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond3_fu_227_p2 = ((c_reg_95 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond4_fu_203_p2 = ((r_reg_83 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond5_fu_187_p2 = ((oc_reg_72 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond_fu_338_p2 = ((kc_reg_166 == 2'd3) ? 1'b1 : 1'b0);

assign f4_address0 = tmp_80_cast_fu_378_p1;

assign ic_2_fu_245_p2 = (ic_reg_120 + 6'd1);

assign kc_1_fu_344_p2 = (kc_reg_166 + 2'd1);

assign kc_cast1_fu_334_p1 = kc_reg_166;

assign kr_1_fu_292_p2 = (kr_reg_143 + 2'd1);

assign kr_cast2_fu_282_p1 = kr_reg_143;

assign oc_2_fu_193_p2 = (oc_reg_72 + 6'd1);

assign out_r_address0 = tmp_73_cast_fu_277_p1;

assign out_r_d0 = sum3_reg_107;

assign p_shl1_cast_fu_324_p1 = tmp_52_fu_316_p3;

assign p_shl_cast_fu_312_p1 = tmp_51_fu_304_p3;

assign r_4_fu_209_p2 = (r_reg_83 + 4'd1);

assign tmp_13_cast_fu_255_p1 = c_reg_95;

assign tmp_14_cast_fu_251_p1 = ic_reg_120;

assign tmp_15_fu_298_p2 = (kr_cast2_fu_282_p1 + r_reg_83);

assign tmp_17_fu_350_p2 = (c_reg_95 + kc_cast1_fu_334_p1);

assign tmp_18_cast_fu_356_p1 = tmp_17_fu_350_p2;

assign tmp_49_fu_259_p2 = (tmp_13_cast_fu_255_p1 + tmp_69_cast_reg_404);

assign tmp_50_fu_272_p2 = (tmp_cast_reg_391 + tmp_72_cast_fu_264_p3);

assign tmp_51_fu_304_p3 = {{tmp_15_fu_298_p2}, {3'd0}};

assign tmp_52_fu_316_p3 = {{tmp_15_fu_298_p2}, {1'd0}};

assign tmp_53_fu_328_p2 = (p_shl1_cast_fu_324_p1 + p_shl_cast_fu_312_p1);

assign tmp_54_fu_360_p2 = (tmp_18_cast_fu_356_p1 + tmp_53_reg_438);

assign tmp_55_fu_373_p2 = (tmp_14_cast_reg_425 + tmp_79_cast_fu_365_p3);

assign tmp_69_cast_fu_223_p1 = tmp_s_fu_215_p3;

assign tmp_72_cast_fu_264_p3 = {{tmp_49_fu_259_p2}, {5'd0}};

assign tmp_73_cast_fu_277_p1 = tmp_50_fu_272_p2;

assign tmp_79_cast_fu_365_p3 = {{tmp_54_fu_360_p2}, {5'd0}};

assign tmp_80_cast_fu_378_p1 = tmp_55_fu_373_p2;

assign tmp_cast_fu_199_p1 = oc_reg_72;

assign tmp_s_fu_215_p3 = {{r_reg_83}, {3'd0}};

always @ (posedge ap_clk) begin
    tmp_cast_reg_391[12:6] <= 7'b0000000;
    tmp_69_cast_reg_404[2:0] <= 3'b000;
    tmp_69_cast_reg_404[7] <= 1'b0;
    tmp_14_cast_reg_425[12:6] <= 7'b0000000;
    tmp_53_reg_438[0] <= 1'b0;
end

endmodule //conv5
