-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    out_r_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_full_n : IN STD_LOGIC;
    out_r_write : OUT STD_LOGIC;
    f3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    f3_empty_n : IN STD_LOGIC;
    f3_read : OUT STD_LOGIC );
end;


architecture behav of conv4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (25 downto 0) := "00000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (25 downto 0) := "00000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (25 downto 0) := "00000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (25 downto 0) := "00000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (25 downto 0) := "00000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (25 downto 0) := "00000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (25 downto 0) := "00001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (25 downto 0) := "00010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (25 downto 0) := "00100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (25 downto 0) := "01000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv58_1 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv58_2 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv58_4 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv58_3 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal linbu_7_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal linbu_7_0_ce0 : STD_LOGIC;
    signal linbu_7_0_we0 : STD_LOGIC;
    signal linbu_7_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linbu_7_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal linbu_7_1_ce0 : STD_LOGIC;
    signal linbu_7_1_we0 : STD_LOGIC;
    signal linbu_7_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal f3_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal win_buf_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_352 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal win_buf_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal reg_359 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_370_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_reg_701 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_706 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond6_i_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_398_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_714 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_23_cast_fu_412_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_23_cast_reg_719 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond5_i_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_fu_422_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ic_reg_727 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_25_fu_428_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_25_reg_732 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond4_i_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal win_buf_addr_reg_738 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_addr_11_reg_744 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_cond_i_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_750 : STD_LOGIC_VECTOR (0 downto 0);
    signal win_buf_addr_12_reg_754 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_addr_14_reg_760 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_addr_15_reg_765 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal win_buf_addr_17_reg_771 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_load_8_reg_777 : STD_LOGIC_VECTOR (31 downto 0);
    signal win_buf_load_9_reg_782 : STD_LOGIC_VECTOR (31 downto 0);
    signal linbu_7_0_addr_reg_787 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal linbu_7_1_addr_reg_792 : STD_LOGIC_VECTOR (8 downto 0);
    signal oc_fu_553_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal oc_reg_800 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal kr_fu_565_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kr_reg_808 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal tmp_34_fu_587_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_34_reg_813 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond2_i_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_reg_818 : STD_LOGIC_VECTOR (0 downto 0);
    signal kc_fu_599_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kc_reg_826 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal tmp_37_cast_fu_614_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_37_cast_reg_831 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond1_i_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_2_fu_628_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ic_2_reg_839 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal exitcond_i_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_341_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_56_i_reg_849 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_fu_336_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal win_buf_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_ce0 : STD_LOGIC;
    signal win_buf_we0 : STD_LOGIC;
    signal win_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal win_buf_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_ce1 : STD_LOGIC;
    signal win_buf_we1 : STD_LOGIC;
    signal win_buf_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_i_reg_221 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal c_i_reg_232 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond3_i_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_i_reg_244 : STD_LOGIC_VECTOR (5 downto 0);
    signal oc_i_reg_256 : STD_LOGIC_VECTOR (5 downto 0);
    signal kr_i_reg_267 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum4_i_reg_278 : STD_LOGIC_VECTOR (31 downto 0);
    signal kc_i_reg_290 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_1_i_reg_301 : STD_LOGIC_VECTOR (31 downto 0);
    signal ic_1_i_reg_313 : STD_LOGIC_VECTOR (5 downto 0);
    signal sum_2_i_reg_324 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_cast_fu_434_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_26_fu_439_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_27_fu_473_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_29_cast_fu_488_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_30_cast_fu_496_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_32_fu_501_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_48_i_fu_510_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_cast_fu_518_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_24_cast_fu_532_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_31_fu_538_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_38_cast_fu_643_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal tmp_54_fu_376_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_22_fu_404_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_55_fu_448_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp2_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_i_cast1_fu_469_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_fu_482_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_cast1_fu_493_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_cast1_fu_515_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_48_i_cast_fu_523_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_24_fu_527_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_33_fu_575_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_cast_fu_583_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_53_i_cast_fu_571_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_54_i_cast_fu_605_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_35_fu_609_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_55_i_cast_fu_634_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_38_fu_638_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sum4_i_to_int_fu_648_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_652_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_56_fu_662_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal notrhs_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_678_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (25 downto 0);

    component topp_fadd_32ns_32bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component topp_fmul_32ns_32cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component topp_fcmp_32ns_32dEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv4_linbu_7_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv4_win_buf IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    linbu_7_0_U : component conv4_linbu_7_0
    generic map (
        DataWidth => 32,
        AddressRange => 384,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linbu_7_0_address0,
        ce0 => linbu_7_0_ce0,
        we0 => linbu_7_0_we0,
        d0 => linbu_7_1_q0,
        q0 => linbu_7_0_q0);

    linbu_7_1_U : component conv4_linbu_7_0
    generic map (
        DataWidth => 32,
        AddressRange => 384,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linbu_7_1_address0,
        ce0 => linbu_7_1_ce0,
        we0 => linbu_7_1_we0,
        d0 => f3_dout,
        q0 => linbu_7_1_q0);

    win_buf_U : component conv4_win_buf
    generic map (
        DataWidth => 32,
        AddressRange => 288,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => win_buf_address0,
        ce0 => win_buf_ce0,
        we0 => win_buf_we0,
        d0 => win_buf_d0,
        q0 => win_buf_q0,
        address1 => win_buf_address1,
        ce1 => win_buf_ce1,
        we1 => win_buf_we1,
        d1 => win_buf_d1,
        q1 => win_buf_q1);

    topp_fadd_32ns_32bkb_U31 : component topp_fadd_32ns_32bkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum_2_i_reg_324,
        din1 => tmp_56_i_reg_849,
        ce => ap_const_logic_1,
        dout => grp_fu_336_p2);

    topp_fmul_32ns_32cud_U32 : component topp_fmul_32ns_32cud
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_352,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        dout => grp_fu_341_p2);

    topp_fcmp_32ns_32dEe_U33 : component topp_fcmp_32ns_32dEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        din0 => sum4_i_reg_278,
        din1 => ap_const_lv32_0,
        opcode => ap_const_lv5_4,
        dout => tmp_49_fu_346_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_364_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_i_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_364_p2 = ap_const_lv1_0))) then 
                c_i_reg_232 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and ((exitcond3_i_fu_547_p2 = ap_const_lv1_1) or (or_cond_i_reg_750 = ap_const_lv1_0)))) then 
                c_i_reg_232 <= c_reg_714;
            end if; 
        end if;
    end process;

    ic_1_i_reg_313_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_593_p2 = ap_const_lv1_0))) then 
                ic_1_i_reg_313 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                ic_1_i_reg_313 <= ic_2_reg_839;
            end if; 
        end if;
    end process;

    ic_i_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_392_p2 = ap_const_lv1_0))) then 
                ic_i_reg_244 <= ap_const_lv6_0;
            elsif (((f3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                ic_i_reg_244 <= ic_reg_727;
            end if; 
        end if;
    end process;

    kc_i_reg_290_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (exitcond_i_fu_622_p2 = ap_const_lv1_1))) then 
                kc_i_reg_290 <= kc_reg_826;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_559_p2 = ap_const_lv1_0))) then 
                kc_i_reg_290 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    kr_i_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (or_cond_i_reg_750 = ap_const_lv1_1) and (exitcond3_i_fu_547_p2 = ap_const_lv1_0))) then 
                kr_i_reg_267 <= ap_const_lv2_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_593_p2 = ap_const_lv1_1))) then 
                kr_i_reg_267 <= kr_reg_808;
            end if; 
        end if;
    end process;

    oc_i_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (or_cond_i_fu_464_p2 = ap_const_lv1_1) and (exitcond4_i_fu_416_p2 = ap_const_lv1_1))) then 
                oc_i_reg_256 <= ap_const_lv6_0;
            elsif (((out_r_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state26))) then 
                oc_i_reg_256 <= oc_reg_800;
            end if; 
        end if;
    end process;

    r_i_reg_221_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_392_p2 = ap_const_lv1_1))) then 
                r_i_reg_221 <= r_reg_701;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                r_i_reg_221 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    reg_352_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                reg_352 <= win_buf_q1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                reg_352 <= win_buf_q0;
            end if; 
        end if;
    end process;

    sum4_i_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (or_cond_i_reg_750 = ap_const_lv1_1) and (exitcond3_i_fu_547_p2 = ap_const_lv1_0))) then 
                sum4_i_reg_278 <= ap_const_lv32_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_593_p2 = ap_const_lv1_1))) then 
                sum4_i_reg_278 <= sum_1_i_reg_301;
            end if; 
        end if;
    end process;

    sum_1_i_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (exitcond_i_fu_622_p2 = ap_const_lv1_1))) then 
                sum_1_i_reg_301 <= sum_2_i_reg_324;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_559_p2 = ap_const_lv1_0))) then 
                sum_1_i_reg_301 <= sum4_i_reg_278;
            end if; 
        end if;
    end process;

    sum_2_i_reg_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_593_p2 = ap_const_lv1_0))) then 
                sum_2_i_reg_324 <= sum_1_i_reg_301;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                sum_2_i_reg_324 <= grp_fu_336_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                c_reg_714 <= c_fu_398_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                ic_2_reg_839 <= ic_2_fu_628_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                ic_reg_727 <= ic_fu_422_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_364_p2 = ap_const_lv1_0))) then
                icmp_reg_706 <= icmp_fu_386_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                kc_reg_826 <= kc_fu_599_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                kr_reg_808 <= kr_fu_565_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                linbu_7_0_addr_reg_787 <= tmp_24_cast_fu_532_p1(9 - 1 downto 0);
                linbu_7_1_addr_reg_792 <= tmp_24_cast_fu_532_p1(9 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (or_cond_i_reg_750 = ap_const_lv1_1))) then
                oc_reg_800 <= oc_fu_553_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond4_i_fu_416_p2 = ap_const_lv1_1))) then
                or_cond_i_reg_750 <= or_cond_i_fu_464_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                r_reg_701 <= r_fu_370_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_359 <= win_buf_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_392_p2 = ap_const_lv1_0))) then
                    tmp_23_cast_reg_719(8 downto 5) <= tmp_23_cast_fu_412_p1(8 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond4_i_fu_416_p2 = ap_const_lv1_0))) then
                tmp_25_reg_732 <= tmp_25_fu_428_p2;
                    win_buf_addr_11_reg_744(5 downto 0) <= tmp_26_fu_439_p3(9 - 1 downto 0)(5 downto 0);
                    win_buf_addr_reg_738(5 downto 0) <= tmp_25_cast_fu_434_p1(9 - 1 downto 0)(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_559_p2 = ap_const_lv1_0))) then
                tmp_34_reg_813 <= tmp_34_fu_587_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_593_p2 = ap_const_lv1_0))) then
                    tmp_37_cast_reg_831(9 downto 5) <= tmp_37_cast_fu_614_p3(9 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_559_p2 = ap_const_lv1_1))) then
                tmp_49_reg_818 <= tmp_49_fu_346_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                tmp_56_i_reg_849 <= grp_fu_341_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    win_buf_addr_12_reg_754(5 downto 0) <= tmp_27_fu_473_p3(9 - 1 downto 0)(5 downto 0);
                    win_buf_addr_14_reg_760(7 downto 0) <= tmp_29_cast_fu_488_p1(9 - 1 downto 0)(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                    win_buf_addr_15_reg_765(7 downto 0) <= tmp_30_cast_fu_496_p1(9 - 1 downto 0)(7 downto 0);
                    win_buf_addr_17_reg_771(5 downto 0) <= tmp_32_fu_501_p3(9 - 1 downto 0)(5 downto 0);
                win_buf_load_8_reg_777 <= win_buf_q0;
                win_buf_load_9_reg_782 <= win_buf_q1;
            end if;
        end if;
    end process;
    tmp_23_cast_reg_719(4 downto 0) <= "00000";
    tmp_23_cast_reg_719(9) <= '0';
    win_buf_addr_reg_738(8 downto 6) <= "000";
    win_buf_addr_11_reg_744(8 downto 6) <= "001";
    win_buf_addr_12_reg_754(8 downto 6) <= "010";
    win_buf_addr_14_reg_760(8) <= '0';
    win_buf_addr_15_reg_765(8) <= '0';
    win_buf_addr_17_reg_771(8 downto 6) <= "100";
    tmp_37_cast_reg_831(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, out_r_full_n, f3_empty_n, ap_CS_fsm_state26, ap_CS_fsm_state11, ap_CS_fsm_state2, exitcond6_i_fu_364_p2, ap_CS_fsm_state3, exitcond5_i_fu_392_p2, ap_CS_fsm_state4, exitcond4_i_fu_416_p2, or_cond_i_reg_750, ap_CS_fsm_state12, ap_CS_fsm_state13, exitcond2_i_fu_559_p2, ap_CS_fsm_state14, exitcond1_i_fu_593_p2, ap_CS_fsm_state15, exitcond_i_fu_622_p2, exitcond3_i_fu_547_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_364_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_392_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond4_i_fu_416_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((f3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and ((exitcond3_i_fu_547_p2 = ap_const_lv1_1) or (or_cond_i_reg_750 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_559_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state26;
                end if;
            when ap_ST_fsm_state14 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_593_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (exitcond_i_fu_622_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state26 => 
                if (((out_r_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state26))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state26;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, exitcond6_i_fu_364_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_364_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    c_fu_398_p2 <= std_logic_vector(unsigned(c_i_reg_232) + unsigned(ap_const_lv4_1));
    exitcond1_i_fu_593_p2 <= "1" when (kc_i_reg_290 = ap_const_lv2_3) else "0";
    exitcond2_i_fu_559_p2 <= "1" when (kr_i_reg_267 = ap_const_lv2_3) else "0";
    exitcond3_i_fu_547_p2 <= "1" when (oc_i_reg_256 = ap_const_lv6_20) else "0";
    exitcond4_i_fu_416_p2 <= "1" when (ic_i_reg_244 = ap_const_lv6_20) else "0";
    exitcond5_i_fu_392_p2 <= "1" when (c_i_reg_232 = ap_const_lv4_C) else "0";
    exitcond6_i_fu_364_p2 <= "1" when (r_i_reg_221 = ap_const_lv4_C) else "0";
    exitcond_i_fu_622_p2 <= "1" when (ic_1_i_reg_313 = ap_const_lv6_20) else "0";

    f3_blk_n_assign_proc : process(f3_empty_n, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            f3_blk_n <= f3_empty_n;
        else 
            f3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    f3_read_assign_proc : process(f3_empty_n, ap_CS_fsm_state11)
    begin
        if (((f3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            f3_read <= ap_const_logic_1;
        else 
            f3_read <= ap_const_logic_0;
        end if; 
    end process;

    ic_2_fu_628_p2 <= std_logic_vector(unsigned(ic_1_i_reg_313) + unsigned(ap_const_lv6_1));
    ic_fu_422_p2 <= std_logic_vector(unsigned(ic_i_reg_244) + unsigned(ap_const_lv6_1));
    icmp2_fu_458_p2 <= "0" when (tmp_55_fu_448_p4 = ap_const_lv3_0) else "1";
    icmp_fu_386_p2 <= "0" when (tmp_54_fu_376_p4 = ap_const_lv3_0) else "1";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond6_i_fu_364_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_364_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    kc_fu_599_p2 <= std_logic_vector(unsigned(kc_i_reg_290) + unsigned(ap_const_lv2_1));
    kr_fu_565_p2 <= std_logic_vector(unsigned(kr_i_reg_267) + unsigned(ap_const_lv2_1));

    linbu_7_0_address0_assign_proc : process(linbu_7_0_addr_reg_787, ap_CS_fsm_state9, tmp_24_cast_fu_532_p1, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            linbu_7_0_address0 <= linbu_7_0_addr_reg_787;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linbu_7_0_address0 <= tmp_24_cast_fu_532_p1(9 - 1 downto 0);
        else 
            linbu_7_0_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    linbu_7_0_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            linbu_7_0_ce0 <= ap_const_logic_1;
        else 
            linbu_7_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_7_0_we0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            linbu_7_0_we0 <= ap_const_logic_1;
        else 
            linbu_7_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_7_1_address0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state9, linbu_7_1_addr_reg_792, tmp_24_cast_fu_532_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            linbu_7_1_address0 <= linbu_7_1_addr_reg_792;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linbu_7_1_address0 <= tmp_24_cast_fu_532_p1(9 - 1 downto 0);
        else 
            linbu_7_1_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    linbu_7_1_ce0_assign_proc : process(f3_empty_n, ap_CS_fsm_state11, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((f3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            linbu_7_1_ce0 <= ap_const_logic_1;
        else 
            linbu_7_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_7_1_we0_assign_proc : process(f3_empty_n, ap_CS_fsm_state11)
    begin
        if (((f3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            linbu_7_1_we0 <= ap_const_logic_1;
        else 
            linbu_7_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    notlhs_fu_666_p2 <= "0" when (tmp_fu_652_p4 = ap_const_lv8_FF) else "1";
    notrhs_fu_672_p2 <= "1" when (tmp_56_fu_662_p1 = ap_const_lv23_0) else "0";
    oc_fu_553_p2 <= std_logic_vector(unsigned(oc_i_reg_256) + unsigned(ap_const_lv6_1));
    or_cond_i_fu_464_p2 <= (icmp_reg_706 and icmp2_fu_458_p2);

    out_r_blk_n_assign_proc : process(out_r_full_n, ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            out_r_blk_n <= out_r_full_n;
        else 
            out_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_din <= 
        ap_const_lv32_0 when (tmp_50_fu_684_p2(0) = '1') else 
        sum4_i_reg_278;

    out_r_write_assign_proc : process(out_r_full_n, ap_CS_fsm_state26)
    begin
        if (((out_r_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state26))) then 
            out_r_write <= ap_const_logic_1;
        else 
            out_r_write <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_cast_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_575_p3),5));
    r_fu_370_p2 <= std_logic_vector(unsigned(r_i_reg_221) + unsigned(ap_const_lv4_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sum4_i_to_int_fu_648_p1 <= sum4_i_reg_278;
    tmp_22_fu_404_p3 <= (c_i_reg_232 & ap_const_lv5_0);
    tmp_23_cast_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_404_p3),10));
    tmp_24_cast_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_527_p2),64));
    tmp_24_fu_527_p2 <= std_logic_vector(unsigned(tmp_23_cast_reg_719) + unsigned(tmp_48_i_cast_fu_523_p1));
    tmp_25_cast_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_428_p2),64));
    tmp_25_fu_428_p2 <= (ic_i_reg_244 xor ap_const_lv6_20);
    tmp_26_fu_439_p3 <= (ap_const_lv58_1 & ic_i_reg_244);
    tmp_27_fu_473_p3 <= (ap_const_lv58_2 & ic_i_reg_244);
        tmp_28_cast1_fu_515_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_25_reg_732),7));

    tmp_28_cast_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_28_cast1_fu_515_p1),64));
    tmp_29_cast_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_29_fu_482_p2),64));
    tmp_29_fu_482_p2 <= std_logic_vector(unsigned(tmp_48_i_cast1_fu_469_p1) + unsigned(ap_const_lv8_A0));
        tmp_30_cast1_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_25_reg_732),8));

    tmp_30_cast_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_30_cast1_fu_493_p1),64));
    tmp_31_fu_538_p3 <= (ap_const_lv58_3 & ic_i_reg_244);
    tmp_32_fu_501_p3 <= (ap_const_lv58_4 & ic_i_reg_244);
    tmp_33_fu_575_p3 <= (kr_i_reg_267 & ap_const_lv2_0);
    tmp_34_fu_587_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_583_p1) - unsigned(tmp_53_i_cast_fu_571_p1));
    tmp_35_fu_609_p2 <= std_logic_vector(unsigned(tmp_54_i_cast_fu_605_p1) + unsigned(tmp_34_reg_813));
    tmp_37_cast_fu_614_p3 <= (tmp_35_fu_609_p2 & ap_const_lv5_0);
    tmp_38_cast_fu_643_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_fu_638_p2),64));
    tmp_38_fu_638_p2 <= std_logic_vector(unsigned(tmp_37_cast_reg_831) + unsigned(tmp_55_i_cast_fu_634_p1));
    tmp_48_i_cast1_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_244),8));
    tmp_48_i_cast_fu_523_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_244),10));
    tmp_48_i_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_244),64));
    tmp_50_fu_684_p2 <= (tmp_s_fu_678_p2 and tmp_49_reg_818);
    tmp_53_i_cast_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kr_i_reg_267),5));
    tmp_54_fu_376_p4 <= r_i_reg_221(3 downto 1);
    tmp_54_i_cast_fu_605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kc_i_reg_290),5));
    tmp_55_fu_448_p4 <= c_i_reg_232(3 downto 1);
    tmp_55_i_cast_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_1_i_reg_313),10));
    tmp_56_fu_662_p1 <= sum4_i_to_int_fu_648_p1(23 - 1 downto 0);
    tmp_fu_652_p4 <= sum4_i_to_int_fu_648_p1(30 downto 23);
    tmp_s_fu_678_p2 <= (notrhs_fu_672_p2 or notlhs_fu_666_p2);

    win_buf_address0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, win_buf_addr_11_reg_744, ap_CS_fsm_state6, win_buf_addr_17_reg_771, ap_CS_fsm_state9, tmp_25_cast_fu_434_p1, tmp_27_fu_473_p3, tmp_30_cast_fu_496_p1, tmp_48_i_fu_510_p1, tmp_28_cast_fu_518_p1, ap_CS_fsm_state8, tmp_31_fu_538_p3, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            win_buf_address0 <= win_buf_addr_17_reg_771;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_address0 <= win_buf_addr_11_reg_744;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            win_buf_address0 <= tmp_31_fu_538_p3(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_address0 <= tmp_28_cast_fu_518_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            win_buf_address0 <= tmp_48_i_fu_510_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            win_buf_address0 <= tmp_30_cast_fu_496_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            win_buf_address0 <= tmp_27_fu_473_p3(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            win_buf_address0 <= tmp_25_cast_fu_434_p1(9 - 1 downto 0);
        else 
            win_buf_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    win_buf_address1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, win_buf_addr_reg_738, win_buf_addr_12_reg_754, win_buf_addr_14_reg_760, win_buf_addr_15_reg_765, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state15, tmp_26_fu_439_p3, tmp_29_cast_fu_488_p1, tmp_32_fu_501_p3, ap_CS_fsm_state8, tmp_38_cast_fu_643_p1, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            win_buf_address1 <= tmp_38_cast_fu_643_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_address1 <= win_buf_addr_14_reg_760;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            win_buf_address1 <= win_buf_addr_15_reg_765;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_address1 <= win_buf_addr_12_reg_754;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            win_buf_address1 <= win_buf_addr_reg_738;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            win_buf_address1 <= tmp_32_fu_501_p3(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            win_buf_address1 <= tmp_29_cast_fu_488_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            win_buf_address1 <= tmp_26_fu_439_p3(9 - 1 downto 0);
        else 
            win_buf_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    win_buf_ce0_assign_proc : process(f3_empty_n, ap_CS_fsm_state11, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((f3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            win_buf_ce0 <= ap_const_logic_1;
        else 
            win_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_ce1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state15, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            win_buf_ce1 <= ap_const_logic_1;
        else 
            win_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_d0_assign_proc : process(f3_dout, linbu_7_0_q0, ap_CS_fsm_state11, reg_352, ap_CS_fsm_state7, win_buf_load_8_reg_777, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            win_buf_d0 <= f3_dout;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_d0 <= linbu_7_0_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_d0 <= win_buf_load_8_reg_777;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            win_buf_d0 <= reg_352;
        else 
            win_buf_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    win_buf_d1_assign_proc : process(linbu_7_1_q0, ap_CS_fsm_state7, reg_359, win_buf_load_9_reg_782, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_d1 <= linbu_7_1_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_d1 <= win_buf_load_9_reg_782;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            win_buf_d1 <= reg_359;
        else 
            win_buf_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    win_buf_we0_assign_proc : process(f3_empty_n, ap_CS_fsm_state11, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((f3_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            win_buf_we0 <= ap_const_logic_1;
        else 
            win_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_we1_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            win_buf_we1 <= ap_const_logic_1;
        else 
            win_buf_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
