-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    out_r_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_full_n : IN STD_LOGIC;
    out_r_write : OUT STD_LOGIC;
    f4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    f4_empty_n : IN STD_LOGIC;
    f4_read : OUT STD_LOGIC );
end;


architecture behav of conv5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv58_1 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv58_2 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv58_4 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv58_3 : STD_LOGIC_VECTOR (57 downto 0) := "0000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal linbu_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal linbu_0_ce0 : STD_LOGIC;
    signal linbu_0_we0 : STD_LOGIC;
    signal linbu_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linbu_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal linbu_1_ce0 : STD_LOGIC;
    signal linbu_1_we0 : STD_LOGIC;
    signal linbu_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal exitcond2_i_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal f4_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal win_buf_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_337 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal win_buf_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal reg_344 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_355_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_reg_636 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_641 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond6_i_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_383_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_reg_649 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_6_cast_fu_397_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_6_cast_reg_654 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond5_i_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_fu_407_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ic_reg_662 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_8_fu_413_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_reg_667 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond4_i_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal win_buf_addr_reg_673 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_addr_2_reg_679 : STD_LOGIC_VECTOR (8 downto 0);
    signal or_cond_i_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_685 : STD_LOGIC_VECTOR (0 downto 0);
    signal win_buf_addr_3_reg_689 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_addr_5_reg_695 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_addr_6_reg_700 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal win_buf_addr_8_reg_706 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_load_2_reg_712 : STD_LOGIC_VECTOR (31 downto 0);
    signal win_buf_load_3_reg_717 : STD_LOGIC_VECTOR (31 downto 0);
    signal linbu_0_addr_reg_722 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal linbu_1_addr_reg_727 : STD_LOGIC_VECTOR (8 downto 0);
    signal oc_fu_538_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal oc_reg_735 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal kr_fu_550_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kr_reg_743 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state13 : BOOLEAN;
    signal tmp_17_fu_572_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_17_reg_748 : STD_LOGIC_VECTOR (4 downto 0);
    signal kc_fu_584_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kc_reg_756 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal tmp_20_cast_fu_599_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_20_cast_reg_761 : STD_LOGIC_VECTOR (9 downto 0);
    signal exitcond1_i_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_1_fu_613_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ic_1_reg_769 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal exitcond_i_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_332_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_43_i_reg_779 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_fu_327_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal win_buf_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_ce0 : STD_LOGIC;
    signal win_buf_we0 : STD_LOGIC;
    signal win_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal win_buf_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal win_buf_ce1 : STD_LOGIC;
    signal win_buf_we1 : STD_LOGIC;
    signal win_buf_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_i_reg_211 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal c_i_reg_222 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond3_i_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_i_reg_234 : STD_LOGIC_VECTOR (5 downto 0);
    signal oc_i_reg_246 : STD_LOGIC_VECTOR (5 downto 0);
    signal kr_i_reg_257 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum1_i_reg_268 : STD_LOGIC_VECTOR (31 downto 0);
    signal kc_i_reg_281 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_1_i_reg_292 : STD_LOGIC_VECTOR (31 downto 0);
    signal ic_1_i_reg_304 : STD_LOGIC_VECTOR (5 downto 0);
    signal sum_2_i_reg_315 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_cast_fu_419_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_fu_424_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_10_fu_458_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_12_cast_fu_473_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_13_cast_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_15_fu_486_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_36_i_fu_495_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_cast_fu_503_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_7_cast_fu_517_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_14_fu_523_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_21_cast_fu_628_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal tmp_52_fu_361_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_389_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_53_fu_433_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp1_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_i_cast1_fu_454_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_467_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_cast1_fu_478_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_cast1_fu_500_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_36_i_cast_fu_508_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_512_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_16_fu_560_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_cast_fu_568_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_40_i_cast_fu_556_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_41_i_cast_fu_590_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_18_fu_594_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_42_i_cast_fu_619_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_21_fu_623_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);

    component topp_fadd_32ns_32bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component topp_fmul_32ns_32cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv5_linbu_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv4_win_buf IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    linbu_0_U : component conv5_linbu_0
    generic map (
        DataWidth => 32,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linbu_0_address0,
        ce0 => linbu_0_ce0,
        we0 => linbu_0_we0,
        d0 => linbu_1_q0,
        q0 => linbu_0_q0);

    linbu_1_U : component conv5_linbu_0
    generic map (
        DataWidth => 32,
        AddressRange => 320,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linbu_1_address0,
        ce0 => linbu_1_ce0,
        we0 => linbu_1_we0,
        d0 => f4_dout,
        q0 => linbu_1_q0);

    win_buf_U : component conv4_win_buf
    generic map (
        DataWidth => 32,
        AddressRange => 288,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => win_buf_address0,
        ce0 => win_buf_ce0,
        we0 => win_buf_we0,
        d0 => win_buf_d0,
        q0 => win_buf_q0,
        address1 => win_buf_address1,
        ce1 => win_buf_ce1,
        we1 => win_buf_we1,
        d1 => win_buf_d1,
        q1 => win_buf_q1);

    topp_fadd_32ns_32bkb_U38 : component topp_fadd_32ns_32bkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum_2_i_reg_315,
        din1 => tmp_43_i_reg_779,
        ce => ap_const_logic_1,
        dout => grp_fu_327_p2);

    topp_fmul_32ns_32cud_U39 : component topp_fmul_32ns_32cud
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_337,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        dout => grp_fu_332_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((exitcond6_i_fu_349_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_i_reg_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_349_p2 = ap_const_lv1_0))) then 
                c_i_reg_222 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and ((exitcond3_i_fu_532_p2 = ap_const_lv1_1) or (or_cond_i_reg_685 = ap_const_lv1_0)))) then 
                c_i_reg_222 <= c_reg_649;
            end if; 
        end if;
    end process;

    ic_1_i_reg_304_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_578_p2 = ap_const_lv1_0))) then 
                ic_1_i_reg_304 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                ic_1_i_reg_304 <= ic_1_reg_769;
            end if; 
        end if;
    end process;

    ic_i_reg_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_377_p2 = ap_const_lv1_0))) then 
                ic_i_reg_234 <= ap_const_lv6_0;
            elsif (((f4_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                ic_i_reg_234 <= ic_reg_662;
            end if; 
        end if;
    end process;

    kc_i_reg_281_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_i_fu_607_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then 
                kc_i_reg_281 <= kc_reg_756;
            elsif ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (exitcond2_i_fu_544_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                kc_i_reg_281 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    kr_i_reg_257_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_reg_685 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12) and (exitcond3_i_fu_532_p2 = ap_const_lv1_0))) then 
                kr_i_reg_257 <= ap_const_lv2_0;
            elsif (((exitcond1_i_fu_578_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                kr_i_reg_257 <= kr_reg_743;
            end if; 
        end if;
    end process;

    oc_i_reg_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_fu_449_p2 = ap_const_lv1_1) and (exitcond4_i_fu_401_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                oc_i_reg_246 <= ap_const_lv6_0;
            elsif ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                oc_i_reg_246 <= oc_reg_735;
            end if; 
        end if;
    end process;

    r_i_reg_211_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond5_i_fu_377_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                r_i_reg_211 <= r_reg_636;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                r_i_reg_211 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    reg_337_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                reg_337 <= win_buf_q1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                reg_337 <= win_buf_q0;
            end if; 
        end if;
    end process;

    sum1_i_reg_268_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_reg_685 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12) and (exitcond3_i_fu_532_p2 = ap_const_lv1_0))) then 
                sum1_i_reg_268 <= ap_const_lv32_0;
            elsif (((exitcond1_i_fu_578_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                sum1_i_reg_268 <= sum_1_i_reg_292;
            end if; 
        end if;
    end process;

    sum_1_i_reg_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_i_fu_607_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then 
                sum_1_i_reg_292 <= sum_2_i_reg_315;
            elsif ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (exitcond2_i_fu_544_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                sum_1_i_reg_292 <= sum1_i_reg_268;
            end if; 
        end if;
    end process;

    sum_2_i_reg_315_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_578_p2 = ap_const_lv1_0))) then 
                sum_2_i_reg_315 <= sum_1_i_reg_292;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                sum_2_i_reg_315 <= grp_fu_327_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                c_reg_649 <= c_fu_383_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                ic_1_reg_769 <= ic_1_fu_613_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                ic_reg_662 <= ic_fu_407_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_349_p2 = ap_const_lv1_0))) then
                icmp_reg_641 <= icmp_fu_371_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                kc_reg_756 <= kc_fu_584_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                kr_reg_743 <= kr_fu_550_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                linbu_0_addr_reg_722 <= tmp_7_cast_fu_517_p1(9 - 1 downto 0);
                linbu_1_addr_reg_727 <= tmp_7_cast_fu_517_p1(9 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_reg_685 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                oc_reg_735 <= oc_fu_538_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond4_i_fu_401_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                or_cond_i_reg_685 <= or_cond_i_fu_449_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                r_reg_636 <= r_fu_355_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_344 <= win_buf_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (exitcond2_i_fu_544_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                tmp_17_reg_748 <= tmp_17_fu_572_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_578_p2 = ap_const_lv1_0))) then
                    tmp_20_cast_reg_761(9 downto 5) <= tmp_20_cast_fu_599_p3(9 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                tmp_43_i_reg_779 <= grp_fu_332_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_377_p2 = ap_const_lv1_0))) then
                    tmp_6_cast_reg_654(8 downto 5) <= tmp_6_cast_fu_397_p1(8 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond4_i_fu_401_p2 = ap_const_lv1_0))) then
                tmp_8_reg_667 <= tmp_8_fu_413_p2;
                    win_buf_addr_2_reg_679(5 downto 0) <= tmp_9_fu_424_p3(9 - 1 downto 0)(5 downto 0);
                    win_buf_addr_reg_673(5 downto 0) <= tmp_8_cast_fu_419_p1(9 - 1 downto 0)(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    win_buf_addr_3_reg_689(5 downto 0) <= tmp_10_fu_458_p3(9 - 1 downto 0)(5 downto 0);
                    win_buf_addr_5_reg_695(7 downto 0) <= tmp_12_cast_fu_473_p1(9 - 1 downto 0)(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                    win_buf_addr_6_reg_700(7 downto 0) <= tmp_13_cast_fu_481_p1(9 - 1 downto 0)(7 downto 0);
                    win_buf_addr_8_reg_706(5 downto 0) <= tmp_15_fu_486_p3(9 - 1 downto 0)(5 downto 0);
                win_buf_load_2_reg_712 <= win_buf_q0;
                win_buf_load_3_reg_717 <= win_buf_q1;
            end if;
        end if;
    end process;
    tmp_6_cast_reg_654(4 downto 0) <= "00000";
    tmp_6_cast_reg_654(9) <= '0';
    win_buf_addr_reg_673(8 downto 6) <= "000";
    win_buf_addr_2_reg_679(8 downto 6) <= "001";
    win_buf_addr_3_reg_689(8 downto 6) <= "010";
    win_buf_addr_5_reg_695(8) <= '0';
    win_buf_addr_6_reg_700(8) <= '0';
    win_buf_addr_8_reg_706(8 downto 6) <= "100";
    tmp_20_cast_reg_761(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, out_r_full_n, f4_empty_n, ap_CS_fsm_state13, exitcond2_i_fu_544_p2, ap_CS_fsm_state11, ap_CS_fsm_state2, exitcond6_i_fu_349_p2, ap_CS_fsm_state3, exitcond5_i_fu_377_p2, ap_CS_fsm_state4, exitcond4_i_fu_401_p2, or_cond_i_reg_685, ap_CS_fsm_state12, ap_CS_fsm_state14, exitcond1_i_fu_578_p2, ap_CS_fsm_state15, exitcond_i_fu_607_p2, exitcond3_i_fu_532_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond6_i_fu_349_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((exitcond5_i_fu_377_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((exitcond4_i_fu_401_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((f4_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and ((exitcond3_i_fu_532_p2 = ap_const_lv1_1) or (or_cond_i_reg_685 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                if ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                elsif ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (exitcond2_i_fu_544_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state14 => 
                if (((exitcond1_i_fu_578_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state15 => 
                if (((exitcond_i_fu_607_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state13_assign_proc : process(out_r_full_n, exitcond2_i_fu_544_p2)
    begin
                ap_block_state13 <= ((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, exitcond6_i_fu_349_p2)
    begin
        if (((exitcond6_i_fu_349_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    c_fu_383_p2 <= std_logic_vector(unsigned(c_i_reg_222) + unsigned(ap_const_lv4_1));
    exitcond1_i_fu_578_p2 <= "1" when (kc_i_reg_281 = ap_const_lv2_3) else "0";
    exitcond2_i_fu_544_p2 <= "1" when (kr_i_reg_257 = ap_const_lv2_3) else "0";
    exitcond3_i_fu_532_p2 <= "1" when (oc_i_reg_246 = ap_const_lv6_20) else "0";
    exitcond4_i_fu_401_p2 <= "1" when (ic_i_reg_234 = ap_const_lv6_20) else "0";
    exitcond5_i_fu_377_p2 <= "1" when (c_i_reg_222 = ap_const_lv4_A) else "0";
    exitcond6_i_fu_349_p2 <= "1" when (r_i_reg_211 = ap_const_lv4_A) else "0";
    exitcond_i_fu_607_p2 <= "1" when (ic_1_i_reg_304 = ap_const_lv6_20) else "0";

    f4_blk_n_assign_proc : process(f4_empty_n, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            f4_blk_n <= f4_empty_n;
        else 
            f4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    f4_read_assign_proc : process(f4_empty_n, ap_CS_fsm_state11)
    begin
        if (((f4_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            f4_read <= ap_const_logic_1;
        else 
            f4_read <= ap_const_logic_0;
        end if; 
    end process;

    ic_1_fu_613_p2 <= std_logic_vector(unsigned(ic_1_i_reg_304) + unsigned(ap_const_lv6_1));
    ic_fu_407_p2 <= std_logic_vector(unsigned(ic_i_reg_234) + unsigned(ap_const_lv6_1));
    icmp1_fu_443_p2 <= "0" when (tmp_53_fu_433_p4 = ap_const_lv3_0) else "1";
    icmp_fu_371_p2 <= "0" when (tmp_52_fu_361_p4 = ap_const_lv3_0) else "1";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond6_i_fu_349_p2)
    begin
        if (((exitcond6_i_fu_349_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    kc_fu_584_p2 <= std_logic_vector(unsigned(kc_i_reg_281) + unsigned(ap_const_lv2_1));
    kr_fu_550_p2 <= std_logic_vector(unsigned(kr_i_reg_257) + unsigned(ap_const_lv2_1));

    linbu_0_address0_assign_proc : process(linbu_0_addr_reg_722, ap_CS_fsm_state9, tmp_7_cast_fu_517_p1, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            linbu_0_address0 <= linbu_0_addr_reg_722;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linbu_0_address0 <= tmp_7_cast_fu_517_p1(9 - 1 downto 0);
        else 
            linbu_0_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    linbu_0_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            linbu_0_ce0 <= ap_const_logic_1;
        else 
            linbu_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_0_we0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            linbu_0_we0 <= ap_const_logic_1;
        else 
            linbu_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_1_address0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state9, linbu_1_addr_reg_727, tmp_7_cast_fu_517_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            linbu_1_address0 <= linbu_1_addr_reg_727;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linbu_1_address0 <= tmp_7_cast_fu_517_p1(9 - 1 downto 0);
        else 
            linbu_1_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    linbu_1_ce0_assign_proc : process(f4_empty_n, ap_CS_fsm_state11, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((f4_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            linbu_1_ce0 <= ap_const_logic_1;
        else 
            linbu_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_1_we0_assign_proc : process(f4_empty_n, ap_CS_fsm_state11)
    begin
        if (((f4_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            linbu_1_we0 <= ap_const_logic_1;
        else 
            linbu_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    oc_fu_538_p2 <= std_logic_vector(unsigned(oc_i_reg_246) + unsigned(ap_const_lv6_1));
    or_cond_i_fu_449_p2 <= (icmp_reg_641 and icmp1_fu_443_p2);

    out_r_blk_n_assign_proc : process(out_r_full_n, ap_CS_fsm_state13, exitcond2_i_fu_544_p2)
    begin
        if (((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            out_r_blk_n <= out_r_full_n;
        else 
            out_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_r_din <= sum1_i_reg_268;

    out_r_write_assign_proc : process(out_r_full_n, ap_CS_fsm_state13, exitcond2_i_fu_544_p2)
    begin
        if ((not(((exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (out_r_full_n = ap_const_logic_0))) and (exitcond2_i_fu_544_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            out_r_write <= ap_const_logic_1;
        else 
            out_r_write <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_cast_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_560_p3),5));
    r_fu_355_p2 <= std_logic_vector(unsigned(r_i_reg_211) + unsigned(ap_const_lv4_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_458_p3 <= (ap_const_lv58_2 & ic_i_reg_234);
        tmp_11_cast1_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_reg_667),7));

    tmp_11_cast_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_cast1_fu_500_p1),64));
    tmp_12_cast_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_467_p2),64));
    tmp_12_fu_467_p2 <= std_logic_vector(unsigned(tmp_36_i_cast1_fu_454_p1) + unsigned(ap_const_lv8_A0));
        tmp_13_cast1_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_reg_667),8));

    tmp_13_cast_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_cast1_fu_478_p1),64));
    tmp_14_fu_523_p3 <= (ap_const_lv58_3 & ic_i_reg_234);
    tmp_15_fu_486_p3 <= (ap_const_lv58_4 & ic_i_reg_234);
    tmp_16_fu_560_p3 <= (kr_i_reg_257 & ap_const_lv2_0);
    tmp_17_fu_572_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_568_p1) - unsigned(tmp_40_i_cast_fu_556_p1));
    tmp_18_fu_594_p2 <= std_logic_vector(unsigned(tmp_41_i_cast_fu_590_p1) + unsigned(tmp_17_reg_748));
    tmp_20_cast_fu_599_p3 <= (tmp_18_fu_594_p2 & ap_const_lv5_0);
    tmp_21_cast_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_623_p2),64));
    tmp_21_fu_623_p2 <= std_logic_vector(unsigned(tmp_20_cast_reg_761) + unsigned(tmp_42_i_cast_fu_619_p1));
    tmp_36_i_cast1_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_234),8));
    tmp_36_i_cast_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_234),10));
    tmp_36_i_fu_495_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_234),64));
    tmp_40_i_cast_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kr_i_reg_257),5));
    tmp_41_i_cast_fu_590_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kc_i_reg_281),5));
    tmp_42_i_cast_fu_619_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_1_i_reg_304),10));
    tmp_52_fu_361_p4 <= r_i_reg_211(3 downto 1);
    tmp_53_fu_433_p4 <= c_i_reg_222(3 downto 1);
    tmp_6_cast_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_389_p3),10));
    tmp_7_cast_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_512_p2),64));
    tmp_7_fu_512_p2 <= std_logic_vector(unsigned(tmp_6_cast_reg_654) + unsigned(tmp_36_i_cast_fu_508_p1));
    tmp_8_cast_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_413_p2),64));
    tmp_8_fu_413_p2 <= (ic_i_reg_234 xor ap_const_lv6_20);
    tmp_9_fu_424_p3 <= (ap_const_lv58_1 & ic_i_reg_234);
    tmp_fu_389_p3 <= (c_i_reg_222 & ap_const_lv5_0);

    win_buf_address0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, win_buf_addr_2_reg_679, ap_CS_fsm_state6, win_buf_addr_8_reg_706, ap_CS_fsm_state9, tmp_8_cast_fu_419_p1, tmp_10_fu_458_p3, tmp_13_cast_fu_481_p1, tmp_36_i_fu_495_p1, tmp_11_cast_fu_503_p1, ap_CS_fsm_state8, tmp_14_fu_523_p3, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            win_buf_address0 <= win_buf_addr_8_reg_706;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_address0 <= win_buf_addr_2_reg_679;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            win_buf_address0 <= tmp_14_fu_523_p3(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_address0 <= tmp_11_cast_fu_503_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            win_buf_address0 <= tmp_36_i_fu_495_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            win_buf_address0 <= tmp_13_cast_fu_481_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            win_buf_address0 <= tmp_10_fu_458_p3(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            win_buf_address0 <= tmp_8_cast_fu_419_p1(9 - 1 downto 0);
        else 
            win_buf_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    win_buf_address1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, win_buf_addr_reg_673, win_buf_addr_3_reg_689, win_buf_addr_5_reg_695, win_buf_addr_6_reg_700, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state15, tmp_9_fu_424_p3, tmp_12_cast_fu_473_p1, tmp_15_fu_486_p3, ap_CS_fsm_state8, tmp_21_cast_fu_628_p1, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            win_buf_address1 <= tmp_21_cast_fu_628_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_address1 <= win_buf_addr_5_reg_695;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            win_buf_address1 <= win_buf_addr_6_reg_700;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_address1 <= win_buf_addr_3_reg_689;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            win_buf_address1 <= win_buf_addr_reg_673;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            win_buf_address1 <= tmp_15_fu_486_p3(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            win_buf_address1 <= tmp_12_cast_fu_473_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            win_buf_address1 <= tmp_9_fu_424_p3(9 - 1 downto 0);
        else 
            win_buf_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    win_buf_ce0_assign_proc : process(f4_empty_n, ap_CS_fsm_state11, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5) or ((f4_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            win_buf_ce0 <= ap_const_logic_1;
        else 
            win_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_ce1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state15, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            win_buf_ce1 <= ap_const_logic_1;
        else 
            win_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_d0_assign_proc : process(f4_dout, linbu_0_q0, ap_CS_fsm_state11, reg_337, ap_CS_fsm_state7, win_buf_load_2_reg_712, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            win_buf_d0 <= f4_dout;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_d0 <= linbu_0_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_d0 <= win_buf_load_2_reg_712;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            win_buf_d0 <= reg_337;
        else 
            win_buf_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    win_buf_d1_assign_proc : process(linbu_1_q0, ap_CS_fsm_state7, reg_344, win_buf_load_3_reg_717, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_d1 <= linbu_1_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_d1 <= win_buf_load_3_reg_717;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            win_buf_d1 <= reg_344;
        else 
            win_buf_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    win_buf_we0_assign_proc : process(f4_empty_n, ap_CS_fsm_state11, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7) or ((f4_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            win_buf_we0 <= ap_const_logic_1;
        else 
            win_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_we1_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            win_buf_we1 <= ap_const_logic_1;
        else 
            win_buf_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
