-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    p1_ce0 : OUT STD_LOGIC;
    p1_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (25 downto 0) := "00000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (25 downto 0) := "00000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (25 downto 0) := "00000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (25 downto 0) := "00000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (25 downto 0) := "00000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (25 downto 0) := "00000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (25 downto 0) := "00001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (25 downto 0) := "00010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (25 downto 0) := "00100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (25 downto 0) := "01000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv60_1 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv60_2 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv60_4 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv60_3 : STD_LOGIC_VECTOR (59 downto 0) := "000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv11_1D : STD_LOGIC_VECTOR (10 downto 0) := "00000011101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal linbu_5_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linbu_5_0_ce0 : STD_LOGIC;
    signal linbu_5_0_we0 : STD_LOGIC;
    signal linbu_5_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal linbu_5_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linbu_5_1_ce0 : STD_LOGIC;
    signal linbu_5_1_we0 : STD_LOGIC;
    signal linbu_5_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal win_buf_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_360 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal win_buf_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal reg_367 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_fu_382_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal r_reg_810 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_145_fu_404_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_145_reg_815 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond6_i_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_820 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_799_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_146_reg_825 : STD_LOGIC_VECTOR (10 downto 0);
    signal c_fu_432_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal c_reg_833 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_192_cast_fu_450_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_192_cast_reg_838 : STD_LOGIC_VECTOR (8 downto 0);
    signal exitcond5_i_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_195_cast_fu_459_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_195_cast_reg_843 : STD_LOGIC_VECTOR (13 downto 0);
    signal ic_fu_473_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ic_reg_851 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_151_fu_479_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_151_reg_856 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond4_i_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal win_buf_addr_reg_862 : STD_LOGIC_VECTOR (6 downto 0);
    signal win_buf_addr_29_reg_868 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_cond_i_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_874 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_208_cast_fu_535_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_208_cast_reg_878 : STD_LOGIC_VECTOR (14 downto 0);
    signal win_buf_addr_30_reg_883 : STD_LOGIC_VECTOR (6 downto 0);
    signal win_buf_addr_32_reg_889 : STD_LOGIC_VECTOR (6 downto 0);
    signal win_buf_addr_33_reg_894 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal win_buf_addr_35_reg_900 : STD_LOGIC_VECTOR (6 downto 0);
    signal win_buf_load_20_reg_906 : STD_LOGIC_VECTOR (31 downto 0);
    signal win_buf_load_21_reg_911 : STD_LOGIC_VECTOR (31 downto 0);
    signal linbu_5_0_addr_reg_916 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal linbu_5_1_addr_reg_921 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_150_fu_616_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_150_reg_926 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal oc_fu_640_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal oc_reg_939 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal out_addr_reg_944 : STD_LOGIC_VECTOR (13 downto 0);
    signal exitcond3_i_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal kr_fu_666_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kr_reg_952 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal tmp_160_fu_688_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_160_reg_957 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond2_i_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_reg_962 : STD_LOGIC_VECTOR (0 downto 0);
    signal kc_fu_700_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kc_reg_970 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal tmp_214_cast_fu_715_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_214_cast_reg_975 : STD_LOGIC_VECTOR (7 downto 0);
    signal exitcond1_i_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_4_fu_729_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ic_4_reg_983 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal exitcond_i_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_349_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_82_i_reg_993 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_fu_344_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal win_buf_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal win_buf_ce0 : STD_LOGIC;
    signal win_buf_we0 : STD_LOGIC;
    signal win_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal win_buf_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal win_buf_ce1 : STD_LOGIC;
    signal win_buf_we1 : STD_LOGIC;
    signal win_buf_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_i_reg_229 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal c_i_reg_240 : STD_LOGIC_VECTOR (4 downto 0);
    signal ic_i_reg_252 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal oc_i_reg_264 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal kr_i_reg_275 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum8_i_reg_286 : STD_LOGIC_VECTOR (31 downto 0);
    signal kc_i_reg_298 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_1_i_reg_309 : STD_LOGIC_VECTOR (31 downto 0);
    signal ic_1_i_reg_321 : STD_LOGIC_VECTOR (3 downto 0);
    signal sum_2_i_reg_332 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_198_cast_fu_485_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_152_fu_490_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_153_fu_547_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_202_cast_fu_562_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_203_cast_fu_570_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_156_fu_575_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_74_i_fu_584_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_201_cast_fu_592_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal tmp_196_cast_fu_610_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_155_fu_621_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_197_cast_fu_630_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_209_cast_fu_655_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_215_cast_fu_744_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal tmp_s_fu_392_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl_cast_fu_400_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_cast_fu_388_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_95_fu_410_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_147_fu_442_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_72_i_cast_fu_438_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_148_fu_454_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_96_fu_499_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp4_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_75_i_fu_520_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_76_i_cast_fu_526_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_157_fu_530_p2 : STD_LOGIC_VECTOR (10 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of tmp_157_fu_530_p2 : signal is "no";
    signal tmp_74_i_cast5_fu_543_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_154_fu_556_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_203_cast6_fu_567_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_201_cast7_fu_589_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_74_i_cast_fu_601_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_149_fu_605_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_74_i_cast2_fu_597_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_77_i_cast_fu_646_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_158_fu_650_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_159_fu_676_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl1_cast_fu_684_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_79_i_cast_fu_672_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_80_i_cast_fu_706_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_161_fu_710_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_81_i_cast_fu_735_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_162_fu_739_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum8_i_to_int_fu_749_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_753_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_97_fu_763_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal notrhs_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal notlhs_fu_767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_799_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_799_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_799_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_799_p00 : STD_LOGIC_VECTOR (5 downto 0);

    component topp_fadd_32ns_32bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component topp_fmul_32ns_32cud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component topp_fcmp_32ns_32dEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component topp_am_addmul_5neOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component conv2_linbu_5_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2_win_buf IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    linbu_5_0_U : component conv2_linbu_5_0
    generic map (
        DataWidth => 32,
        AddressRange => 248,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linbu_5_0_address0,
        ce0 => linbu_5_0_ce0,
        we0 => linbu_5_0_we0,
        d0 => linbu_5_1_q0,
        q0 => linbu_5_0_q0);

    linbu_5_1_U : component conv2_linbu_5_0
    generic map (
        DataWidth => 32,
        AddressRange => 248,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => linbu_5_1_address0,
        ce0 => linbu_5_1_ce0,
        we0 => linbu_5_1_we0,
        d0 => p1_q0,
        q0 => linbu_5_1_q0);

    win_buf_U : component conv2_win_buf
    generic map (
        DataWidth => 32,
        AddressRange => 72,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => win_buf_address0,
        ce0 => win_buf_ce0,
        we0 => win_buf_we0,
        d0 => win_buf_d0,
        q0 => win_buf_q0,
        address1 => win_buf_address1,
        ce1 => win_buf_ce1,
        we1 => win_buf_we1,
        d1 => win_buf_d1,
        q1 => win_buf_q1);

    topp_fadd_32ns_32bkb_U14 : component topp_fadd_32ns_32bkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sum_2_i_reg_332,
        din1 => tmp_82_i_reg_993,
        ce => ap_const_logic_1,
        dout => grp_fu_344_p2);

    topp_fmul_32ns_32cud_U15 : component topp_fmul_32ns_32cud
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_360,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        dout => grp_fu_349_p2);

    topp_fcmp_32ns_32dEe_U16 : component topp_fcmp_32ns_32dEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        din0 => sum8_i_reg_286,
        din1 => ap_const_lv32_0,
        opcode => ap_const_lv5_4,
        dout => tmp_58_fu_354_p2);

    topp_am_addmul_5neOg_U17 : component topp_am_addmul_5neOg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 2,
        din2_WIDTH => 6,
        dout_WIDTH => 11)
    port map (
        din0 => grp_fu_799_p0,
        din1 => grp_fu_799_p1,
        din2 => grp_fu_799_p2,
        dout => grp_fu_799_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_376_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    c_i_reg_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_376_p2 = ap_const_lv1_0))) then 
                c_i_reg_240 <= ap_const_lv5_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and ((exitcond3_i_fu_634_p2 = ap_const_lv1_1) or (or_cond_i_reg_874 = ap_const_lv1_0)))) then 
                c_i_reg_240 <= c_reg_833;
            end if; 
        end if;
    end process;

    ic_1_i_reg_321_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_694_p2 = ap_const_lv1_0))) then 
                ic_1_i_reg_321 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                ic_1_i_reg_321 <= ic_4_reg_983;
            end if; 
        end if;
    end process;

    ic_i_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_426_p2 = ap_const_lv1_0))) then 
                ic_i_reg_252 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                ic_i_reg_252 <= ic_reg_851;
            end if; 
        end if;
    end process;

    kc_i_reg_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (exitcond_i_fu_723_p2 = ap_const_lv1_1))) then 
                kc_i_reg_298 <= kc_reg_970;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_660_p2 = ap_const_lv1_0))) then 
                kc_i_reg_298 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    kr_i_reg_275_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_694_p2 = ap_const_lv1_1))) then 
                kr_i_reg_275 <= kr_reg_952;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (or_cond_i_reg_874 = ap_const_lv1_1) and (exitcond3_i_fu_634_p2 = ap_const_lv1_0))) then 
                kr_i_reg_275 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    oc_i_reg_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (or_cond_i_fu_515_p2 = ap_const_lv1_1) and (exitcond4_i_fu_467_p2 = ap_const_lv1_1))) then 
                oc_i_reg_264 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
                oc_i_reg_264 <= oc_reg_939;
            end if; 
        end if;
    end process;

    r_i_reg_229_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_426_p2 = ap_const_lv1_1))) then 
                r_i_reg_229 <= r_reg_810;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                r_i_reg_229 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    reg_360_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
                reg_360 <= win_buf_q1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                reg_360 <= win_buf_q0;
            end if; 
        end if;
    end process;

    sum8_i_reg_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_694_p2 = ap_const_lv1_1))) then 
                sum8_i_reg_286 <= sum_1_i_reg_309;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state12) and (or_cond_i_reg_874 = ap_const_lv1_1) and (exitcond3_i_fu_634_p2 = ap_const_lv1_0))) then 
                sum8_i_reg_286 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    sum_1_i_reg_309_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state15) and (exitcond_i_fu_723_p2 = ap_const_lv1_1))) then 
                sum_1_i_reg_309 <= sum_2_i_reg_332;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_660_p2 = ap_const_lv1_0))) then 
                sum_1_i_reg_309 <= sum8_i_reg_286;
            end if; 
        end if;
    end process;

    sum_2_i_reg_332_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_694_p2 = ap_const_lv1_0))) then 
                sum_2_i_reg_332 <= sum_1_i_reg_309;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
                sum_2_i_reg_332 <= grp_fu_344_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                c_reg_833 <= c_fu_432_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                ic_4_reg_983 <= ic_4_fu_729_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                ic_reg_851 <= ic_fu_473_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_376_p2 = ap_const_lv1_0))) then
                icmp_reg_820 <= icmp_fu_420_p2;
                tmp_145_reg_815 <= tmp_145_fu_404_p2;
                tmp_146_reg_825 <= grp_fu_799_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                kc_reg_970 <= kc_fu_700_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                kr_reg_952 <= kr_fu_666_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                linbu_5_0_addr_reg_916 <= tmp_196_cast_fu_610_p1(8 - 1 downto 0);
                linbu_5_1_addr_reg_921 <= tmp_196_cast_fu_610_p1(8 - 1 downto 0);
                tmp_150_reg_926 <= tmp_150_fu_616_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (or_cond_i_reg_874 = ap_const_lv1_1))) then
                oc_reg_939 <= oc_fu_640_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond4_i_fu_467_p2 = ap_const_lv1_1))) then
                or_cond_i_reg_874 <= or_cond_i_fu_515_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) and (or_cond_i_reg_874 = ap_const_lv1_1) and (exitcond3_i_fu_634_p2 = ap_const_lv1_0))) then
                out_addr_reg_944 <= tmp_209_cast_fu_655_p1(14 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                r_reg_810 <= r_fu_382_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_367 <= win_buf_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond4_i_fu_467_p2 = ap_const_lv1_0))) then
                tmp_151_reg_856 <= tmp_151_fu_479_p2;
                    win_buf_addr_29_reg_868(3 downto 0) <= tmp_152_fu_490_p3(7 - 1 downto 0)(3 downto 0);
                    win_buf_addr_reg_862(3 downto 0) <= tmp_198_cast_fu_485_p1(7 - 1 downto 0)(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_660_p2 = ap_const_lv1_0))) then
                tmp_160_reg_957 <= tmp_160_fu_688_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_426_p2 = ap_const_lv1_0))) then
                    tmp_192_cast_reg_838(7 downto 3) <= tmp_192_cast_fu_450_p1(7 downto 3);
                    tmp_195_cast_reg_843(13 downto 3) <= tmp_195_cast_fu_459_p3(13 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (or_cond_i_fu_515_p2 = ap_const_lv1_1) and (exitcond4_i_fu_467_p2 = ap_const_lv1_1))) then
                    tmp_208_cast_reg_878(14 downto 4) <= tmp_208_cast_fu_535_p3(14 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_694_p2 = ap_const_lv1_0))) then
                    tmp_214_cast_reg_975(7 downto 3) <= tmp_214_cast_fu_715_p3(7 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_660_p2 = ap_const_lv1_1))) then
                tmp_58_reg_962 <= tmp_58_fu_354_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                tmp_82_i_reg_993 <= grp_fu_349_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    win_buf_addr_30_reg_883(3 downto 0) <= tmp_153_fu_547_p3(7 - 1 downto 0)(3 downto 0);
                    win_buf_addr_32_reg_889(5 downto 0) <= tmp_202_cast_fu_562_p1(7 - 1 downto 0)(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                    win_buf_addr_33_reg_894(5 downto 0) <= tmp_203_cast_fu_570_p1(7 - 1 downto 0)(5 downto 0);
                    win_buf_addr_35_reg_900(3 downto 0) <= tmp_156_fu_575_p3(7 - 1 downto 0)(3 downto 0);
                win_buf_load_20_reg_906 <= win_buf_q0;
                win_buf_load_21_reg_911 <= win_buf_q1;
            end if;
        end if;
    end process;
    tmp_192_cast_reg_838(2 downto 0) <= "000";
    tmp_192_cast_reg_838(8) <= '0';
    tmp_195_cast_reg_843(2 downto 0) <= "000";
    win_buf_addr_reg_862(6 downto 4) <= "000";
    win_buf_addr_29_reg_868(6 downto 4) <= "001";
    tmp_208_cast_reg_878(3 downto 0) <= "0000";
    win_buf_addr_30_reg_883(6 downto 4) <= "010";
    win_buf_addr_32_reg_889(6) <= '0';
    win_buf_addr_33_reg_894(6) <= '0';
    win_buf_addr_35_reg_900(6 downto 4) <= "100";
    tmp_214_cast_reg_975(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond6_i_fu_376_p2, ap_CS_fsm_state3, exitcond5_i_fu_426_p2, ap_CS_fsm_state4, exitcond4_i_fu_467_p2, or_cond_i_reg_874, ap_CS_fsm_state12, exitcond3_i_fu_634_p2, ap_CS_fsm_state13, exitcond2_i_fu_660_p2, ap_CS_fsm_state14, exitcond1_i_fu_694_p2, ap_CS_fsm_state15, exitcond_i_fu_723_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_376_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond5_i_fu_426_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (exitcond4_i_fu_467_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and ((exitcond3_i_fu_634_p2 = ap_const_lv1_1) or (or_cond_i_reg_874 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and (exitcond2_i_fu_660_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state26;
                end if;
            when ap_ST_fsm_state14 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state14) and (exitcond1_i_fu_694_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when ap_ST_fsm_state15 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state15) and (exitcond_i_fu_723_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, exitcond6_i_fu_376_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_376_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond6_i_fu_376_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond6_i_fu_376_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    c_fu_432_p2 <= std_logic_vector(unsigned(c_i_reg_240) + unsigned(ap_const_lv5_1));
    exitcond1_i_fu_694_p2 <= "1" when (kc_i_reg_298 = ap_const_lv2_3) else "0";
    exitcond2_i_fu_660_p2 <= "1" when (kr_i_reg_275 = ap_const_lv2_3) else "0";
    exitcond3_i_fu_634_p2 <= "1" when (oc_i_reg_264 = ap_const_lv5_10) else "0";
    exitcond4_i_fu_467_p2 <= "1" when (ic_i_reg_252 = ap_const_lv4_8) else "0";
    exitcond5_i_fu_426_p2 <= "1" when (c_i_reg_240 = ap_const_lv5_1F) else "0";
    exitcond6_i_fu_376_p2 <= "1" when (r_i_reg_229 = ap_const_lv5_1F) else "0";
    exitcond_i_fu_723_p2 <= "1" when (ic_1_i_reg_321 = ap_const_lv4_8) else "0";
    grp_fu_799_p0 <= grp_fu_799_p00(5 - 1 downto 0);
    grp_fu_799_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_i_reg_229),6));
    grp_fu_799_p1 <= ap_const_lv6_3E(2 - 1 downto 0);
    grp_fu_799_p2 <= ap_const_lv11_1D(6 - 1 downto 0);
    ic_4_fu_729_p2 <= std_logic_vector(unsigned(ic_1_i_reg_321) + unsigned(ap_const_lv4_1));
    ic_fu_473_p2 <= std_logic_vector(unsigned(ic_i_reg_252) + unsigned(ap_const_lv4_1));
    icmp4_fu_509_p2 <= "0" when (tmp_96_fu_499_p4 = ap_const_lv4_0) else "1";
    icmp_fu_420_p2 <= "0" when (tmp_95_fu_410_p4 = ap_const_lv4_0) else "1";
    kc_fu_700_p2 <= std_logic_vector(unsigned(kc_i_reg_298) + unsigned(ap_const_lv2_1));
    kr_fu_666_p2 <= std_logic_vector(unsigned(kr_i_reg_275) + unsigned(ap_const_lv2_1));

    linbu_5_0_address0_assign_proc : process(linbu_5_0_addr_reg_916, ap_CS_fsm_state9, ap_CS_fsm_state10, tmp_196_cast_fu_610_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            linbu_5_0_address0 <= linbu_5_0_addr_reg_916;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linbu_5_0_address0 <= tmp_196_cast_fu_610_p1(8 - 1 downto 0);
        else 
            linbu_5_0_address0 <= "XXXXXXXX";
        end if; 
    end process;


    linbu_5_0_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            linbu_5_0_ce0 <= ap_const_logic_1;
        else 
            linbu_5_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_5_0_we0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            linbu_5_0_we0 <= ap_const_logic_1;
        else 
            linbu_5_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_5_1_address0_assign_proc : process(ap_CS_fsm_state9, linbu_5_1_addr_reg_921, ap_CS_fsm_state11, tmp_196_cast_fu_610_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            linbu_5_1_address0 <= linbu_5_1_addr_reg_921;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            linbu_5_1_address0 <= tmp_196_cast_fu_610_p1(8 - 1 downto 0);
        else 
            linbu_5_1_address0 <= "XXXXXXXX";
        end if; 
    end process;


    linbu_5_1_ce0_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            linbu_5_1_ce0 <= ap_const_logic_1;
        else 
            linbu_5_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    linbu_5_1_we0_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            linbu_5_1_we0 <= ap_const_logic_1;
        else 
            linbu_5_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    notlhs_fu_767_p2 <= "0" when (tmp_fu_753_p4 = ap_const_lv8_FF) else "1";
    notrhs_fu_773_p2 <= "1" when (tmp_97_fu_763_p1 = ap_const_lv23_0) else "0";
    oc_fu_640_p2 <= std_logic_vector(unsigned(oc_i_reg_264) + unsigned(ap_const_lv5_1));
    or_cond_i_fu_515_p2 <= (icmp_reg_820 and icmp4_fu_509_p2);
    out_r_address0 <= out_addr_reg_944;

    out_r_ce0_assign_proc : process(ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            out_r_ce0 <= ap_const_logic_1;
        else 
            out_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_r_d0 <= 
        ap_const_lv32_0 when (tmp_59_fu_785_p2(0) = '1') else 
        sum8_i_reg_286;

    out_r_we0_assign_proc : process(ap_CS_fsm_state26)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            out_r_we0 <= ap_const_logic_1;
        else 
            out_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p1_address0 <= tmp_197_cast_fu_630_p1(13 - 1 downto 0);

    p1_ce0_assign_proc : process(ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            p1_ce0 <= ap_const_logic_1;
        else 
            p1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_cast_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_159_fu_676_p3),5));
    p_shl_cast_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_392_p3),11));
    r_fu_382_p2 <= std_logic_vector(unsigned(r_i_reg_229) + unsigned(ap_const_lv5_1));
    sum8_i_to_int_fu_749_p1 <= sum8_i_reg_286;
    tmp_145_fu_404_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_400_p1) - unsigned(tmp_i_cast_fu_388_p1));
    tmp_147_fu_442_p3 <= (c_i_reg_240 & ap_const_lv3_0);
    tmp_148_fu_454_p2 <= std_logic_vector(unsigned(tmp_72_i_cast_fu_438_p1) + unsigned(tmp_145_reg_815));
    tmp_149_fu_605_p2 <= std_logic_vector(unsigned(tmp_192_cast_reg_838) + unsigned(tmp_74_i_cast_fu_601_p1));
    tmp_150_fu_616_p2 <= std_logic_vector(unsigned(tmp_195_cast_reg_843) + unsigned(tmp_74_i_cast2_fu_597_p1));
    tmp_151_fu_479_p2 <= (ic_i_reg_252 xor ap_const_lv4_8);
    tmp_152_fu_490_p3 <= (ap_const_lv60_1 & ic_i_reg_252);
    tmp_153_fu_547_p3 <= (ap_const_lv60_2 & ic_i_reg_252);
    tmp_154_fu_556_p2 <= std_logic_vector(unsigned(tmp_74_i_cast5_fu_543_p1) + unsigned(ap_const_lv6_28));
    tmp_155_fu_621_p3 <= (ap_const_lv60_3 & ic_i_reg_252);
    tmp_156_fu_575_p3 <= (ap_const_lv60_4 & ic_i_reg_252);
    tmp_157_fu_530_p2 <= std_logic_vector(unsigned(tmp_76_i_cast_fu_526_p1) + unsigned(tmp_146_reg_825));
    tmp_158_fu_650_p2 <= std_logic_vector(unsigned(tmp_208_cast_reg_878) + unsigned(tmp_77_i_cast_fu_646_p1));
    tmp_159_fu_676_p3 <= (kr_i_reg_275 & ap_const_lv2_0);
    tmp_160_fu_688_p2 <= std_logic_vector(unsigned(p_shl1_cast_fu_684_p1) - unsigned(tmp_79_i_cast_fu_672_p1));
    tmp_161_fu_710_p2 <= std_logic_vector(unsigned(tmp_80_i_cast_fu_706_p1) + unsigned(tmp_160_reg_957));
    tmp_162_fu_739_p2 <= std_logic_vector(unsigned(tmp_214_cast_reg_975) + unsigned(tmp_81_i_cast_fu_735_p1));
    tmp_192_cast_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_147_fu_442_p3),9));
    tmp_195_cast_fu_459_p3 <= (tmp_148_fu_454_p2 & ap_const_lv3_0);
    tmp_196_cast_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_149_fu_605_p2),64));
    tmp_197_cast_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_150_reg_926),64));
    tmp_198_cast_fu_485_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_151_fu_479_p2),64));
        tmp_201_cast7_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_151_reg_856),5));

    tmp_201_cast_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_201_cast7_fu_589_p1),64));
    tmp_202_cast_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_154_fu_556_p2),64));
        tmp_203_cast6_fu_567_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_151_reg_856),6));

    tmp_203_cast_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_203_cast6_fu_567_p1),64));
    tmp_208_cast_fu_535_p3 <= (tmp_157_fu_530_p2 & ap_const_lv4_0);
    tmp_209_cast_fu_655_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_158_fu_650_p2),64));
    tmp_214_cast_fu_715_p3 <= (tmp_161_fu_710_p2 & ap_const_lv3_0);
    tmp_215_cast_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_162_fu_739_p2),64));
    tmp_57_fu_779_p2 <= (notrhs_fu_773_p2 or notlhs_fu_767_p2);
    tmp_59_fu_785_p2 <= (tmp_58_reg_962 and tmp_57_fu_779_p2);
    tmp_72_i_cast_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_i_reg_240),11));
    tmp_74_i_cast2_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_252),14));
    tmp_74_i_cast5_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_252),6));
    tmp_74_i_cast_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_252),9));
    tmp_74_i_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_i_reg_252),64));
    tmp_75_i_fu_520_p2 <= std_logic_vector(unsigned(c_i_reg_240) + unsigned(ap_const_lv5_1E));
    tmp_76_i_cast_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_75_i_fu_520_p2),11));
    tmp_77_i_cast_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_i_reg_264),15));
    tmp_79_i_cast_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kr_i_reg_275),5));
    tmp_80_i_cast_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kc_i_reg_298),5));
    tmp_81_i_cast_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_1_i_reg_321),8));
    tmp_95_fu_410_p4 <= r_i_reg_229(4 downto 1);
    tmp_96_fu_499_p4 <= c_i_reg_240(4 downto 1);
    tmp_97_fu_763_p1 <= sum8_i_to_int_fu_749_p1(23 - 1 downto 0);
    tmp_fu_753_p4 <= sum8_i_to_int_fu_749_p1(30 downto 23);
    tmp_i_cast_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_i_reg_229),11));
    tmp_s_fu_392_p3 <= (r_i_reg_229 & ap_const_lv5_0);

    win_buf_address0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, win_buf_addr_29_reg_868, ap_CS_fsm_state6, win_buf_addr_35_reg_900, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, tmp_198_cast_fu_485_p1, tmp_153_fu_547_p3, tmp_203_cast_fu_570_p1, tmp_74_i_fu_584_p1, tmp_201_cast_fu_592_p1, ap_CS_fsm_state8, tmp_155_fu_621_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            win_buf_address0 <= win_buf_addr_35_reg_900;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_address0 <= win_buf_addr_29_reg_868;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            win_buf_address0 <= tmp_155_fu_621_p3(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_address0 <= tmp_201_cast_fu_592_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            win_buf_address0 <= tmp_74_i_fu_584_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            win_buf_address0 <= tmp_203_cast_fu_570_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            win_buf_address0 <= tmp_153_fu_547_p3(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            win_buf_address0 <= tmp_198_cast_fu_485_p1(7 - 1 downto 0);
        else 
            win_buf_address0 <= "XXXXXXX";
        end if; 
    end process;


    win_buf_address1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, win_buf_addr_reg_862, win_buf_addr_30_reg_883, win_buf_addr_32_reg_889, win_buf_addr_33_reg_894, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state15, tmp_152_fu_490_p3, tmp_202_cast_fu_562_p1, tmp_156_fu_575_p3, ap_CS_fsm_state8, tmp_215_cast_fu_744_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            win_buf_address1 <= tmp_215_cast_fu_744_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_address1 <= win_buf_addr_32_reg_889;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            win_buf_address1 <= win_buf_addr_33_reg_894;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_address1 <= win_buf_addr_30_reg_883;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            win_buf_address1 <= win_buf_addr_reg_862;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            win_buf_address1 <= tmp_156_fu_575_p3(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            win_buf_address1 <= tmp_202_cast_fu_562_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            win_buf_address1 <= tmp_152_fu_490_p3(7 - 1 downto 0);
        else 
            win_buf_address1 <= "XXXXXXX";
        end if; 
    end process;


    win_buf_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            win_buf_ce0 <= ap_const_logic_1;
        else 
            win_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_ce1_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state15, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            win_buf_ce1 <= ap_const_logic_1;
        else 
            win_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_d0_assign_proc : process(p1_q0, linbu_5_0_q0, reg_360, ap_CS_fsm_state7, win_buf_load_20_reg_906, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            win_buf_d0 <= p1_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_d0 <= linbu_5_0_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_d0 <= win_buf_load_20_reg_906;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            win_buf_d0 <= reg_360;
        else 
            win_buf_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    win_buf_d1_assign_proc : process(linbu_5_1_q0, ap_CS_fsm_state7, reg_367, win_buf_load_21_reg_911, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            win_buf_d1 <= linbu_5_1_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            win_buf_d1 <= win_buf_load_21_reg_911;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            win_buf_d1 <= reg_367;
        else 
            win_buf_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    win_buf_we0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            win_buf_we0 <= ap_const_logic_1;
        else 
            win_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    win_buf_we1_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            win_buf_we1 <= ap_const_logic_1;
        else 
            win_buf_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
