// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="topp,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.677000,HLS_SYN_LAT=7482665,HLS_SYN_TPT=7433162,HLS_SYN_MEM=38,HLS_SYN_DSP=43,HLS_SYN_FF=32970,HLS_SYN_LUT=31291,HLS_VERSION=2018_3}" *)

module topp (
        image_r_address0,
        image_r_ce0,
        image_r_d0,
        image_r_q0,
        image_r_we0,
        image_r_address1,
        image_r_ce1,
        image_r_d1,
        image_r_q1,
        image_r_we1,
        output_r_address0,
        output_r_ce0,
        output_r_d0,
        output_r_q0,
        output_r_we0,
        output_r_address1,
        output_r_ce1,
        output_r_d1,
        output_r_q1,
        output_r_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output  [13:0] image_r_address0;
output   image_r_ce0;
output  [31:0] image_r_d0;
input  [31:0] image_r_q0;
output   image_r_we0;
output  [13:0] image_r_address1;
output   image_r_ce1;
output  [31:0] image_r_d1;
input  [31:0] image_r_q1;
output   image_r_we1;
output  [9:0] output_r_address0;
output   output_r_ce0;
output  [31:0] output_r_d0;
input  [31:0] output_r_q0;
output   output_r_we0;
output  [9:0] output_r_address1;
output   output_r_ce1;
output  [31:0] output_r_d1;
input  [31:0] output_r_q1;
output   output_r_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    conv1_U0_ap_start;
wire    conv1_U0_ap_done;
wire    conv1_U0_ap_continue;
wire    conv1_U0_ap_idle;
wire    conv1_U0_ap_ready;
wire    conv1_U0_start_out;
wire    conv1_U0_start_write;
wire   [13:0] conv1_U0_in_r_address0;
wire    conv1_U0_in_r_ce0;
wire   [31:0] conv1_U0_out_0_din;
wire    conv1_U0_out_0_write;
wire   [31:0] conv1_U0_out_1_din;
wire    conv1_U0_out_1_write;
wire   [31:0] conv1_U0_out_2_din;
wire    conv1_U0_out_2_write;
wire   [31:0] conv1_U0_out_3_din;
wire    conv1_U0_out_3_write;
wire   [31:0] conv1_U0_out_4_din;
wire    conv1_U0_out_4_write;
wire   [31:0] conv1_U0_out_5_din;
wire    conv1_U0_out_5_write;
wire   [31:0] conv1_U0_out_6_din;
wire    conv1_U0_out_6_write;
wire   [31:0] conv1_U0_out_7_din;
wire    conv1_U0_out_7_write;
wire    maxpool1_U0_ap_start;
wire    maxpool1_U0_ap_done;
wire    maxpool1_U0_ap_continue;
wire    maxpool1_U0_ap_idle;
wire    maxpool1_U0_ap_ready;
wire    maxpool1_U0_start_out;
wire    maxpool1_U0_start_write;
wire   [31:0] maxpool1_U0_out_0_din;
wire    maxpool1_U0_out_0_write;
wire   [31:0] maxpool1_U0_out_1_din;
wire    maxpool1_U0_out_1_write;
wire   [31:0] maxpool1_U0_out_2_din;
wire    maxpool1_U0_out_2_write;
wire   [31:0] maxpool1_U0_out_3_din;
wire    maxpool1_U0_out_3_write;
wire   [31:0] maxpool1_U0_out_4_din;
wire    maxpool1_U0_out_4_write;
wire   [31:0] maxpool1_U0_out_5_din;
wire    maxpool1_U0_out_5_write;
wire   [31:0] maxpool1_U0_out_6_din;
wire    maxpool1_U0_out_6_write;
wire   [31:0] maxpool1_U0_out_7_din;
wire    maxpool1_U0_out_7_write;
wire    maxpool1_U0_f1_0_read;
wire    maxpool1_U0_f1_1_read;
wire    maxpool1_U0_f1_2_read;
wire    maxpool1_U0_f1_3_read;
wire    maxpool1_U0_f1_4_read;
wire    maxpool1_U0_f1_5_read;
wire    maxpool1_U0_f1_6_read;
wire    maxpool1_U0_f1_7_read;
wire    conv2_U0_ap_start;
wire    conv2_U0_ap_done;
wire    conv2_U0_ap_continue;
wire    conv2_U0_ap_idle;
wire    conv2_U0_ap_ready;
wire    conv2_U0_start_out;
wire    conv2_U0_start_write;
wire   [31:0] conv2_U0_out_0_din;
wire    conv2_U0_out_0_write;
wire   [31:0] conv2_U0_out_1_din;
wire    conv2_U0_out_1_write;
wire   [31:0] conv2_U0_out_2_din;
wire    conv2_U0_out_2_write;
wire   [31:0] conv2_U0_out_3_din;
wire    conv2_U0_out_3_write;
wire   [31:0] conv2_U0_out_4_din;
wire    conv2_U0_out_4_write;
wire   [31:0] conv2_U0_out_5_din;
wire    conv2_U0_out_5_write;
wire   [31:0] conv2_U0_out_6_din;
wire    conv2_U0_out_6_write;
wire   [31:0] conv2_U0_out_7_din;
wire    conv2_U0_out_7_write;
wire    conv2_U0_p1_0_read;
wire    conv2_U0_p1_1_read;
wire    conv2_U0_p1_2_read;
wire    conv2_U0_p1_3_read;
wire    conv2_U0_p1_4_read;
wire    conv2_U0_p1_5_read;
wire    conv2_U0_p1_6_read;
wire    conv2_U0_p1_7_read;
wire    maxpool2_U0_ap_start;
wire    maxpool2_U0_ap_done;
wire    maxpool2_U0_ap_continue;
wire    maxpool2_U0_ap_idle;
wire    maxpool2_U0_ap_ready;
wire    maxpool2_U0_start_out;
wire    maxpool2_U0_start_write;
wire   [31:0] maxpool2_U0_out_0_din;
wire    maxpool2_U0_out_0_write;
wire   [31:0] maxpool2_U0_out_1_din;
wire    maxpool2_U0_out_1_write;
wire   [31:0] maxpool2_U0_out_2_din;
wire    maxpool2_U0_out_2_write;
wire   [31:0] maxpool2_U0_out_3_din;
wire    maxpool2_U0_out_3_write;
wire   [31:0] maxpool2_U0_out_4_din;
wire    maxpool2_U0_out_4_write;
wire   [31:0] maxpool2_U0_out_5_din;
wire    maxpool2_U0_out_5_write;
wire   [31:0] maxpool2_U0_out_6_din;
wire    maxpool2_U0_out_6_write;
wire   [31:0] maxpool2_U0_out_7_din;
wire    maxpool2_U0_out_7_write;
wire    maxpool2_U0_f2_0_read;
wire    maxpool2_U0_f2_1_read;
wire    maxpool2_U0_f2_2_read;
wire    maxpool2_U0_f2_3_read;
wire    maxpool2_U0_f2_4_read;
wire    maxpool2_U0_f2_5_read;
wire    maxpool2_U0_f2_6_read;
wire    maxpool2_U0_f2_7_read;
wire    conv3_U0_ap_start;
wire    conv3_U0_ap_done;
wire    conv3_U0_ap_continue;
wire    conv3_U0_ap_idle;
wire    conv3_U0_ap_ready;
wire    conv3_U0_start_out;
wire    conv3_U0_start_write;
wire   [31:0] conv3_U0_out_0_din;
wire    conv3_U0_out_0_write;
wire   [31:0] conv3_U0_out_1_din;
wire    conv3_U0_out_1_write;
wire   [31:0] conv3_U0_out_2_din;
wire    conv3_U0_out_2_write;
wire   [31:0] conv3_U0_out_3_din;
wire    conv3_U0_out_3_write;
wire   [31:0] conv3_U0_out_4_din;
wire    conv3_U0_out_4_write;
wire   [31:0] conv3_U0_out_5_din;
wire    conv3_U0_out_5_write;
wire   [31:0] conv3_U0_out_6_din;
wire    conv3_U0_out_6_write;
wire   [31:0] conv3_U0_out_7_din;
wire    conv3_U0_out_7_write;
wire    conv3_U0_p2_0_read;
wire    conv3_U0_p2_1_read;
wire    conv3_U0_p2_2_read;
wire    conv3_U0_p2_3_read;
wire    conv3_U0_p2_4_read;
wire    conv3_U0_p2_5_read;
wire    conv3_U0_p2_6_read;
wire    conv3_U0_p2_7_read;
wire    conv4_U0_ap_start;
wire    conv4_U0_ap_done;
wire    conv4_U0_ap_continue;
wire    conv4_U0_ap_idle;
wire    conv4_U0_ap_ready;
wire    conv4_U0_start_out;
wire    conv4_U0_start_write;
wire   [31:0] conv4_U0_out_0_din;
wire    conv4_U0_out_0_write;
wire   [31:0] conv4_U0_out_1_din;
wire    conv4_U0_out_1_write;
wire   [31:0] conv4_U0_out_2_din;
wire    conv4_U0_out_2_write;
wire   [31:0] conv4_U0_out_3_din;
wire    conv4_U0_out_3_write;
wire   [31:0] conv4_U0_out_4_din;
wire    conv4_U0_out_4_write;
wire   [31:0] conv4_U0_out_5_din;
wire    conv4_U0_out_5_write;
wire   [31:0] conv4_U0_out_6_din;
wire    conv4_U0_out_6_write;
wire   [31:0] conv4_U0_out_7_din;
wire    conv4_U0_out_7_write;
wire    conv4_U0_f3_0_read;
wire    conv4_U0_f3_1_read;
wire    conv4_U0_f3_2_read;
wire    conv4_U0_f3_3_read;
wire    conv4_U0_f3_4_read;
wire    conv4_U0_f3_5_read;
wire    conv4_U0_f3_6_read;
wire    conv4_U0_f3_7_read;
wire    conv5_U0_ap_start;
wire    conv5_U0_ap_done;
wire    conv5_U0_ap_continue;
wire    conv5_U0_ap_idle;
wire    conv5_U0_ap_ready;
wire    conv5_U0_start_out;
wire    conv5_U0_start_write;
wire   [31:0] conv5_U0_out_0_din;
wire    conv5_U0_out_0_write;
wire   [31:0] conv5_U0_out_1_din;
wire    conv5_U0_out_1_write;
wire   [31:0] conv5_U0_out_2_din;
wire    conv5_U0_out_2_write;
wire   [31:0] conv5_U0_out_3_din;
wire    conv5_U0_out_3_write;
wire   [31:0] conv5_U0_out_4_din;
wire    conv5_U0_out_4_write;
wire   [31:0] conv5_U0_out_5_din;
wire    conv5_U0_out_5_write;
wire   [31:0] conv5_U0_out_6_din;
wire    conv5_U0_out_6_write;
wire   [31:0] conv5_U0_out_7_din;
wire    conv5_U0_out_7_write;
wire    conv5_U0_f4_0_read;
wire    conv5_U0_f4_1_read;
wire    conv5_U0_f4_2_read;
wire    conv5_U0_f4_3_read;
wire    conv5_U0_f4_4_read;
wire    conv5_U0_f4_5_read;
wire    conv5_U0_f4_6_read;
wire    conv5_U0_f4_7_read;
wire    detection_head_U0_ap_start;
wire    detection_head_U0_ap_done;
wire    detection_head_U0_ap_continue;
wire    detection_head_U0_ap_idle;
wire    detection_head_U0_ap_ready;
wire   [9:0] detection_head_U0_out_r_address0;
wire    detection_head_U0_out_r_ce0;
wire    detection_head_U0_out_r_we0;
wire   [31:0] detection_head_U0_out_r_d0;
wire    detection_head_U0_f5_0_read;
wire    detection_head_U0_f5_1_read;
wire    detection_head_U0_f5_2_read;
wire    detection_head_U0_f5_3_read;
wire    detection_head_U0_f5_4_read;
wire    detection_head_U0_f5_5_read;
wire    detection_head_U0_f5_6_read;
wire    detection_head_U0_f5_7_read;
wire    ap_sync_continue;
wire    f1_0_local_channel_full_n;
wire   [31:0] f1_0_local_channel_dout;
wire    f1_0_local_channel_empty_n;
wire    f1_1_local_channel_full_n;
wire   [31:0] f1_1_local_channel_dout;
wire    f1_1_local_channel_empty_n;
wire    f1_2_local_channel_full_n;
wire   [31:0] f1_2_local_channel_dout;
wire    f1_2_local_channel_empty_n;
wire    f1_3_local_channel_full_n;
wire   [31:0] f1_3_local_channel_dout;
wire    f1_3_local_channel_empty_n;
wire    f1_4_local_channel_full_n;
wire   [31:0] f1_4_local_channel_dout;
wire    f1_4_local_channel_empty_n;
wire    f1_5_local_channel_full_n;
wire   [31:0] f1_5_local_channel_dout;
wire    f1_5_local_channel_empty_n;
wire    f1_6_local_channel_full_n;
wire   [31:0] f1_6_local_channel_dout;
wire    f1_6_local_channel_empty_n;
wire    f1_7_local_channel_full_n;
wire   [31:0] f1_7_local_channel_dout;
wire    f1_7_local_channel_empty_n;
wire    p1_0_local_channel_full_n;
wire   [31:0] p1_0_local_channel_dout;
wire    p1_0_local_channel_empty_n;
wire    p1_1_local_channel_full_n;
wire   [31:0] p1_1_local_channel_dout;
wire    p1_1_local_channel_empty_n;
wire    p1_2_local_channel_full_n;
wire   [31:0] p1_2_local_channel_dout;
wire    p1_2_local_channel_empty_n;
wire    p1_3_local_channel_full_n;
wire   [31:0] p1_3_local_channel_dout;
wire    p1_3_local_channel_empty_n;
wire    p1_4_local_channel_full_n;
wire   [31:0] p1_4_local_channel_dout;
wire    p1_4_local_channel_empty_n;
wire    p1_5_local_channel_full_n;
wire   [31:0] p1_5_local_channel_dout;
wire    p1_5_local_channel_empty_n;
wire    p1_6_local_channel_full_n;
wire   [31:0] p1_6_local_channel_dout;
wire    p1_6_local_channel_empty_n;
wire    p1_7_local_channel_full_n;
wire   [31:0] p1_7_local_channel_dout;
wire    p1_7_local_channel_empty_n;
wire    f2_0_local_channel_full_n;
wire   [31:0] f2_0_local_channel_dout;
wire    f2_0_local_channel_empty_n;
wire    f2_1_local_channel_full_n;
wire   [31:0] f2_1_local_channel_dout;
wire    f2_1_local_channel_empty_n;
wire    f2_2_local_channel_full_n;
wire   [31:0] f2_2_local_channel_dout;
wire    f2_2_local_channel_empty_n;
wire    f2_3_local_channel_full_n;
wire   [31:0] f2_3_local_channel_dout;
wire    f2_3_local_channel_empty_n;
wire    f2_4_local_channel_full_n;
wire   [31:0] f2_4_local_channel_dout;
wire    f2_4_local_channel_empty_n;
wire    f2_5_local_channel_full_n;
wire   [31:0] f2_5_local_channel_dout;
wire    f2_5_local_channel_empty_n;
wire    f2_6_local_channel_full_n;
wire   [31:0] f2_6_local_channel_dout;
wire    f2_6_local_channel_empty_n;
wire    f2_7_local_channel_full_n;
wire   [31:0] f2_7_local_channel_dout;
wire    f2_7_local_channel_empty_n;
wire    p2_0_local_channel_full_n;
wire   [31:0] p2_0_local_channel_dout;
wire    p2_0_local_channel_empty_n;
wire    p2_1_local_channel_full_n;
wire   [31:0] p2_1_local_channel_dout;
wire    p2_1_local_channel_empty_n;
wire    p2_2_local_channel_full_n;
wire   [31:0] p2_2_local_channel_dout;
wire    p2_2_local_channel_empty_n;
wire    p2_3_local_channel_full_n;
wire   [31:0] p2_3_local_channel_dout;
wire    p2_3_local_channel_empty_n;
wire    p2_4_local_channel_full_n;
wire   [31:0] p2_4_local_channel_dout;
wire    p2_4_local_channel_empty_n;
wire    p2_5_local_channel_full_n;
wire   [31:0] p2_5_local_channel_dout;
wire    p2_5_local_channel_empty_n;
wire    p2_6_local_channel_full_n;
wire   [31:0] p2_6_local_channel_dout;
wire    p2_6_local_channel_empty_n;
wire    p2_7_local_channel_full_n;
wire   [31:0] p2_7_local_channel_dout;
wire    p2_7_local_channel_empty_n;
wire    f3_0_local_channel_full_n;
wire   [31:0] f3_0_local_channel_dout;
wire    f3_0_local_channel_empty_n;
wire    f3_1_local_channel_full_n;
wire   [31:0] f3_1_local_channel_dout;
wire    f3_1_local_channel_empty_n;
wire    f3_2_local_channel_full_n;
wire   [31:0] f3_2_local_channel_dout;
wire    f3_2_local_channel_empty_n;
wire    f3_3_local_channel_full_n;
wire   [31:0] f3_3_local_channel_dout;
wire    f3_3_local_channel_empty_n;
wire    f3_4_local_channel_full_n;
wire   [31:0] f3_4_local_channel_dout;
wire    f3_4_local_channel_empty_n;
wire    f3_5_local_channel_full_n;
wire   [31:0] f3_5_local_channel_dout;
wire    f3_5_local_channel_empty_n;
wire    f3_6_local_channel_full_n;
wire   [31:0] f3_6_local_channel_dout;
wire    f3_6_local_channel_empty_n;
wire    f3_7_local_channel_full_n;
wire   [31:0] f3_7_local_channel_dout;
wire    f3_7_local_channel_empty_n;
wire    f4_0_local_channel_full_n;
wire   [31:0] f4_0_local_channel_dout;
wire    f4_0_local_channel_empty_n;
wire    f4_1_local_channel_full_n;
wire   [31:0] f4_1_local_channel_dout;
wire    f4_1_local_channel_empty_n;
wire    f4_2_local_channel_full_n;
wire   [31:0] f4_2_local_channel_dout;
wire    f4_2_local_channel_empty_n;
wire    f4_3_local_channel_full_n;
wire   [31:0] f4_3_local_channel_dout;
wire    f4_3_local_channel_empty_n;
wire    f4_4_local_channel_full_n;
wire   [31:0] f4_4_local_channel_dout;
wire    f4_4_local_channel_empty_n;
wire    f4_5_local_channel_full_n;
wire   [31:0] f4_5_local_channel_dout;
wire    f4_5_local_channel_empty_n;
wire    f4_6_local_channel_full_n;
wire   [31:0] f4_6_local_channel_dout;
wire    f4_6_local_channel_empty_n;
wire    f4_7_local_channel_full_n;
wire   [31:0] f4_7_local_channel_dout;
wire    f4_7_local_channel_empty_n;
wire    f5_0_local_channel_full_n;
wire   [31:0] f5_0_local_channel_dout;
wire    f5_0_local_channel_empty_n;
wire    f5_1_local_channel_full_n;
wire   [31:0] f5_1_local_channel_dout;
wire    f5_1_local_channel_empty_n;
wire    f5_2_local_channel_full_n;
wire   [31:0] f5_2_local_channel_dout;
wire    f5_2_local_channel_empty_n;
wire    f5_3_local_channel_full_n;
wire   [31:0] f5_3_local_channel_dout;
wire    f5_3_local_channel_empty_n;
wire    f5_4_local_channel_full_n;
wire   [31:0] f5_4_local_channel_dout;
wire    f5_4_local_channel_empty_n;
wire    f5_5_local_channel_full_n;
wire   [31:0] f5_5_local_channel_dout;
wire    f5_5_local_channel_empty_n;
wire    f5_6_local_channel_full_n;
wire   [31:0] f5_6_local_channel_dout;
wire    f5_6_local_channel_empty_n;
wire    f5_7_local_channel_full_n;
wire   [31:0] f5_7_local_channel_dout;
wire    f5_7_local_channel_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_maxpool1_U0_din;
wire    start_for_maxpool1_U0_full_n;
wire   [0:0] start_for_maxpool1_U0_dout;
wire    start_for_maxpool1_U0_empty_n;
wire   [0:0] start_for_conv2_U0_din;
wire    start_for_conv2_U0_full_n;
wire   [0:0] start_for_conv2_U0_dout;
wire    start_for_conv2_U0_empty_n;
wire   [0:0] start_for_maxpool2_U0_din;
wire    start_for_maxpool2_U0_full_n;
wire   [0:0] start_for_maxpool2_U0_dout;
wire    start_for_maxpool2_U0_empty_n;
wire   [0:0] start_for_conv3_U0_din;
wire    start_for_conv3_U0_full_n;
wire   [0:0] start_for_conv3_U0_dout;
wire    start_for_conv3_U0_empty_n;
wire   [0:0] start_for_conv4_U0_din;
wire    start_for_conv4_U0_full_n;
wire   [0:0] start_for_conv4_U0_dout;
wire    start_for_conv4_U0_empty_n;
wire   [0:0] start_for_conv5_U0_din;
wire    start_for_conv5_U0_full_n;
wire   [0:0] start_for_conv5_U0_dout;
wire    start_for_conv5_U0_empty_n;
wire   [0:0] start_for_detection_head_U0_din;
wire    start_for_detection_head_U0_full_n;
wire   [0:0] start_for_detection_head_U0_dout;
wire    start_for_detection_head_U0_empty_n;
wire    detection_head_U0_start_full_n;
wire    detection_head_U0_start_write;

conv1 conv1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv1_U0_ap_start),
    .start_full_n(start_for_maxpool1_U0_full_n),
    .ap_done(conv1_U0_ap_done),
    .ap_continue(conv1_U0_ap_continue),
    .ap_idle(conv1_U0_ap_idle),
    .ap_ready(conv1_U0_ap_ready),
    .start_out(conv1_U0_start_out),
    .start_write(conv1_U0_start_write),
    .in_r_address0(conv1_U0_in_r_address0),
    .in_r_ce0(conv1_U0_in_r_ce0),
    .in_r_q0(image_r_q0),
    .out_0_din(conv1_U0_out_0_din),
    .out_0_full_n(f1_0_local_channel_full_n),
    .out_0_write(conv1_U0_out_0_write),
    .out_1_din(conv1_U0_out_1_din),
    .out_1_full_n(f1_1_local_channel_full_n),
    .out_1_write(conv1_U0_out_1_write),
    .out_2_din(conv1_U0_out_2_din),
    .out_2_full_n(f1_2_local_channel_full_n),
    .out_2_write(conv1_U0_out_2_write),
    .out_3_din(conv1_U0_out_3_din),
    .out_3_full_n(f1_3_local_channel_full_n),
    .out_3_write(conv1_U0_out_3_write),
    .out_4_din(conv1_U0_out_4_din),
    .out_4_full_n(f1_4_local_channel_full_n),
    .out_4_write(conv1_U0_out_4_write),
    .out_5_din(conv1_U0_out_5_din),
    .out_5_full_n(f1_5_local_channel_full_n),
    .out_5_write(conv1_U0_out_5_write),
    .out_6_din(conv1_U0_out_6_din),
    .out_6_full_n(f1_6_local_channel_full_n),
    .out_6_write(conv1_U0_out_6_write),
    .out_7_din(conv1_U0_out_7_din),
    .out_7_full_n(f1_7_local_channel_full_n),
    .out_7_write(conv1_U0_out_7_write)
);

maxpool1 maxpool1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(maxpool1_U0_ap_start),
    .start_full_n(start_for_conv2_U0_full_n),
    .ap_done(maxpool1_U0_ap_done),
    .ap_continue(maxpool1_U0_ap_continue),
    .ap_idle(maxpool1_U0_ap_idle),
    .ap_ready(maxpool1_U0_ap_ready),
    .start_out(maxpool1_U0_start_out),
    .start_write(maxpool1_U0_start_write),
    .out_0_din(maxpool1_U0_out_0_din),
    .out_0_full_n(p1_0_local_channel_full_n),
    .out_0_write(maxpool1_U0_out_0_write),
    .out_1_din(maxpool1_U0_out_1_din),
    .out_1_full_n(p1_1_local_channel_full_n),
    .out_1_write(maxpool1_U0_out_1_write),
    .out_2_din(maxpool1_U0_out_2_din),
    .out_2_full_n(p1_2_local_channel_full_n),
    .out_2_write(maxpool1_U0_out_2_write),
    .out_3_din(maxpool1_U0_out_3_din),
    .out_3_full_n(p1_3_local_channel_full_n),
    .out_3_write(maxpool1_U0_out_3_write),
    .out_4_din(maxpool1_U0_out_4_din),
    .out_4_full_n(p1_4_local_channel_full_n),
    .out_4_write(maxpool1_U0_out_4_write),
    .out_5_din(maxpool1_U0_out_5_din),
    .out_5_full_n(p1_5_local_channel_full_n),
    .out_5_write(maxpool1_U0_out_5_write),
    .out_6_din(maxpool1_U0_out_6_din),
    .out_6_full_n(p1_6_local_channel_full_n),
    .out_6_write(maxpool1_U0_out_6_write),
    .out_7_din(maxpool1_U0_out_7_din),
    .out_7_full_n(p1_7_local_channel_full_n),
    .out_7_write(maxpool1_U0_out_7_write),
    .f1_0_dout(f1_0_local_channel_dout),
    .f1_0_empty_n(f1_0_local_channel_empty_n),
    .f1_0_read(maxpool1_U0_f1_0_read),
    .f1_1_dout(f1_1_local_channel_dout),
    .f1_1_empty_n(f1_1_local_channel_empty_n),
    .f1_1_read(maxpool1_U0_f1_1_read),
    .f1_2_dout(f1_2_local_channel_dout),
    .f1_2_empty_n(f1_2_local_channel_empty_n),
    .f1_2_read(maxpool1_U0_f1_2_read),
    .f1_3_dout(f1_3_local_channel_dout),
    .f1_3_empty_n(f1_3_local_channel_empty_n),
    .f1_3_read(maxpool1_U0_f1_3_read),
    .f1_4_dout(f1_4_local_channel_dout),
    .f1_4_empty_n(f1_4_local_channel_empty_n),
    .f1_4_read(maxpool1_U0_f1_4_read),
    .f1_5_dout(f1_5_local_channel_dout),
    .f1_5_empty_n(f1_5_local_channel_empty_n),
    .f1_5_read(maxpool1_U0_f1_5_read),
    .f1_6_dout(f1_6_local_channel_dout),
    .f1_6_empty_n(f1_6_local_channel_empty_n),
    .f1_6_read(maxpool1_U0_f1_6_read),
    .f1_7_dout(f1_7_local_channel_dout),
    .f1_7_empty_n(f1_7_local_channel_empty_n),
    .f1_7_read(maxpool1_U0_f1_7_read)
);

conv2 conv2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv2_U0_ap_start),
    .start_full_n(start_for_maxpool2_U0_full_n),
    .ap_done(conv2_U0_ap_done),
    .ap_continue(conv2_U0_ap_continue),
    .ap_idle(conv2_U0_ap_idle),
    .ap_ready(conv2_U0_ap_ready),
    .start_out(conv2_U0_start_out),
    .start_write(conv2_U0_start_write),
    .out_0_din(conv2_U0_out_0_din),
    .out_0_full_n(f2_0_local_channel_full_n),
    .out_0_write(conv2_U0_out_0_write),
    .out_1_din(conv2_U0_out_1_din),
    .out_1_full_n(f2_1_local_channel_full_n),
    .out_1_write(conv2_U0_out_1_write),
    .out_2_din(conv2_U0_out_2_din),
    .out_2_full_n(f2_2_local_channel_full_n),
    .out_2_write(conv2_U0_out_2_write),
    .out_3_din(conv2_U0_out_3_din),
    .out_3_full_n(f2_3_local_channel_full_n),
    .out_3_write(conv2_U0_out_3_write),
    .out_4_din(conv2_U0_out_4_din),
    .out_4_full_n(f2_4_local_channel_full_n),
    .out_4_write(conv2_U0_out_4_write),
    .out_5_din(conv2_U0_out_5_din),
    .out_5_full_n(f2_5_local_channel_full_n),
    .out_5_write(conv2_U0_out_5_write),
    .out_6_din(conv2_U0_out_6_din),
    .out_6_full_n(f2_6_local_channel_full_n),
    .out_6_write(conv2_U0_out_6_write),
    .out_7_din(conv2_U0_out_7_din),
    .out_7_full_n(f2_7_local_channel_full_n),
    .out_7_write(conv2_U0_out_7_write),
    .p1_0_dout(p1_0_local_channel_dout),
    .p1_0_empty_n(p1_0_local_channel_empty_n),
    .p1_0_read(conv2_U0_p1_0_read),
    .p1_1_dout(p1_1_local_channel_dout),
    .p1_1_empty_n(p1_1_local_channel_empty_n),
    .p1_1_read(conv2_U0_p1_1_read),
    .p1_2_dout(p1_2_local_channel_dout),
    .p1_2_empty_n(p1_2_local_channel_empty_n),
    .p1_2_read(conv2_U0_p1_2_read),
    .p1_3_dout(p1_3_local_channel_dout),
    .p1_3_empty_n(p1_3_local_channel_empty_n),
    .p1_3_read(conv2_U0_p1_3_read),
    .p1_4_dout(p1_4_local_channel_dout),
    .p1_4_empty_n(p1_4_local_channel_empty_n),
    .p1_4_read(conv2_U0_p1_4_read),
    .p1_5_dout(p1_5_local_channel_dout),
    .p1_5_empty_n(p1_5_local_channel_empty_n),
    .p1_5_read(conv2_U0_p1_5_read),
    .p1_6_dout(p1_6_local_channel_dout),
    .p1_6_empty_n(p1_6_local_channel_empty_n),
    .p1_6_read(conv2_U0_p1_6_read),
    .p1_7_dout(p1_7_local_channel_dout),
    .p1_7_empty_n(p1_7_local_channel_empty_n),
    .p1_7_read(conv2_U0_p1_7_read)
);

maxpool2 maxpool2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(maxpool2_U0_ap_start),
    .start_full_n(start_for_conv3_U0_full_n),
    .ap_done(maxpool2_U0_ap_done),
    .ap_continue(maxpool2_U0_ap_continue),
    .ap_idle(maxpool2_U0_ap_idle),
    .ap_ready(maxpool2_U0_ap_ready),
    .start_out(maxpool2_U0_start_out),
    .start_write(maxpool2_U0_start_write),
    .out_0_din(maxpool2_U0_out_0_din),
    .out_0_full_n(p2_0_local_channel_full_n),
    .out_0_write(maxpool2_U0_out_0_write),
    .out_1_din(maxpool2_U0_out_1_din),
    .out_1_full_n(p2_1_local_channel_full_n),
    .out_1_write(maxpool2_U0_out_1_write),
    .out_2_din(maxpool2_U0_out_2_din),
    .out_2_full_n(p2_2_local_channel_full_n),
    .out_2_write(maxpool2_U0_out_2_write),
    .out_3_din(maxpool2_U0_out_3_din),
    .out_3_full_n(p2_3_local_channel_full_n),
    .out_3_write(maxpool2_U0_out_3_write),
    .out_4_din(maxpool2_U0_out_4_din),
    .out_4_full_n(p2_4_local_channel_full_n),
    .out_4_write(maxpool2_U0_out_4_write),
    .out_5_din(maxpool2_U0_out_5_din),
    .out_5_full_n(p2_5_local_channel_full_n),
    .out_5_write(maxpool2_U0_out_5_write),
    .out_6_din(maxpool2_U0_out_6_din),
    .out_6_full_n(p2_6_local_channel_full_n),
    .out_6_write(maxpool2_U0_out_6_write),
    .out_7_din(maxpool2_U0_out_7_din),
    .out_7_full_n(p2_7_local_channel_full_n),
    .out_7_write(maxpool2_U0_out_7_write),
    .f2_0_dout(f2_0_local_channel_dout),
    .f2_0_empty_n(f2_0_local_channel_empty_n),
    .f2_0_read(maxpool2_U0_f2_0_read),
    .f2_1_dout(f2_1_local_channel_dout),
    .f2_1_empty_n(f2_1_local_channel_empty_n),
    .f2_1_read(maxpool2_U0_f2_1_read),
    .f2_2_dout(f2_2_local_channel_dout),
    .f2_2_empty_n(f2_2_local_channel_empty_n),
    .f2_2_read(maxpool2_U0_f2_2_read),
    .f2_3_dout(f2_3_local_channel_dout),
    .f2_3_empty_n(f2_3_local_channel_empty_n),
    .f2_3_read(maxpool2_U0_f2_3_read),
    .f2_4_dout(f2_4_local_channel_dout),
    .f2_4_empty_n(f2_4_local_channel_empty_n),
    .f2_4_read(maxpool2_U0_f2_4_read),
    .f2_5_dout(f2_5_local_channel_dout),
    .f2_5_empty_n(f2_5_local_channel_empty_n),
    .f2_5_read(maxpool2_U0_f2_5_read),
    .f2_6_dout(f2_6_local_channel_dout),
    .f2_6_empty_n(f2_6_local_channel_empty_n),
    .f2_6_read(maxpool2_U0_f2_6_read),
    .f2_7_dout(f2_7_local_channel_dout),
    .f2_7_empty_n(f2_7_local_channel_empty_n),
    .f2_7_read(maxpool2_U0_f2_7_read)
);

conv3 conv3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv3_U0_ap_start),
    .start_full_n(start_for_conv4_U0_full_n),
    .ap_done(conv3_U0_ap_done),
    .ap_continue(conv3_U0_ap_continue),
    .ap_idle(conv3_U0_ap_idle),
    .ap_ready(conv3_U0_ap_ready),
    .start_out(conv3_U0_start_out),
    .start_write(conv3_U0_start_write),
    .out_0_din(conv3_U0_out_0_din),
    .out_0_full_n(f3_0_local_channel_full_n),
    .out_0_write(conv3_U0_out_0_write),
    .out_1_din(conv3_U0_out_1_din),
    .out_1_full_n(f3_1_local_channel_full_n),
    .out_1_write(conv3_U0_out_1_write),
    .out_2_din(conv3_U0_out_2_din),
    .out_2_full_n(f3_2_local_channel_full_n),
    .out_2_write(conv3_U0_out_2_write),
    .out_3_din(conv3_U0_out_3_din),
    .out_3_full_n(f3_3_local_channel_full_n),
    .out_3_write(conv3_U0_out_3_write),
    .out_4_din(conv3_U0_out_4_din),
    .out_4_full_n(f3_4_local_channel_full_n),
    .out_4_write(conv3_U0_out_4_write),
    .out_5_din(conv3_U0_out_5_din),
    .out_5_full_n(f3_5_local_channel_full_n),
    .out_5_write(conv3_U0_out_5_write),
    .out_6_din(conv3_U0_out_6_din),
    .out_6_full_n(f3_6_local_channel_full_n),
    .out_6_write(conv3_U0_out_6_write),
    .out_7_din(conv3_U0_out_7_din),
    .out_7_full_n(f3_7_local_channel_full_n),
    .out_7_write(conv3_U0_out_7_write),
    .p2_0_dout(p2_0_local_channel_dout),
    .p2_0_empty_n(p2_0_local_channel_empty_n),
    .p2_0_read(conv3_U0_p2_0_read),
    .p2_1_dout(p2_1_local_channel_dout),
    .p2_1_empty_n(p2_1_local_channel_empty_n),
    .p2_1_read(conv3_U0_p2_1_read),
    .p2_2_dout(p2_2_local_channel_dout),
    .p2_2_empty_n(p2_2_local_channel_empty_n),
    .p2_2_read(conv3_U0_p2_2_read),
    .p2_3_dout(p2_3_local_channel_dout),
    .p2_3_empty_n(p2_3_local_channel_empty_n),
    .p2_3_read(conv3_U0_p2_3_read),
    .p2_4_dout(p2_4_local_channel_dout),
    .p2_4_empty_n(p2_4_local_channel_empty_n),
    .p2_4_read(conv3_U0_p2_4_read),
    .p2_5_dout(p2_5_local_channel_dout),
    .p2_5_empty_n(p2_5_local_channel_empty_n),
    .p2_5_read(conv3_U0_p2_5_read),
    .p2_6_dout(p2_6_local_channel_dout),
    .p2_6_empty_n(p2_6_local_channel_empty_n),
    .p2_6_read(conv3_U0_p2_6_read),
    .p2_7_dout(p2_7_local_channel_dout),
    .p2_7_empty_n(p2_7_local_channel_empty_n),
    .p2_7_read(conv3_U0_p2_7_read)
);

conv4 conv4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv4_U0_ap_start),
    .start_full_n(start_for_conv5_U0_full_n),
    .ap_done(conv4_U0_ap_done),
    .ap_continue(conv4_U0_ap_continue),
    .ap_idle(conv4_U0_ap_idle),
    .ap_ready(conv4_U0_ap_ready),
    .start_out(conv4_U0_start_out),
    .start_write(conv4_U0_start_write),
    .out_0_din(conv4_U0_out_0_din),
    .out_0_full_n(f4_0_local_channel_full_n),
    .out_0_write(conv4_U0_out_0_write),
    .out_1_din(conv4_U0_out_1_din),
    .out_1_full_n(f4_1_local_channel_full_n),
    .out_1_write(conv4_U0_out_1_write),
    .out_2_din(conv4_U0_out_2_din),
    .out_2_full_n(f4_2_local_channel_full_n),
    .out_2_write(conv4_U0_out_2_write),
    .out_3_din(conv4_U0_out_3_din),
    .out_3_full_n(f4_3_local_channel_full_n),
    .out_3_write(conv4_U0_out_3_write),
    .out_4_din(conv4_U0_out_4_din),
    .out_4_full_n(f4_4_local_channel_full_n),
    .out_4_write(conv4_U0_out_4_write),
    .out_5_din(conv4_U0_out_5_din),
    .out_5_full_n(f4_5_local_channel_full_n),
    .out_5_write(conv4_U0_out_5_write),
    .out_6_din(conv4_U0_out_6_din),
    .out_6_full_n(f4_6_local_channel_full_n),
    .out_6_write(conv4_U0_out_6_write),
    .out_7_din(conv4_U0_out_7_din),
    .out_7_full_n(f4_7_local_channel_full_n),
    .out_7_write(conv4_U0_out_7_write),
    .f3_0_dout(f3_0_local_channel_dout),
    .f3_0_empty_n(f3_0_local_channel_empty_n),
    .f3_0_read(conv4_U0_f3_0_read),
    .f3_1_dout(f3_1_local_channel_dout),
    .f3_1_empty_n(f3_1_local_channel_empty_n),
    .f3_1_read(conv4_U0_f3_1_read),
    .f3_2_dout(f3_2_local_channel_dout),
    .f3_2_empty_n(f3_2_local_channel_empty_n),
    .f3_2_read(conv4_U0_f3_2_read),
    .f3_3_dout(f3_3_local_channel_dout),
    .f3_3_empty_n(f3_3_local_channel_empty_n),
    .f3_3_read(conv4_U0_f3_3_read),
    .f3_4_dout(f3_4_local_channel_dout),
    .f3_4_empty_n(f3_4_local_channel_empty_n),
    .f3_4_read(conv4_U0_f3_4_read),
    .f3_5_dout(f3_5_local_channel_dout),
    .f3_5_empty_n(f3_5_local_channel_empty_n),
    .f3_5_read(conv4_U0_f3_5_read),
    .f3_6_dout(f3_6_local_channel_dout),
    .f3_6_empty_n(f3_6_local_channel_empty_n),
    .f3_6_read(conv4_U0_f3_6_read),
    .f3_7_dout(f3_7_local_channel_dout),
    .f3_7_empty_n(f3_7_local_channel_empty_n),
    .f3_7_read(conv4_U0_f3_7_read)
);

conv5 conv5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv5_U0_ap_start),
    .start_full_n(start_for_detection_head_U0_full_n),
    .ap_done(conv5_U0_ap_done),
    .ap_continue(conv5_U0_ap_continue),
    .ap_idle(conv5_U0_ap_idle),
    .ap_ready(conv5_U0_ap_ready),
    .start_out(conv5_U0_start_out),
    .start_write(conv5_U0_start_write),
    .out_0_din(conv5_U0_out_0_din),
    .out_0_full_n(f5_0_local_channel_full_n),
    .out_0_write(conv5_U0_out_0_write),
    .out_1_din(conv5_U0_out_1_din),
    .out_1_full_n(f5_1_local_channel_full_n),
    .out_1_write(conv5_U0_out_1_write),
    .out_2_din(conv5_U0_out_2_din),
    .out_2_full_n(f5_2_local_channel_full_n),
    .out_2_write(conv5_U0_out_2_write),
    .out_3_din(conv5_U0_out_3_din),
    .out_3_full_n(f5_3_local_channel_full_n),
    .out_3_write(conv5_U0_out_3_write),
    .out_4_din(conv5_U0_out_4_din),
    .out_4_full_n(f5_4_local_channel_full_n),
    .out_4_write(conv5_U0_out_4_write),
    .out_5_din(conv5_U0_out_5_din),
    .out_5_full_n(f5_5_local_channel_full_n),
    .out_5_write(conv5_U0_out_5_write),
    .out_6_din(conv5_U0_out_6_din),
    .out_6_full_n(f5_6_local_channel_full_n),
    .out_6_write(conv5_U0_out_6_write),
    .out_7_din(conv5_U0_out_7_din),
    .out_7_full_n(f5_7_local_channel_full_n),
    .out_7_write(conv5_U0_out_7_write),
    .f4_0_dout(f4_0_local_channel_dout),
    .f4_0_empty_n(f4_0_local_channel_empty_n),
    .f4_0_read(conv5_U0_f4_0_read),
    .f4_1_dout(f4_1_local_channel_dout),
    .f4_1_empty_n(f4_1_local_channel_empty_n),
    .f4_1_read(conv5_U0_f4_1_read),
    .f4_2_dout(f4_2_local_channel_dout),
    .f4_2_empty_n(f4_2_local_channel_empty_n),
    .f4_2_read(conv5_U0_f4_2_read),
    .f4_3_dout(f4_3_local_channel_dout),
    .f4_3_empty_n(f4_3_local_channel_empty_n),
    .f4_3_read(conv5_U0_f4_3_read),
    .f4_4_dout(f4_4_local_channel_dout),
    .f4_4_empty_n(f4_4_local_channel_empty_n),
    .f4_4_read(conv5_U0_f4_4_read),
    .f4_5_dout(f4_5_local_channel_dout),
    .f4_5_empty_n(f4_5_local_channel_empty_n),
    .f4_5_read(conv5_U0_f4_5_read),
    .f4_6_dout(f4_6_local_channel_dout),
    .f4_6_empty_n(f4_6_local_channel_empty_n),
    .f4_6_read(conv5_U0_f4_6_read),
    .f4_7_dout(f4_7_local_channel_dout),
    .f4_7_empty_n(f4_7_local_channel_empty_n),
    .f4_7_read(conv5_U0_f4_7_read)
);

detection_head detection_head_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(detection_head_U0_ap_start),
    .ap_done(detection_head_U0_ap_done),
    .ap_continue(detection_head_U0_ap_continue),
    .ap_idle(detection_head_U0_ap_idle),
    .ap_ready(detection_head_U0_ap_ready),
    .out_r_address0(detection_head_U0_out_r_address0),
    .out_r_ce0(detection_head_U0_out_r_ce0),
    .out_r_we0(detection_head_U0_out_r_we0),
    .out_r_d0(detection_head_U0_out_r_d0),
    .f5_0_dout(f5_0_local_channel_dout),
    .f5_0_empty_n(f5_0_local_channel_empty_n),
    .f5_0_read(detection_head_U0_f5_0_read),
    .f5_1_dout(f5_1_local_channel_dout),
    .f5_1_empty_n(f5_1_local_channel_empty_n),
    .f5_1_read(detection_head_U0_f5_1_read),
    .f5_2_dout(f5_2_local_channel_dout),
    .f5_2_empty_n(f5_2_local_channel_empty_n),
    .f5_2_read(detection_head_U0_f5_2_read),
    .f5_3_dout(f5_3_local_channel_dout),
    .f5_3_empty_n(f5_3_local_channel_empty_n),
    .f5_3_read(detection_head_U0_f5_3_read),
    .f5_4_dout(f5_4_local_channel_dout),
    .f5_4_empty_n(f5_4_local_channel_empty_n),
    .f5_4_read(detection_head_U0_f5_4_read),
    .f5_5_dout(f5_5_local_channel_dout),
    .f5_5_empty_n(f5_5_local_channel_empty_n),
    .f5_5_read(detection_head_U0_f5_5_read),
    .f5_6_dout(f5_6_local_channel_dout),
    .f5_6_empty_n(f5_6_local_channel_empty_n),
    .f5_6_read(detection_head_U0_f5_6_read),
    .f5_7_dout(f5_7_local_channel_dout),
    .f5_7_empty_n(f5_7_local_channel_empty_n),
    .f5_7_read(detection_head_U0_f5_7_read)
);

fifo_w32_d16_A f1_0_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_0_din),
    .if_full_n(f1_0_local_channel_full_n),
    .if_write(conv1_U0_out_0_write),
    .if_dout(f1_0_local_channel_dout),
    .if_empty_n(f1_0_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_0_read)
);

fifo_w32_d16_A f1_1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_1_din),
    .if_full_n(f1_1_local_channel_full_n),
    .if_write(conv1_U0_out_1_write),
    .if_dout(f1_1_local_channel_dout),
    .if_empty_n(f1_1_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_1_read)
);

fifo_w32_d16_A f1_2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_2_din),
    .if_full_n(f1_2_local_channel_full_n),
    .if_write(conv1_U0_out_2_write),
    .if_dout(f1_2_local_channel_dout),
    .if_empty_n(f1_2_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_2_read)
);

fifo_w32_d16_A f1_3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_3_din),
    .if_full_n(f1_3_local_channel_full_n),
    .if_write(conv1_U0_out_3_write),
    .if_dout(f1_3_local_channel_dout),
    .if_empty_n(f1_3_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_3_read)
);

fifo_w32_d16_A f1_4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_4_din),
    .if_full_n(f1_4_local_channel_full_n),
    .if_write(conv1_U0_out_4_write),
    .if_dout(f1_4_local_channel_dout),
    .if_empty_n(f1_4_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_4_read)
);

fifo_w32_d16_A f1_5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_5_din),
    .if_full_n(f1_5_local_channel_full_n),
    .if_write(conv1_U0_out_5_write),
    .if_dout(f1_5_local_channel_dout),
    .if_empty_n(f1_5_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_5_read)
);

fifo_w32_d16_A f1_6_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_6_din),
    .if_full_n(f1_6_local_channel_full_n),
    .if_write(conv1_U0_out_6_write),
    .if_dout(f1_6_local_channel_dout),
    .if_empty_n(f1_6_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_6_read)
);

fifo_w32_d16_A f1_7_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_7_din),
    .if_full_n(f1_7_local_channel_full_n),
    .if_write(conv1_U0_out_7_write),
    .if_dout(f1_7_local_channel_dout),
    .if_empty_n(f1_7_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_7_read)
);

fifo_w32_d16_A p1_0_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_0_din),
    .if_full_n(p1_0_local_channel_full_n),
    .if_write(maxpool1_U0_out_0_write),
    .if_dout(p1_0_local_channel_dout),
    .if_empty_n(p1_0_local_channel_empty_n),
    .if_read(conv2_U0_p1_0_read)
);

fifo_w32_d16_A p1_1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_1_din),
    .if_full_n(p1_1_local_channel_full_n),
    .if_write(maxpool1_U0_out_1_write),
    .if_dout(p1_1_local_channel_dout),
    .if_empty_n(p1_1_local_channel_empty_n),
    .if_read(conv2_U0_p1_1_read)
);

fifo_w32_d16_A p1_2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_2_din),
    .if_full_n(p1_2_local_channel_full_n),
    .if_write(maxpool1_U0_out_2_write),
    .if_dout(p1_2_local_channel_dout),
    .if_empty_n(p1_2_local_channel_empty_n),
    .if_read(conv2_U0_p1_2_read)
);

fifo_w32_d16_A p1_3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_3_din),
    .if_full_n(p1_3_local_channel_full_n),
    .if_write(maxpool1_U0_out_3_write),
    .if_dout(p1_3_local_channel_dout),
    .if_empty_n(p1_3_local_channel_empty_n),
    .if_read(conv2_U0_p1_3_read)
);

fifo_w32_d16_A p1_4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_4_din),
    .if_full_n(p1_4_local_channel_full_n),
    .if_write(maxpool1_U0_out_4_write),
    .if_dout(p1_4_local_channel_dout),
    .if_empty_n(p1_4_local_channel_empty_n),
    .if_read(conv2_U0_p1_4_read)
);

fifo_w32_d16_A p1_5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_5_din),
    .if_full_n(p1_5_local_channel_full_n),
    .if_write(maxpool1_U0_out_5_write),
    .if_dout(p1_5_local_channel_dout),
    .if_empty_n(p1_5_local_channel_empty_n),
    .if_read(conv2_U0_p1_5_read)
);

fifo_w32_d16_A p1_6_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_6_din),
    .if_full_n(p1_6_local_channel_full_n),
    .if_write(maxpool1_U0_out_6_write),
    .if_dout(p1_6_local_channel_dout),
    .if_empty_n(p1_6_local_channel_empty_n),
    .if_read(conv2_U0_p1_6_read)
);

fifo_w32_d16_A p1_7_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_7_din),
    .if_full_n(p1_7_local_channel_full_n),
    .if_write(maxpool1_U0_out_7_write),
    .if_dout(p1_7_local_channel_dout),
    .if_empty_n(p1_7_local_channel_empty_n),
    .if_read(conv2_U0_p1_7_read)
);

fifo_w32_d16_A f2_0_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_0_din),
    .if_full_n(f2_0_local_channel_full_n),
    .if_write(conv2_U0_out_0_write),
    .if_dout(f2_0_local_channel_dout),
    .if_empty_n(f2_0_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_0_read)
);

fifo_w32_d16_A f2_1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_1_din),
    .if_full_n(f2_1_local_channel_full_n),
    .if_write(conv2_U0_out_1_write),
    .if_dout(f2_1_local_channel_dout),
    .if_empty_n(f2_1_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_1_read)
);

fifo_w32_d16_A f2_2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_2_din),
    .if_full_n(f2_2_local_channel_full_n),
    .if_write(conv2_U0_out_2_write),
    .if_dout(f2_2_local_channel_dout),
    .if_empty_n(f2_2_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_2_read)
);

fifo_w32_d16_A f2_3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_3_din),
    .if_full_n(f2_3_local_channel_full_n),
    .if_write(conv2_U0_out_3_write),
    .if_dout(f2_3_local_channel_dout),
    .if_empty_n(f2_3_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_3_read)
);

fifo_w32_d16_A f2_4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_4_din),
    .if_full_n(f2_4_local_channel_full_n),
    .if_write(conv2_U0_out_4_write),
    .if_dout(f2_4_local_channel_dout),
    .if_empty_n(f2_4_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_4_read)
);

fifo_w32_d16_A f2_5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_5_din),
    .if_full_n(f2_5_local_channel_full_n),
    .if_write(conv2_U0_out_5_write),
    .if_dout(f2_5_local_channel_dout),
    .if_empty_n(f2_5_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_5_read)
);

fifo_w32_d16_A f2_6_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_6_din),
    .if_full_n(f2_6_local_channel_full_n),
    .if_write(conv2_U0_out_6_write),
    .if_dout(f2_6_local_channel_dout),
    .if_empty_n(f2_6_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_6_read)
);

fifo_w32_d16_A f2_7_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_7_din),
    .if_full_n(f2_7_local_channel_full_n),
    .if_write(conv2_U0_out_7_write),
    .if_dout(f2_7_local_channel_dout),
    .if_empty_n(f2_7_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_7_read)
);

fifo_w32_d16_A p2_0_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_0_din),
    .if_full_n(p2_0_local_channel_full_n),
    .if_write(maxpool2_U0_out_0_write),
    .if_dout(p2_0_local_channel_dout),
    .if_empty_n(p2_0_local_channel_empty_n),
    .if_read(conv3_U0_p2_0_read)
);

fifo_w32_d16_A p2_1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_1_din),
    .if_full_n(p2_1_local_channel_full_n),
    .if_write(maxpool2_U0_out_1_write),
    .if_dout(p2_1_local_channel_dout),
    .if_empty_n(p2_1_local_channel_empty_n),
    .if_read(conv3_U0_p2_1_read)
);

fifo_w32_d16_A p2_2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_2_din),
    .if_full_n(p2_2_local_channel_full_n),
    .if_write(maxpool2_U0_out_2_write),
    .if_dout(p2_2_local_channel_dout),
    .if_empty_n(p2_2_local_channel_empty_n),
    .if_read(conv3_U0_p2_2_read)
);

fifo_w32_d16_A p2_3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_3_din),
    .if_full_n(p2_3_local_channel_full_n),
    .if_write(maxpool2_U0_out_3_write),
    .if_dout(p2_3_local_channel_dout),
    .if_empty_n(p2_3_local_channel_empty_n),
    .if_read(conv3_U0_p2_3_read)
);

fifo_w32_d16_A p2_4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_4_din),
    .if_full_n(p2_4_local_channel_full_n),
    .if_write(maxpool2_U0_out_4_write),
    .if_dout(p2_4_local_channel_dout),
    .if_empty_n(p2_4_local_channel_empty_n),
    .if_read(conv3_U0_p2_4_read)
);

fifo_w32_d16_A p2_5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_5_din),
    .if_full_n(p2_5_local_channel_full_n),
    .if_write(maxpool2_U0_out_5_write),
    .if_dout(p2_5_local_channel_dout),
    .if_empty_n(p2_5_local_channel_empty_n),
    .if_read(conv3_U0_p2_5_read)
);

fifo_w32_d16_A p2_6_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_6_din),
    .if_full_n(p2_6_local_channel_full_n),
    .if_write(maxpool2_U0_out_6_write),
    .if_dout(p2_6_local_channel_dout),
    .if_empty_n(p2_6_local_channel_empty_n),
    .if_read(conv3_U0_p2_6_read)
);

fifo_w32_d16_A p2_7_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_7_din),
    .if_full_n(p2_7_local_channel_full_n),
    .if_write(maxpool2_U0_out_7_write),
    .if_dout(p2_7_local_channel_dout),
    .if_empty_n(p2_7_local_channel_empty_n),
    .if_read(conv3_U0_p2_7_read)
);

fifo_w32_d16_A f3_0_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_0_din),
    .if_full_n(f3_0_local_channel_full_n),
    .if_write(conv3_U0_out_0_write),
    .if_dout(f3_0_local_channel_dout),
    .if_empty_n(f3_0_local_channel_empty_n),
    .if_read(conv4_U0_f3_0_read)
);

fifo_w32_d16_A f3_1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_1_din),
    .if_full_n(f3_1_local_channel_full_n),
    .if_write(conv3_U0_out_1_write),
    .if_dout(f3_1_local_channel_dout),
    .if_empty_n(f3_1_local_channel_empty_n),
    .if_read(conv4_U0_f3_1_read)
);

fifo_w32_d16_A f3_2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_2_din),
    .if_full_n(f3_2_local_channel_full_n),
    .if_write(conv3_U0_out_2_write),
    .if_dout(f3_2_local_channel_dout),
    .if_empty_n(f3_2_local_channel_empty_n),
    .if_read(conv4_U0_f3_2_read)
);

fifo_w32_d16_A f3_3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_3_din),
    .if_full_n(f3_3_local_channel_full_n),
    .if_write(conv3_U0_out_3_write),
    .if_dout(f3_3_local_channel_dout),
    .if_empty_n(f3_3_local_channel_empty_n),
    .if_read(conv4_U0_f3_3_read)
);

fifo_w32_d16_A f3_4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_4_din),
    .if_full_n(f3_4_local_channel_full_n),
    .if_write(conv3_U0_out_4_write),
    .if_dout(f3_4_local_channel_dout),
    .if_empty_n(f3_4_local_channel_empty_n),
    .if_read(conv4_U0_f3_4_read)
);

fifo_w32_d16_A f3_5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_5_din),
    .if_full_n(f3_5_local_channel_full_n),
    .if_write(conv3_U0_out_5_write),
    .if_dout(f3_5_local_channel_dout),
    .if_empty_n(f3_5_local_channel_empty_n),
    .if_read(conv4_U0_f3_5_read)
);

fifo_w32_d16_A f3_6_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_6_din),
    .if_full_n(f3_6_local_channel_full_n),
    .if_write(conv3_U0_out_6_write),
    .if_dout(f3_6_local_channel_dout),
    .if_empty_n(f3_6_local_channel_empty_n),
    .if_read(conv4_U0_f3_6_read)
);

fifo_w32_d16_A f3_7_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_7_din),
    .if_full_n(f3_7_local_channel_full_n),
    .if_write(conv3_U0_out_7_write),
    .if_dout(f3_7_local_channel_dout),
    .if_empty_n(f3_7_local_channel_empty_n),
    .if_read(conv4_U0_f3_7_read)
);

fifo_w32_d16_A f4_0_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_0_din),
    .if_full_n(f4_0_local_channel_full_n),
    .if_write(conv4_U0_out_0_write),
    .if_dout(f4_0_local_channel_dout),
    .if_empty_n(f4_0_local_channel_empty_n),
    .if_read(conv5_U0_f4_0_read)
);

fifo_w32_d16_A f4_1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_1_din),
    .if_full_n(f4_1_local_channel_full_n),
    .if_write(conv4_U0_out_1_write),
    .if_dout(f4_1_local_channel_dout),
    .if_empty_n(f4_1_local_channel_empty_n),
    .if_read(conv5_U0_f4_1_read)
);

fifo_w32_d16_A f4_2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_2_din),
    .if_full_n(f4_2_local_channel_full_n),
    .if_write(conv4_U0_out_2_write),
    .if_dout(f4_2_local_channel_dout),
    .if_empty_n(f4_2_local_channel_empty_n),
    .if_read(conv5_U0_f4_2_read)
);

fifo_w32_d16_A f4_3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_3_din),
    .if_full_n(f4_3_local_channel_full_n),
    .if_write(conv4_U0_out_3_write),
    .if_dout(f4_3_local_channel_dout),
    .if_empty_n(f4_3_local_channel_empty_n),
    .if_read(conv5_U0_f4_3_read)
);

fifo_w32_d16_A f4_4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_4_din),
    .if_full_n(f4_4_local_channel_full_n),
    .if_write(conv4_U0_out_4_write),
    .if_dout(f4_4_local_channel_dout),
    .if_empty_n(f4_4_local_channel_empty_n),
    .if_read(conv5_U0_f4_4_read)
);

fifo_w32_d16_A f4_5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_5_din),
    .if_full_n(f4_5_local_channel_full_n),
    .if_write(conv4_U0_out_5_write),
    .if_dout(f4_5_local_channel_dout),
    .if_empty_n(f4_5_local_channel_empty_n),
    .if_read(conv5_U0_f4_5_read)
);

fifo_w32_d16_A f4_6_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_6_din),
    .if_full_n(f4_6_local_channel_full_n),
    .if_write(conv4_U0_out_6_write),
    .if_dout(f4_6_local_channel_dout),
    .if_empty_n(f4_6_local_channel_empty_n),
    .if_read(conv5_U0_f4_6_read)
);

fifo_w32_d16_A f4_7_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_7_din),
    .if_full_n(f4_7_local_channel_full_n),
    .if_write(conv4_U0_out_7_write),
    .if_dout(f4_7_local_channel_dout),
    .if_empty_n(f4_7_local_channel_empty_n),
    .if_read(conv5_U0_f4_7_read)
);

fifo_w32_d16_A f5_0_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_0_din),
    .if_full_n(f5_0_local_channel_full_n),
    .if_write(conv5_U0_out_0_write),
    .if_dout(f5_0_local_channel_dout),
    .if_empty_n(f5_0_local_channel_empty_n),
    .if_read(detection_head_U0_f5_0_read)
);

fifo_w32_d16_A f5_1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_1_din),
    .if_full_n(f5_1_local_channel_full_n),
    .if_write(conv5_U0_out_1_write),
    .if_dout(f5_1_local_channel_dout),
    .if_empty_n(f5_1_local_channel_empty_n),
    .if_read(detection_head_U0_f5_1_read)
);

fifo_w32_d16_A f5_2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_2_din),
    .if_full_n(f5_2_local_channel_full_n),
    .if_write(conv5_U0_out_2_write),
    .if_dout(f5_2_local_channel_dout),
    .if_empty_n(f5_2_local_channel_empty_n),
    .if_read(detection_head_U0_f5_2_read)
);

fifo_w32_d16_A f5_3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_3_din),
    .if_full_n(f5_3_local_channel_full_n),
    .if_write(conv5_U0_out_3_write),
    .if_dout(f5_3_local_channel_dout),
    .if_empty_n(f5_3_local_channel_empty_n),
    .if_read(detection_head_U0_f5_3_read)
);

fifo_w32_d16_A f5_4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_4_din),
    .if_full_n(f5_4_local_channel_full_n),
    .if_write(conv5_U0_out_4_write),
    .if_dout(f5_4_local_channel_dout),
    .if_empty_n(f5_4_local_channel_empty_n),
    .if_read(detection_head_U0_f5_4_read)
);

fifo_w32_d16_A f5_5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_5_din),
    .if_full_n(f5_5_local_channel_full_n),
    .if_write(conv5_U0_out_5_write),
    .if_dout(f5_5_local_channel_dout),
    .if_empty_n(f5_5_local_channel_empty_n),
    .if_read(detection_head_U0_f5_5_read)
);

fifo_w32_d16_A f5_6_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_6_din),
    .if_full_n(f5_6_local_channel_full_n),
    .if_write(conv5_U0_out_6_write),
    .if_dout(f5_6_local_channel_dout),
    .if_empty_n(f5_6_local_channel_empty_n),
    .if_read(detection_head_U0_f5_6_read)
);

fifo_w32_d16_A f5_7_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_7_din),
    .if_full_n(f5_7_local_channel_full_n),
    .if_write(conv5_U0_out_7_write),
    .if_dout(f5_7_local_channel_dout),
    .if_empty_n(f5_7_local_channel_empty_n),
    .if_read(detection_head_U0_f5_7_read)
);

start_for_maxpoolg8j start_for_maxpoolg8j_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool1_U0_din),
    .if_full_n(start_for_maxpool1_U0_full_n),
    .if_write(conv1_U0_start_write),
    .if_dout(start_for_maxpool1_U0_dout),
    .if_empty_n(start_for_maxpool1_U0_empty_n),
    .if_read(maxpool1_U0_ap_ready)
);

start_for_conv2_U0 start_for_conv2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv2_U0_din),
    .if_full_n(start_for_conv2_U0_full_n),
    .if_write(maxpool1_U0_start_write),
    .if_dout(start_for_conv2_U0_dout),
    .if_empty_n(start_for_conv2_U0_empty_n),
    .if_read(conv2_U0_ap_ready)
);

start_for_maxpoolhbi start_for_maxpoolhbi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool2_U0_din),
    .if_full_n(start_for_maxpool2_U0_full_n),
    .if_write(conv2_U0_start_write),
    .if_dout(start_for_maxpool2_U0_dout),
    .if_empty_n(start_for_maxpool2_U0_empty_n),
    .if_read(maxpool2_U0_ap_ready)
);

start_for_conv3_U0 start_for_conv3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv3_U0_din),
    .if_full_n(start_for_conv3_U0_full_n),
    .if_write(maxpool2_U0_start_write),
    .if_dout(start_for_conv3_U0_dout),
    .if_empty_n(start_for_conv3_U0_empty_n),
    .if_read(conv3_U0_ap_ready)
);

start_for_conv4_U0 start_for_conv4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv4_U0_din),
    .if_full_n(start_for_conv4_U0_full_n),
    .if_write(conv3_U0_start_write),
    .if_dout(start_for_conv4_U0_dout),
    .if_empty_n(start_for_conv4_U0_empty_n),
    .if_read(conv4_U0_ap_ready)
);

start_for_conv5_U0 start_for_conv5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv5_U0_din),
    .if_full_n(start_for_conv5_U0_full_n),
    .if_write(conv4_U0_start_write),
    .if_dout(start_for_conv5_U0_dout),
    .if_empty_n(start_for_conv5_U0_empty_n),
    .if_read(conv5_U0_ap_ready)
);

start_for_detectiibs start_for_detectiibs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_detection_head_U0_din),
    .if_full_n(start_for_detection_head_U0_full_n),
    .if_write(conv5_U0_start_write),
    .if_dout(start_for_detection_head_U0_dout),
    .if_empty_n(start_for_detection_head_U0_empty_n),
    .if_read(detection_head_U0_ap_ready)
);

assign ap_done = detection_head_U0_ap_done;

assign ap_idle = (maxpool2_U0_ap_idle & maxpool1_U0_ap_idle & detection_head_U0_ap_idle & conv5_U0_ap_idle & conv4_U0_ap_idle & conv3_U0_ap_idle & conv2_U0_ap_idle & conv1_U0_ap_idle);

assign ap_ready = conv1_U0_ap_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = detection_head_U0_ap_done;

assign ap_sync_ready = conv1_U0_ap_ready;

assign conv1_U0_ap_continue = 1'b1;

assign conv1_U0_ap_start = ap_start;

assign conv2_U0_ap_continue = 1'b1;

assign conv2_U0_ap_start = start_for_conv2_U0_empty_n;

assign conv3_U0_ap_continue = 1'b1;

assign conv3_U0_ap_start = start_for_conv3_U0_empty_n;

assign conv4_U0_ap_continue = 1'b1;

assign conv4_U0_ap_start = start_for_conv4_U0_empty_n;

assign conv5_U0_ap_continue = 1'b1;

assign conv5_U0_ap_start = start_for_conv5_U0_empty_n;

assign detection_head_U0_ap_continue = 1'b1;

assign detection_head_U0_ap_start = start_for_detection_head_U0_empty_n;

assign detection_head_U0_start_full_n = 1'b1;

assign detection_head_U0_start_write = 1'b0;

assign image_r_address0 = conv1_U0_in_r_address0;

assign image_r_address1 = 14'd0;

assign image_r_ce0 = conv1_U0_in_r_ce0;

assign image_r_ce1 = 1'b0;

assign image_r_d0 = 32'd0;

assign image_r_d1 = 32'd0;

assign image_r_we0 = 1'b0;

assign image_r_we1 = 1'b0;

assign maxpool1_U0_ap_continue = 1'b1;

assign maxpool1_U0_ap_start = start_for_maxpool1_U0_empty_n;

assign maxpool2_U0_ap_continue = 1'b1;

assign maxpool2_U0_ap_start = start_for_maxpool2_U0_empty_n;

assign output_r_address0 = detection_head_U0_out_r_address0;

assign output_r_address1 = 10'd0;

assign output_r_ce0 = detection_head_U0_out_r_ce0;

assign output_r_ce1 = 1'b0;

assign output_r_d0 = detection_head_U0_out_r_d0;

assign output_r_d1 = 32'd0;

assign output_r_we0 = detection_head_U0_out_r_we0;

assign output_r_we1 = 1'b0;

assign start_for_conv2_U0_din = 1'b1;

assign start_for_conv3_U0_din = 1'b1;

assign start_for_conv4_U0_din = 1'b1;

assign start_for_conv5_U0_din = 1'b1;

assign start_for_detection_head_U0_din = 1'b1;

assign start_for_maxpool1_U0_din = 1'b1;

assign start_for_maxpool2_U0_din = 1'b1;

endmodule //topp
