// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv2 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        out_r_din,
        out_r_full_n,
        out_r_write,
        p1_dout,
        p1_empty_n,
        p1_read
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_state20 = 26'd524288;
parameter    ap_ST_fsm_state21 = 26'd1048576;
parameter    ap_ST_fsm_state22 = 26'd2097152;
parameter    ap_ST_fsm_state23 = 26'd4194304;
parameter    ap_ST_fsm_state24 = 26'd8388608;
parameter    ap_ST_fsm_state25 = 26'd16777216;
parameter    ap_ST_fsm_state26 = 26'd33554432;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [31:0] out_r_din;
input   out_r_full_n;
output   out_r_write;
input  [31:0] p1_dout;
input   p1_empty_n;
output   p1_read;

reg ap_done;
reg ap_idle;
reg start_write;
reg out_r_write;
reg p1_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [7:0] linbu_5_0_address0;
reg    linbu_5_0_ce0;
reg    linbu_5_0_we0;
wire   [31:0] linbu_5_0_q0;
reg   [7:0] linbu_5_1_address0;
reg    linbu_5_1_ce0;
reg    linbu_5_1_we0;
wire   [31:0] linbu_5_1_q0;
reg    out_r_blk_n;
wire    ap_CS_fsm_state26;
reg    p1_blk_n;
wire    ap_CS_fsm_state11;
wire   [31:0] win_buf_q0;
reg   [31:0] reg_352;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
wire   [31:0] win_buf_q1;
wire    ap_CS_fsm_state16;
reg   [31:0] reg_359;
wire   [4:0] r_fu_370_p2;
reg   [4:0] r_reg_701;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_fu_386_p2;
reg   [0:0] icmp_reg_706;
wire   [0:0] exitcond6_i_fu_364_p2;
wire   [4:0] c_fu_398_p2;
reg   [4:0] c_reg_714;
wire    ap_CS_fsm_state3;
wire   [8:0] tmp_60_cast_fu_412_p1;
reg   [8:0] tmp_60_cast_reg_719;
wire   [0:0] exitcond5_i_fu_392_p2;
wire   [3:0] ic_fu_422_p2;
reg   [3:0] ic_reg_727;
wire    ap_CS_fsm_state4;
wire  signed [3:0] tmp_59_fu_428_p2;
reg  signed [3:0] tmp_59_reg_732;
wire   [0:0] exitcond4_i_fu_416_p2;
reg   [6:0] win_buf_addr_reg_738;
reg   [6:0] win_buf_addr_29_reg_744;
wire   [0:0] or_cond_i_fu_464_p2;
reg   [0:0] or_cond_i_reg_750;
reg   [6:0] win_buf_addr_30_reg_754;
reg   [6:0] win_buf_addr_32_reg_760;
reg   [6:0] win_buf_addr_33_reg_765;
wire    ap_CS_fsm_state6;
reg   [6:0] win_buf_addr_35_reg_771;
reg   [31:0] win_buf_load_20_reg_777;
reg   [31:0] win_buf_load_21_reg_782;
reg   [7:0] linbu_5_0_addr_reg_787;
wire    ap_CS_fsm_state9;
reg   [7:0] linbu_5_1_addr_reg_792;
wire   [4:0] oc_fu_553_p2;
reg   [4:0] oc_reg_800;
wire    ap_CS_fsm_state12;
wire   [1:0] kr_fu_565_p2;
reg   [1:0] kr_reg_808;
wire    ap_CS_fsm_state13;
wire   [4:0] tmp_70_fu_587_p2;
reg   [4:0] tmp_70_reg_813;
wire   [0:0] exitcond2_i_fu_559_p2;
wire   [0:0] tmp_58_fu_346_p2;
reg   [0:0] tmp_58_reg_818;
wire   [1:0] kc_fu_599_p2;
reg   [1:0] kc_reg_826;
wire    ap_CS_fsm_state14;
wire   [7:0] tmp_78_cast_fu_614_p3;
reg   [7:0] tmp_78_cast_reg_831;
wire   [0:0] exitcond1_i_fu_593_p2;
wire   [3:0] ic_4_fu_628_p2;
reg   [3:0] ic_4_reg_839;
wire    ap_CS_fsm_state15;
wire   [0:0] exitcond_i_fu_622_p2;
wire   [31:0] grp_fu_341_p2;
reg   [31:0] tmp_82_i_reg_849;
wire    ap_CS_fsm_state20;
wire   [31:0] grp_fu_336_p2;
wire    ap_CS_fsm_state25;
reg   [6:0] win_buf_address0;
reg    win_buf_ce0;
reg    win_buf_we0;
reg   [31:0] win_buf_d0;
reg   [6:0] win_buf_address1;
reg    win_buf_ce1;
reg    win_buf_we1;
reg   [31:0] win_buf_d1;
reg   [4:0] r_i_reg_221;
reg    ap_block_state1;
reg   [4:0] c_i_reg_232;
wire   [0:0] exitcond3_i_fu_547_p2;
reg   [3:0] ic_i_reg_244;
reg   [4:0] oc_i_reg_256;
reg   [1:0] kr_i_reg_267;
reg   [31:0] sum8_i_reg_278;
reg   [1:0] kc_i_reg_290;
reg   [31:0] sum_1_i_reg_301;
reg   [3:0] ic_1_i_reg_313;
reg   [31:0] sum_2_i_reg_324;
wire   [63:0] tmp_66_cast_fu_434_p1;
wire   [63:0] tmp_60_fu_439_p3;
wire   [63:0] tmp_64_fu_473_p3;
wire   [63:0] tmp_70_cast_fu_488_p1;
wire   [63:0] tmp_71_cast_fu_496_p1;
wire   [63:0] tmp_67_fu_501_p3;
wire   [63:0] tmp_74_i_fu_510_p1;
wire   [63:0] tmp_69_cast_fu_518_p1;
wire    ap_CS_fsm_state8;
wire   [63:0] tmp_65_cast_fu_532_p1;
wire   [63:0] tmp_66_fu_538_p3;
wire   [63:0] tmp_79_cast_fu_643_p1;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state17;
wire   [3:0] tmp_62_fu_376_p4;
wire   [7:0] tmp_s_fu_404_p3;
wire   [3:0] tmp_63_fu_448_p4;
wire   [0:0] icmp4_fu_458_p2;
wire   [5:0] tmp_74_i_cast1_fu_469_p1;
wire   [5:0] tmp_65_fu_482_p2;
wire  signed [5:0] tmp_71_cast1_fu_493_p1;
wire  signed [4:0] tmp_69_cast1_fu_515_p1;
wire   [8:0] tmp_74_i_cast_fu_523_p1;
wire   [8:0] tmp_56_fu_527_p2;
wire   [3:0] tmp_69_fu_575_p3;
wire   [4:0] p_shl_cast_fu_583_p1;
wire   [4:0] tmp_79_i_cast_fu_571_p1;
wire   [4:0] tmp_80_i_cast_fu_605_p1;
wire   [4:0] tmp_71_fu_609_p2;
wire   [7:0] tmp_81_i_cast_fu_634_p1;
wire   [7:0] tmp_72_fu_638_p2;
wire   [31:0] sum8_i_to_int_fu_648_p1;
wire   [7:0] tmp_fu_652_p4;
wire   [22:0] tmp_68_fu_662_p1;
wire   [0:0] notrhs_fu_672_p2;
wire   [0:0] notlhs_fu_666_p2;
wire   [0:0] tmp_57_fu_678_p2;
wire   [0:0] tmp_61_fu_684_p2;
reg   [25:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 26'd1;
end

conv2_linbu_5_0 #(
    .DataWidth( 32 ),
    .AddressRange( 248 ),
    .AddressWidth( 8 ))
linbu_5_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_5_0_address0),
    .ce0(linbu_5_0_ce0),
    .we0(linbu_5_0_we0),
    .d0(linbu_5_1_q0),
    .q0(linbu_5_0_q0)
);

conv2_linbu_5_0 #(
    .DataWidth( 32 ),
    .AddressRange( 248 ),
    .AddressWidth( 8 ))
linbu_5_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linbu_5_1_address0),
    .ce0(linbu_5_1_ce0),
    .we0(linbu_5_1_we0),
    .d0(p1_dout),
    .q0(linbu_5_1_q0)
);

conv2_win_buf #(
    .DataWidth( 32 ),
    .AddressRange( 72 ),
    .AddressWidth( 7 ))
win_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(win_buf_address0),
    .ce0(win_buf_ce0),
    .we0(win_buf_we0),
    .d0(win_buf_d0),
    .q0(win_buf_q0),
    .address1(win_buf_address1),
    .ce1(win_buf_ce1),
    .we1(win_buf_we1),
    .d1(win_buf_d1),
    .q1(win_buf_q1)
);

topp_fadd_32ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fadd_32ns_32bkb_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_2_i_reg_324),
    .din1(tmp_82_i_reg_849),
    .ce(1'b1),
    .dout(grp_fu_336_p2)
);

topp_fmul_32ns_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fmul_32ns_32cud_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_352),
    .din1(32'd0),
    .ce(1'b1),
    .dout(grp_fu_341_p2)
);

topp_fcmp_32ns_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
topp_fcmp_32ns_32dEe_U16(
    .din0(sum8_i_reg_278),
    .din1(32'd0),
    .opcode(5'd4),
    .dout(tmp_58_fu_346_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_i_fu_364_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_i_fu_364_p2 == 1'd0))) begin
        c_i_reg_232 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state12) & ((exitcond3_i_fu_547_p2 == 1'd1) | (or_cond_i_reg_750 == 1'd0)))) begin
        c_i_reg_232 <= c_reg_714;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (exitcond1_i_fu_593_p2 == 1'd0))) begin
        ic_1_i_reg_313 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        ic_1_i_reg_313 <= ic_4_reg_839;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond5_i_fu_392_p2 == 1'd0))) begin
        ic_i_reg_244 <= 4'd0;
    end else if (((p1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        ic_i_reg_244 <= ic_reg_727;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_622_p2 == 1'd1))) begin
        kc_i_reg_290 <= kc_reg_826;
    end else if (((1'b1 == ap_CS_fsm_state13) & (exitcond2_i_fu_559_p2 == 1'd0))) begin
        kc_i_reg_290 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (or_cond_i_reg_750 == 1'd1) & (exitcond3_i_fu_547_p2 == 1'd0))) begin
        kr_i_reg_267 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state14) & (exitcond1_i_fu_593_p2 == 1'd1))) begin
        kr_i_reg_267 <= kr_reg_808;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (or_cond_i_fu_464_p2 == 1'd1) & (exitcond4_i_fu_416_p2 == 1'd1))) begin
        oc_i_reg_256 <= 5'd0;
    end else if (((out_r_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        oc_i_reg_256 <= oc_reg_800;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond5_i_fu_392_p2 == 1'd1))) begin
        r_i_reg_221 <= r_reg_701;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        r_i_reg_221 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_352 <= win_buf_q1;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_352 <= win_buf_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (or_cond_i_reg_750 == 1'd1) & (exitcond3_i_fu_547_p2 == 1'd0))) begin
        sum8_i_reg_278 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state14) & (exitcond1_i_fu_593_p2 == 1'd1))) begin
        sum8_i_reg_278 <= sum_1_i_reg_301;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_622_p2 == 1'd1))) begin
        sum_1_i_reg_301 <= sum_2_i_reg_324;
    end else if (((1'b1 == ap_CS_fsm_state13) & (exitcond2_i_fu_559_p2 == 1'd0))) begin
        sum_1_i_reg_301 <= sum8_i_reg_278;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (exitcond1_i_fu_593_p2 == 1'd0))) begin
        sum_2_i_reg_324 <= sum_1_i_reg_301;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        sum_2_i_reg_324 <= grp_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c_reg_714 <= c_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ic_4_reg_839 <= ic_4_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ic_reg_727 <= ic_fu_422_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_i_fu_364_p2 == 1'd0))) begin
        icmp_reg_706 <= icmp_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        kc_reg_826 <= kc_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        kr_reg_808 <= kr_fu_565_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        linbu_5_0_addr_reg_787 <= tmp_65_cast_fu_532_p1;
        linbu_5_1_addr_reg_792 <= tmp_65_cast_fu_532_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) & (or_cond_i_reg_750 == 1'd1))) begin
        oc_reg_800 <= oc_fu_553_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond4_i_fu_416_p2 == 1'd1))) begin
        or_cond_i_reg_750 <= or_cond_i_fu_464_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_reg_701 <= r_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_359 <= win_buf_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (exitcond2_i_fu_559_p2 == 1'd1))) begin
        tmp_58_reg_818 <= tmp_58_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (exitcond4_i_fu_416_p2 == 1'd0))) begin
        tmp_59_reg_732 <= tmp_59_fu_428_p2;
        win_buf_addr_29_reg_744[3 : 0] <= tmp_60_fu_439_p3[3 : 0];
        win_buf_addr_reg_738[3 : 0] <= tmp_66_cast_fu_434_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond5_i_fu_392_p2 == 1'd0))) begin
        tmp_60_cast_reg_719[7 : 3] <= tmp_60_cast_fu_412_p1[7 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (exitcond2_i_fu_559_p2 == 1'd0))) begin
        tmp_70_reg_813 <= tmp_70_fu_587_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (exitcond1_i_fu_593_p2 == 1'd0))) begin
        tmp_78_cast_reg_831[7 : 3] <= tmp_78_cast_fu_614_p3[7 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tmp_82_i_reg_849 <= grp_fu_341_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        win_buf_addr_30_reg_754[3 : 0] <= tmp_64_fu_473_p3[3 : 0];
        win_buf_addr_32_reg_760[5 : 0] <= tmp_70_cast_fu_488_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        win_buf_addr_33_reg_765[5 : 0] <= tmp_71_cast_fu_496_p1[5 : 0];
        win_buf_addr_35_reg_771[3 : 0] <= tmp_67_fu_501_p3[3 : 0];
        win_buf_load_20_reg_777 <= win_buf_q0;
        win_buf_load_21_reg_782 <= win_buf_q1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_i_fu_364_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_i_fu_364_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        linbu_5_0_address0 = linbu_5_0_addr_reg_787;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        linbu_5_0_address0 = tmp_65_cast_fu_532_p1;
    end else begin
        linbu_5_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        linbu_5_0_ce0 = 1'b1;
    end else begin
        linbu_5_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        linbu_5_0_we0 = 1'b1;
    end else begin
        linbu_5_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        linbu_5_1_address0 = linbu_5_1_addr_reg_792;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        linbu_5_1_address0 = tmp_65_cast_fu_532_p1;
    end else begin
        linbu_5_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((p1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        linbu_5_1_ce0 = 1'b1;
    end else begin
        linbu_5_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        linbu_5_1_we0 = 1'b1;
    end else begin
        linbu_5_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        out_r_blk_n = out_r_full_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_r_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
        out_r_write = 1'b1;
    end else begin
        out_r_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        p1_blk_n = p1_empty_n;
    end else begin
        p1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((p1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        p1_read = 1'b1;
    end else begin
        p1_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        win_buf_address0 = win_buf_addr_35_reg_771;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        win_buf_address0 = win_buf_addr_29_reg_744;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        win_buf_address0 = tmp_66_fu_538_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        win_buf_address0 = tmp_69_cast_fu_518_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        win_buf_address0 = tmp_74_i_fu_510_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        win_buf_address0 = tmp_71_cast_fu_496_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        win_buf_address0 = tmp_64_fu_473_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        win_buf_address0 = tmp_66_cast_fu_434_p1;
    end else begin
        win_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        win_buf_address1 = tmp_79_cast_fu_643_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        win_buf_address1 = win_buf_addr_32_reg_760;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        win_buf_address1 = win_buf_addr_33_reg_765;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        win_buf_address1 = win_buf_addr_30_reg_754;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        win_buf_address1 = win_buf_addr_reg_738;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        win_buf_address1 = tmp_67_fu_501_p3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        win_buf_address1 = tmp_70_cast_fu_488_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        win_buf_address1 = tmp_60_fu_439_p3;
    end else begin
        win_buf_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | ((p1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        win_buf_ce0 = 1'b1;
    end else begin
        win_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5))) begin
        win_buf_ce1 = 1'b1;
    end else begin
        win_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        win_buf_d0 = p1_dout;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        win_buf_d0 = linbu_5_0_q0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        win_buf_d0 = win_buf_load_20_reg_777;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7))) begin
        win_buf_d0 = reg_352;
    end else begin
        win_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        win_buf_d1 = linbu_5_1_q0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        win_buf_d1 = win_buf_load_21_reg_782;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7))) begin
        win_buf_d1 = reg_359;
    end else begin
        win_buf_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | ((p1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        win_buf_we0 = 1'b1;
    end else begin
        win_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7))) begin
        win_buf_we1 = 1'b1;
    end else begin
        win_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond6_i_fu_364_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond5_i_fu_392_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (exitcond4_i_fu_416_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((p1_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & ((exitcond3_i_fu_547_p2 == 1'd1) | (or_cond_i_reg_750 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b1 == ap_CS_fsm_state13) & (exitcond2_i_fu_559_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (exitcond1_i_fu_593_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (exitcond_i_fu_622_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state26 : begin
            if (((out_r_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign c_fu_398_p2 = (c_i_reg_232 + 5'd1);

assign exitcond1_i_fu_593_p2 = ((kc_i_reg_290 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond2_i_fu_559_p2 = ((kr_i_reg_267 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond3_i_fu_547_p2 = ((oc_i_reg_256 == 5'd16) ? 1'b1 : 1'b0);

assign exitcond4_i_fu_416_p2 = ((ic_i_reg_244 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond5_i_fu_392_p2 = ((c_i_reg_232 == 5'd31) ? 1'b1 : 1'b0);

assign exitcond6_i_fu_364_p2 = ((r_i_reg_221 == 5'd31) ? 1'b1 : 1'b0);

assign exitcond_i_fu_622_p2 = ((ic_1_i_reg_313 == 4'd8) ? 1'b1 : 1'b0);

assign ic_4_fu_628_p2 = (ic_1_i_reg_313 + 4'd1);

assign ic_fu_422_p2 = (ic_i_reg_244 + 4'd1);

assign icmp4_fu_458_p2 = ((tmp_63_fu_448_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_fu_386_p2 = ((tmp_62_fu_376_p4 != 4'd0) ? 1'b1 : 1'b0);

assign kc_fu_599_p2 = (kc_i_reg_290 + 2'd1);

assign kr_fu_565_p2 = (kr_i_reg_267 + 2'd1);

assign notlhs_fu_666_p2 = ((tmp_fu_652_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_672_p2 = ((tmp_68_fu_662_p1 == 23'd0) ? 1'b1 : 1'b0);

assign oc_fu_553_p2 = (oc_i_reg_256 + 5'd1);

assign or_cond_i_fu_464_p2 = (icmp_reg_706 & icmp4_fu_458_p2);

assign out_r_din = ((tmp_61_fu_684_p2[0:0] === 1'b1) ? 32'd0 : sum8_i_reg_278);

assign p_shl_cast_fu_583_p1 = tmp_69_fu_575_p3;

assign r_fu_370_p2 = (r_i_reg_221 + 5'd1);

assign start_out = real_start;

assign sum8_i_to_int_fu_648_p1 = sum8_i_reg_278;

assign tmp_56_fu_527_p2 = (tmp_60_cast_reg_719 + tmp_74_i_cast_fu_523_p1);

assign tmp_57_fu_678_p2 = (notrhs_fu_672_p2 | notlhs_fu_666_p2);

assign tmp_59_fu_428_p2 = (ic_i_reg_244 ^ 4'd8);

assign tmp_60_cast_fu_412_p1 = tmp_s_fu_404_p3;

assign tmp_60_fu_439_p3 = {{60'd1}, {ic_i_reg_244}};

assign tmp_61_fu_684_p2 = (tmp_58_reg_818 & tmp_57_fu_678_p2);

assign tmp_62_fu_376_p4 = {{r_i_reg_221[4:1]}};

assign tmp_63_fu_448_p4 = {{c_i_reg_232[4:1]}};

assign tmp_64_fu_473_p3 = {{60'd2}, {ic_i_reg_244}};

assign tmp_65_cast_fu_532_p1 = tmp_56_fu_527_p2;

assign tmp_65_fu_482_p2 = ($signed(tmp_74_i_cast1_fu_469_p1) + $signed(6'd40));

assign tmp_66_cast_fu_434_p1 = $unsigned(tmp_59_fu_428_p2);

assign tmp_66_fu_538_p3 = {{60'd3}, {ic_i_reg_244}};

assign tmp_67_fu_501_p3 = {{60'd4}, {ic_i_reg_244}};

assign tmp_68_fu_662_p1 = sum8_i_to_int_fu_648_p1[22:0];

assign tmp_69_cast1_fu_515_p1 = tmp_59_reg_732;

assign tmp_69_cast_fu_518_p1 = $unsigned(tmp_69_cast1_fu_515_p1);

assign tmp_69_fu_575_p3 = {{kr_i_reg_267}, {2'd0}};

assign tmp_70_cast_fu_488_p1 = tmp_65_fu_482_p2;

assign tmp_70_fu_587_p2 = (p_shl_cast_fu_583_p1 - tmp_79_i_cast_fu_571_p1);

assign tmp_71_cast1_fu_493_p1 = tmp_59_reg_732;

assign tmp_71_cast_fu_496_p1 = $unsigned(tmp_71_cast1_fu_493_p1);

assign tmp_71_fu_609_p2 = (tmp_80_i_cast_fu_605_p1 + tmp_70_reg_813);

assign tmp_72_fu_638_p2 = (tmp_78_cast_reg_831 + tmp_81_i_cast_fu_634_p1);

assign tmp_74_i_cast1_fu_469_p1 = ic_i_reg_244;

assign tmp_74_i_cast_fu_523_p1 = ic_i_reg_244;

assign tmp_74_i_fu_510_p1 = ic_i_reg_244;

assign tmp_78_cast_fu_614_p3 = {{tmp_71_fu_609_p2}, {3'd0}};

assign tmp_79_cast_fu_643_p1 = tmp_72_fu_638_p2;

assign tmp_79_i_cast_fu_571_p1 = kr_i_reg_267;

assign tmp_80_i_cast_fu_605_p1 = kc_i_reg_290;

assign tmp_81_i_cast_fu_634_p1 = ic_1_i_reg_313;

assign tmp_fu_652_p4 = {{sum8_i_to_int_fu_648_p1[30:23]}};

assign tmp_s_fu_404_p3 = {{c_i_reg_232}, {3'd0}};

always @ (posedge ap_clk) begin
    tmp_60_cast_reg_719[2:0] <= 3'b000;
    tmp_60_cast_reg_719[8] <= 1'b0;
    win_buf_addr_reg_738[6:4] <= 3'b000;
    win_buf_addr_29_reg_744[6:4] <= 3'b001;
    win_buf_addr_30_reg_754[6:4] <= 3'b010;
    win_buf_addr_32_reg_760[6] <= 1'b0;
    win_buf_addr_33_reg_765[6] <= 1'b0;
    win_buf_addr_35_reg_771[6:4] <= 3'b100;
    tmp_78_cast_reg_831[2:0] <= 3'b000;
end

endmodule //conv2
