// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="topp,hls_ip_2018_3,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=8.677000,HLS_SYN_LAT=7462485,HLS_SYN_TPT=7398602,HLS_SYN_MEM=20,HLS_SYN_DSP=37,HLS_SYN_FF=6465,HLS_SYN_LUT=13414,HLS_VERSION=2018_3}" *)

module topp (
        image_r_address0,
        image_r_ce0,
        image_r_d0,
        image_r_q0,
        image_r_we0,
        image_r_address1,
        image_r_ce1,
        image_r_d1,
        image_r_q1,
        image_r_we1,
        output_r_address0,
        output_r_ce0,
        output_r_d0,
        output_r_q0,
        output_r_we0,
        output_r_address1,
        output_r_ce1,
        output_r_d1,
        output_r_q1,
        output_r_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


output  [13:0] image_r_address0;
output   image_r_ce0;
output  [31:0] image_r_d0;
input  [31:0] image_r_q0;
output   image_r_we0;
output  [13:0] image_r_address1;
output   image_r_ce1;
output  [31:0] image_r_d1;
input  [31:0] image_r_q1;
output   image_r_we1;
output  [9:0] output_r_address0;
output   output_r_ce0;
output  [31:0] output_r_d0;
input  [31:0] output_r_q0;
output   output_r_we0;
output  [9:0] output_r_address1;
output   output_r_ce1;
output  [31:0] output_r_d1;
input  [31:0] output_r_q1;
output   output_r_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    conv1_U0_ap_start;
wire    conv1_U0_ap_done;
wire    conv1_U0_ap_continue;
wire    conv1_U0_ap_idle;
wire    conv1_U0_ap_ready;
wire    conv1_U0_start_out;
wire    conv1_U0_start_write;
wire   [13:0] conv1_U0_in_r_address0;
wire    conv1_U0_in_r_ce0;
wire   [31:0] conv1_U0_out_r_din;
wire    conv1_U0_out_r_write;
wire    maxpool1_U0_ap_start;
wire    maxpool1_U0_ap_done;
wire    maxpool1_U0_ap_continue;
wire    maxpool1_U0_ap_idle;
wire    maxpool1_U0_ap_ready;
wire    maxpool1_U0_start_out;
wire    maxpool1_U0_start_write;
wire   [31:0] maxpool1_U0_out_r_din;
wire    maxpool1_U0_out_r_write;
wire    maxpool1_U0_f1_read;
wire    conv2_U0_ap_start;
wire    conv2_U0_ap_done;
wire    conv2_U0_ap_continue;
wire    conv2_U0_ap_idle;
wire    conv2_U0_ap_ready;
wire    conv2_U0_start_out;
wire    conv2_U0_start_write;
wire   [31:0] conv2_U0_out_r_din;
wire    conv2_U0_out_r_write;
wire    conv2_U0_p1_read;
wire    maxpool2_U0_ap_start;
wire    maxpool2_U0_ap_done;
wire    maxpool2_U0_ap_continue;
wire    maxpool2_U0_ap_idle;
wire    maxpool2_U0_ap_ready;
wire    maxpool2_U0_start_out;
wire    maxpool2_U0_start_write;
wire   [31:0] maxpool2_U0_out_r_din;
wire    maxpool2_U0_out_r_write;
wire    maxpool2_U0_f2_read;
wire    conv3_U0_ap_start;
wire    conv3_U0_ap_done;
wire    conv3_U0_ap_continue;
wire    conv3_U0_ap_idle;
wire    conv3_U0_ap_ready;
wire    conv3_U0_start_out;
wire    conv3_U0_start_write;
wire   [31:0] conv3_U0_out_r_din;
wire    conv3_U0_out_r_write;
wire    conv3_U0_p2_read;
wire    conv4_U0_ap_start;
wire    conv4_U0_ap_done;
wire    conv4_U0_ap_continue;
wire    conv4_U0_ap_idle;
wire    conv4_U0_ap_ready;
wire    conv4_U0_start_out;
wire    conv4_U0_start_write;
wire   [31:0] conv4_U0_out_r_din;
wire    conv4_U0_out_r_write;
wire    conv4_U0_f3_read;
wire    conv5_U0_ap_start;
wire    conv5_U0_ap_done;
wire    conv5_U0_ap_continue;
wire    conv5_U0_ap_idle;
wire    conv5_U0_ap_ready;
wire    conv5_U0_start_out;
wire    conv5_U0_start_write;
wire   [31:0] conv5_U0_out_r_din;
wire    conv5_U0_out_r_write;
wire    conv5_U0_f4_read;
wire    detection_head_U0_ap_start;
wire    detection_head_U0_ap_done;
wire    detection_head_U0_ap_continue;
wire    detection_head_U0_ap_idle;
wire    detection_head_U0_ap_ready;
wire   [9:0] detection_head_U0_out_r_address0;
wire    detection_head_U0_out_r_ce0;
wire    detection_head_U0_out_r_we0;
wire   [31:0] detection_head_U0_out_r_d0;
wire    detection_head_U0_f5_read;
wire    ap_sync_continue;
wire    f1_local_channel_full_n;
wire   [31:0] f1_local_channel_dout;
wire    f1_local_channel_empty_n;
wire    p1_local_channel_full_n;
wire   [31:0] p1_local_channel_dout;
wire    p1_local_channel_empty_n;
wire    f2_local_channel_full_n;
wire   [31:0] f2_local_channel_dout;
wire    f2_local_channel_empty_n;
wire    p2_local_channel_full_n;
wire   [31:0] p2_local_channel_dout;
wire    p2_local_channel_empty_n;
wire    f3_local_channel_full_n;
wire   [31:0] f3_local_channel_dout;
wire    f3_local_channel_empty_n;
wire    f4_local_channel_full_n;
wire   [31:0] f4_local_channel_dout;
wire    f4_local_channel_empty_n;
wire    f5_local_channel_full_n;
wire   [31:0] f5_local_channel_dout;
wire    f5_local_channel_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_maxpool1_U0_din;
wire    start_for_maxpool1_U0_full_n;
wire   [0:0] start_for_maxpool1_U0_dout;
wire    start_for_maxpool1_U0_empty_n;
wire   [0:0] start_for_conv2_U0_din;
wire    start_for_conv2_U0_full_n;
wire   [0:0] start_for_conv2_U0_dout;
wire    start_for_conv2_U0_empty_n;
wire   [0:0] start_for_maxpool2_U0_din;
wire    start_for_maxpool2_U0_full_n;
wire   [0:0] start_for_maxpool2_U0_dout;
wire    start_for_maxpool2_U0_empty_n;
wire   [0:0] start_for_conv3_U0_din;
wire    start_for_conv3_U0_full_n;
wire   [0:0] start_for_conv3_U0_dout;
wire    start_for_conv3_U0_empty_n;
wire   [0:0] start_for_conv4_U0_din;
wire    start_for_conv4_U0_full_n;
wire   [0:0] start_for_conv4_U0_dout;
wire    start_for_conv4_U0_empty_n;
wire   [0:0] start_for_conv5_U0_din;
wire    start_for_conv5_U0_full_n;
wire   [0:0] start_for_conv5_U0_dout;
wire    start_for_conv5_U0_empty_n;
wire   [0:0] start_for_detection_head_U0_din;
wire    start_for_detection_head_U0_full_n;
wire   [0:0] start_for_detection_head_U0_dout;
wire    start_for_detection_head_U0_empty_n;
wire    detection_head_U0_start_full_n;
wire    detection_head_U0_start_write;

conv1 conv1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv1_U0_ap_start),
    .start_full_n(start_for_maxpool1_U0_full_n),
    .ap_done(conv1_U0_ap_done),
    .ap_continue(conv1_U0_ap_continue),
    .ap_idle(conv1_U0_ap_idle),
    .ap_ready(conv1_U0_ap_ready),
    .start_out(conv1_U0_start_out),
    .start_write(conv1_U0_start_write),
    .in_r_address0(conv1_U0_in_r_address0),
    .in_r_ce0(conv1_U0_in_r_ce0),
    .in_r_q0(image_r_q0),
    .out_r_din(conv1_U0_out_r_din),
    .out_r_full_n(f1_local_channel_full_n),
    .out_r_write(conv1_U0_out_r_write)
);

maxpool1 maxpool1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(maxpool1_U0_ap_start),
    .start_full_n(start_for_conv2_U0_full_n),
    .ap_done(maxpool1_U0_ap_done),
    .ap_continue(maxpool1_U0_ap_continue),
    .ap_idle(maxpool1_U0_ap_idle),
    .ap_ready(maxpool1_U0_ap_ready),
    .start_out(maxpool1_U0_start_out),
    .start_write(maxpool1_U0_start_write),
    .out_r_din(maxpool1_U0_out_r_din),
    .out_r_full_n(p1_local_channel_full_n),
    .out_r_write(maxpool1_U0_out_r_write),
    .f1_dout(f1_local_channel_dout),
    .f1_empty_n(f1_local_channel_empty_n),
    .f1_read(maxpool1_U0_f1_read)
);

conv2 conv2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv2_U0_ap_start),
    .start_full_n(start_for_maxpool2_U0_full_n),
    .ap_done(conv2_U0_ap_done),
    .ap_continue(conv2_U0_ap_continue),
    .ap_idle(conv2_U0_ap_idle),
    .ap_ready(conv2_U0_ap_ready),
    .start_out(conv2_U0_start_out),
    .start_write(conv2_U0_start_write),
    .out_r_din(conv2_U0_out_r_din),
    .out_r_full_n(f2_local_channel_full_n),
    .out_r_write(conv2_U0_out_r_write),
    .p1_dout(p1_local_channel_dout),
    .p1_empty_n(p1_local_channel_empty_n),
    .p1_read(conv2_U0_p1_read)
);

maxpool2 maxpool2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(maxpool2_U0_ap_start),
    .start_full_n(start_for_conv3_U0_full_n),
    .ap_done(maxpool2_U0_ap_done),
    .ap_continue(maxpool2_U0_ap_continue),
    .ap_idle(maxpool2_U0_ap_idle),
    .ap_ready(maxpool2_U0_ap_ready),
    .start_out(maxpool2_U0_start_out),
    .start_write(maxpool2_U0_start_write),
    .out_r_din(maxpool2_U0_out_r_din),
    .out_r_full_n(p2_local_channel_full_n),
    .out_r_write(maxpool2_U0_out_r_write),
    .f2_dout(f2_local_channel_dout),
    .f2_empty_n(f2_local_channel_empty_n),
    .f2_read(maxpool2_U0_f2_read)
);

conv3 conv3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv3_U0_ap_start),
    .start_full_n(start_for_conv4_U0_full_n),
    .ap_done(conv3_U0_ap_done),
    .ap_continue(conv3_U0_ap_continue),
    .ap_idle(conv3_U0_ap_idle),
    .ap_ready(conv3_U0_ap_ready),
    .start_out(conv3_U0_start_out),
    .start_write(conv3_U0_start_write),
    .out_r_din(conv3_U0_out_r_din),
    .out_r_full_n(f3_local_channel_full_n),
    .out_r_write(conv3_U0_out_r_write),
    .p2_dout(p2_local_channel_dout),
    .p2_empty_n(p2_local_channel_empty_n),
    .p2_read(conv3_U0_p2_read)
);

conv4 conv4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv4_U0_ap_start),
    .start_full_n(start_for_conv5_U0_full_n),
    .ap_done(conv4_U0_ap_done),
    .ap_continue(conv4_U0_ap_continue),
    .ap_idle(conv4_U0_ap_idle),
    .ap_ready(conv4_U0_ap_ready),
    .start_out(conv4_U0_start_out),
    .start_write(conv4_U0_start_write),
    .out_r_din(conv4_U0_out_r_din),
    .out_r_full_n(f4_local_channel_full_n),
    .out_r_write(conv4_U0_out_r_write),
    .f3_dout(f3_local_channel_dout),
    .f3_empty_n(f3_local_channel_empty_n),
    .f3_read(conv4_U0_f3_read)
);

conv5 conv5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv5_U0_ap_start),
    .start_full_n(start_for_detection_head_U0_full_n),
    .ap_done(conv5_U0_ap_done),
    .ap_continue(conv5_U0_ap_continue),
    .ap_idle(conv5_U0_ap_idle),
    .ap_ready(conv5_U0_ap_ready),
    .start_out(conv5_U0_start_out),
    .start_write(conv5_U0_start_write),
    .out_r_din(conv5_U0_out_r_din),
    .out_r_full_n(f5_local_channel_full_n),
    .out_r_write(conv5_U0_out_r_write),
    .f4_dout(f4_local_channel_dout),
    .f4_empty_n(f4_local_channel_empty_n),
    .f4_read(conv5_U0_f4_read)
);

detection_head detection_head_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(detection_head_U0_ap_start),
    .ap_done(detection_head_U0_ap_done),
    .ap_continue(detection_head_U0_ap_continue),
    .ap_idle(detection_head_U0_ap_idle),
    .ap_ready(detection_head_U0_ap_ready),
    .out_r_address0(detection_head_U0_out_r_address0),
    .out_r_ce0(detection_head_U0_out_r_ce0),
    .out_r_we0(detection_head_U0_out_r_we0),
    .out_r_d0(detection_head_U0_out_r_d0),
    .f5_dout(f5_local_channel_dout),
    .f5_empty_n(f5_local_channel_empty_n),
    .f5_read(detection_head_U0_f5_read)
);

fifo_w32_d16_A f1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv1_U0_out_r_din),
    .if_full_n(f1_local_channel_full_n),
    .if_write(conv1_U0_out_r_write),
    .if_dout(f1_local_channel_dout),
    .if_empty_n(f1_local_channel_empty_n),
    .if_read(maxpool1_U0_f1_read)
);

fifo_w32_d16_A p1_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool1_U0_out_r_din),
    .if_full_n(p1_local_channel_full_n),
    .if_write(maxpool1_U0_out_r_write),
    .if_dout(p1_local_channel_dout),
    .if_empty_n(p1_local_channel_empty_n),
    .if_read(conv2_U0_p1_read)
);

fifo_w32_d16_A f2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv2_U0_out_r_din),
    .if_full_n(f2_local_channel_full_n),
    .if_write(conv2_U0_out_r_write),
    .if_dout(f2_local_channel_dout),
    .if_empty_n(f2_local_channel_empty_n),
    .if_read(maxpool2_U0_f2_read)
);

fifo_w32_d16_A p2_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2_U0_out_r_din),
    .if_full_n(p2_local_channel_full_n),
    .if_write(maxpool2_U0_out_r_write),
    .if_dout(p2_local_channel_dout),
    .if_empty_n(p2_local_channel_empty_n),
    .if_read(conv3_U0_p2_read)
);

fifo_w32_d16_A f3_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv3_U0_out_r_din),
    .if_full_n(f3_local_channel_full_n),
    .if_write(conv3_U0_out_r_write),
    .if_dout(f3_local_channel_dout),
    .if_empty_n(f3_local_channel_empty_n),
    .if_read(conv4_U0_f3_read)
);

fifo_w32_d16_A f4_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv4_U0_out_r_din),
    .if_full_n(f4_local_channel_full_n),
    .if_write(conv4_U0_out_r_write),
    .if_dout(f4_local_channel_dout),
    .if_empty_n(f4_local_channel_empty_n),
    .if_read(conv5_U0_f4_read)
);

fifo_w32_d16_A f5_local_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv5_U0_out_r_din),
    .if_full_n(f5_local_channel_full_n),
    .if_write(conv5_U0_out_r_write),
    .if_dout(f5_local_channel_dout),
    .if_empty_n(f5_local_channel_empty_n),
    .if_read(detection_head_U0_f5_read)
);

start_for_maxpoolg8j start_for_maxpoolg8j_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool1_U0_din),
    .if_full_n(start_for_maxpool1_U0_full_n),
    .if_write(conv1_U0_start_write),
    .if_dout(start_for_maxpool1_U0_dout),
    .if_empty_n(start_for_maxpool1_U0_empty_n),
    .if_read(maxpool1_U0_ap_ready)
);

start_for_conv2_U0 start_for_conv2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv2_U0_din),
    .if_full_n(start_for_conv2_U0_full_n),
    .if_write(maxpool1_U0_start_write),
    .if_dout(start_for_conv2_U0_dout),
    .if_empty_n(start_for_conv2_U0_empty_n),
    .if_read(conv2_U0_ap_ready)
);

start_for_maxpoolhbi start_for_maxpoolhbi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_maxpool2_U0_din),
    .if_full_n(start_for_maxpool2_U0_full_n),
    .if_write(conv2_U0_start_write),
    .if_dout(start_for_maxpool2_U0_dout),
    .if_empty_n(start_for_maxpool2_U0_empty_n),
    .if_read(maxpool2_U0_ap_ready)
);

start_for_conv3_U0 start_for_conv3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv3_U0_din),
    .if_full_n(start_for_conv3_U0_full_n),
    .if_write(maxpool2_U0_start_write),
    .if_dout(start_for_conv3_U0_dout),
    .if_empty_n(start_for_conv3_U0_empty_n),
    .if_read(conv3_U0_ap_ready)
);

start_for_conv4_U0 start_for_conv4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv4_U0_din),
    .if_full_n(start_for_conv4_U0_full_n),
    .if_write(conv3_U0_start_write),
    .if_dout(start_for_conv4_U0_dout),
    .if_empty_n(start_for_conv4_U0_empty_n),
    .if_read(conv4_U0_ap_ready)
);

start_for_conv5_U0 start_for_conv5_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv5_U0_din),
    .if_full_n(start_for_conv5_U0_full_n),
    .if_write(conv4_U0_start_write),
    .if_dout(start_for_conv5_U0_dout),
    .if_empty_n(start_for_conv5_U0_empty_n),
    .if_read(conv5_U0_ap_ready)
);

start_for_detectiibs start_for_detectiibs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_detection_head_U0_din),
    .if_full_n(start_for_detection_head_U0_full_n),
    .if_write(conv5_U0_start_write),
    .if_dout(start_for_detection_head_U0_dout),
    .if_empty_n(start_for_detection_head_U0_empty_n),
    .if_read(detection_head_U0_ap_ready)
);

assign ap_done = detection_head_U0_ap_done;

assign ap_idle = (maxpool2_U0_ap_idle & maxpool1_U0_ap_idle & detection_head_U0_ap_idle & conv5_U0_ap_idle & conv4_U0_ap_idle & conv3_U0_ap_idle & conv2_U0_ap_idle & conv1_U0_ap_idle);

assign ap_ready = conv1_U0_ap_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = detection_head_U0_ap_done;

assign ap_sync_ready = conv1_U0_ap_ready;

assign conv1_U0_ap_continue = 1'b1;

assign conv1_U0_ap_start = ap_start;

assign conv2_U0_ap_continue = 1'b1;

assign conv2_U0_ap_start = start_for_conv2_U0_empty_n;

assign conv3_U0_ap_continue = 1'b1;

assign conv3_U0_ap_start = start_for_conv3_U0_empty_n;

assign conv4_U0_ap_continue = 1'b1;

assign conv4_U0_ap_start = start_for_conv4_U0_empty_n;

assign conv5_U0_ap_continue = 1'b1;

assign conv5_U0_ap_start = start_for_conv5_U0_empty_n;

assign detection_head_U0_ap_continue = 1'b1;

assign detection_head_U0_ap_start = start_for_detection_head_U0_empty_n;

assign detection_head_U0_start_full_n = 1'b1;

assign detection_head_U0_start_write = 1'b0;

assign image_r_address0 = conv1_U0_in_r_address0;

assign image_r_address1 = 14'd0;

assign image_r_ce0 = conv1_U0_in_r_ce0;

assign image_r_ce1 = 1'b0;

assign image_r_d0 = 32'd0;

assign image_r_d1 = 32'd0;

assign image_r_we0 = 1'b0;

assign image_r_we1 = 1'b0;

assign maxpool1_U0_ap_continue = 1'b1;

assign maxpool1_U0_ap_start = start_for_maxpool1_U0_empty_n;

assign maxpool2_U0_ap_continue = 1'b1;

assign maxpool2_U0_ap_start = start_for_maxpool2_U0_empty_n;

assign output_r_address0 = detection_head_U0_out_r_address0;

assign output_r_address1 = 10'd0;

assign output_r_ce0 = detection_head_U0_out_r_ce0;

assign output_r_ce1 = 1'b0;

assign output_r_d0 = detection_head_U0_out_r_d0;

assign output_r_d1 = 32'd0;

assign output_r_we0 = detection_head_U0_out_r_we0;

assign output_r_we1 = 1'b0;

assign start_for_conv2_U0_din = 1'b1;

assign start_for_conv3_U0_din = 1'b1;

assign start_for_conv4_U0_din = 1'b1;

assign start_for_conv5_U0_din = 1'b1;

assign start_for_detection_head_U0_din = 1'b1;

assign start_for_maxpool1_U0_din = 1'b1;

assign start_for_maxpool2_U0_din = 1'b1;

endmodule //topp
