// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        f3_address0,
        f3_ce0,
        f3_q0
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;
output  [12:0] f3_address0;
output   f3_ce0;
input  [31:0] f3_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ce0;
reg out_r_we0;
reg f3_ce0;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] oc_3_fu_214_p2;
reg   [5:0] oc_3_reg_474;
wire    ap_CS_fsm_state2;
wire   [12:0] tmp_cast_fu_220_p1;
reg   [12:0] tmp_cast_reg_479;
wire   [0:0] exitcond5_fu_208_p2;
wire   [3:0] r_5_fu_230_p2;
reg   [3:0] r_5_reg_487;
wire    ap_CS_fsm_state3;
wire   [7:0] tmp_58_fu_260_p2;
reg   [7:0] tmp_58_reg_492;
wire   [0:0] exitcond4_fu_224_p2;
wire   [3:0] c_5_fu_272_p2;
reg   [3:0] c_5_reg_500;
wire    ap_CS_fsm_state4;
wire   [5:0] ic_3_fu_284_p2;
reg   [5:0] ic_3_reg_508;
wire    ap_CS_fsm_state5;
wire   [13:0] tmp_21_cast_fu_290_p1;
reg   [13:0] tmp_21_cast_reg_513;
wire   [0:0] exitcond2_fu_278_p2;
wire   [0:0] tmp_30_fu_202_p2;
reg   [0:0] tmp_30_reg_518;
wire   [12:0] tmp_60_fu_311_p2;
reg   [12:0] tmp_60_reg_523;
wire   [1:0] kr_2_fu_326_p2;
reg   [1:0] kr_2_reg_531;
wire    ap_CS_fsm_state6;
wire   [8:0] tmp_63_fu_362_p2;
reg   [8:0] tmp_63_reg_536;
wire   [0:0] exitcond1_fu_320_p2;
wire   [1:0] kc_2_fu_378_p2;
reg   [1:0] kc_2_reg_544;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond_fu_372_p2;
reg   [31:0] f3_load_reg_554;
wire    ap_CS_fsm_state8;
wire   [31:0] grp_fu_197_p2;
reg   [31:0] tmp_26_reg_559;
wire    ap_CS_fsm_state12;
wire   [31:0] grp_fu_192_p2;
wire    ap_CS_fsm_state17;
reg   [5:0] oc_reg_88;
reg   [3:0] r_reg_99;
wire   [0:0] exitcond3_fu_266_p2;
reg   [3:0] c_reg_111;
wire    ap_CS_fsm_state18;
reg   [31:0] sum5_reg_123;
reg   [5:0] ic_reg_135;
reg   [31:0] sum_1_reg_146;
reg   [1:0] kr_reg_158;
reg   [31:0] sum_2_reg_169;
reg   [1:0] kc_reg_181;
wire   [63:0] tmp_94_cast_fu_412_p1;
wire   [63:0] tmp_87_cast_fu_467_p1;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state9;
wire   [6:0] tmp_56_fu_236_p3;
wire   [4:0] tmp_57_fu_248_p3;
wire   [7:0] p_shl1_cast_fu_256_p1;
wire   [7:0] p_shl_cast_fu_244_p1;
wire   [7:0] tmp_20_cast_fu_294_p1;
wire   [7:0] tmp_59_fu_298_p2;
wire   [12:0] tmp_86_cast_fu_303_p3;
wire   [3:0] kr_cast2_fu_316_p1;
wire   [3:0] tmp_22_fu_332_p2;
wire   [7:0] tmp_61_fu_338_p3;
wire   [5:0] tmp_62_fu_350_p3;
wire   [8:0] p_shl2_cast_fu_346_p1;
wire   [8:0] p_shl3_cast_fu_358_p1;
wire   [3:0] kc_cast1_fu_368_p1;
wire   [3:0] tmp_24_fu_384_p2;
wire   [8:0] tmp_25_cast_fu_390_p1;
wire   [8:0] tmp_64_fu_394_p2;
wire   [13:0] tmp_93_cast_fu_399_p3;
wire   [13:0] tmp_65_fu_407_p2;
wire   [31:0] sum5_to_int_fu_417_p1;
wire   [7:0] tmp_s_fu_421_p4;
wire   [22:0] tmp_fu_431_p1;
wire   [0:0] notrhs_fu_441_p2;
wire   [0:0] notlhs_fu_435_p2;
wire   [0:0] tmp_29_fu_447_p2;
wire   [0:0] tmp_31_fu_453_p2;
reg   [17:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
end

topp_fadd_32ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fadd_32ns_32bkb_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_2_reg_169),
    .din1(tmp_26_reg_559),
    .ce(1'b1),
    .dout(grp_fu_192_p2)
);

topp_fmul_32ns_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
topp_fmul_32ns_32cud_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(f3_load_reg_554),
    .din1(32'd0),
    .ce(1'b1),
    .dout(grp_fu_197_p2)
);

topp_fcmp_32ns_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
topp_fcmp_32ns_32dEe_U27(
    .din0(sum5_reg_123),
    .din1(32'd0),
    .opcode(5'd4),
    .dout(tmp_30_fu_202_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_224_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        c_reg_111 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        c_reg_111 <= c_5_reg_500;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_266_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ic_reg_135 <= 6'd0;
    end else if (((exitcond1_fu_320_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ic_reg_135 <= ic_3_reg_508;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_320_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        kc_reg_181 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        kc_reg_181 <= kc_2_reg_544;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_372_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        kr_reg_158 <= kr_2_reg_531;
    end else if (((exitcond2_fu_278_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        kr_reg_158 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_224_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        oc_reg_88 <= oc_3_reg_474;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        oc_reg_88 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_266_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        r_reg_99 <= r_5_reg_487;
    end else if (((exitcond5_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        r_reg_99 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_266_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sum5_reg_123 <= 32'd0;
    end else if (((exitcond1_fu_320_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        sum5_reg_123 <= sum_1_reg_146;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_372_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        sum_1_reg_146 <= sum_2_reg_169;
    end else if (((exitcond2_fu_278_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        sum_1_reg_146 <= sum5_reg_123;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_320_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        sum_2_reg_169 <= sum_1_reg_146;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        sum_2_reg_169 <= grp_fu_192_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_5_reg_500 <= c_5_fu_272_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        f3_load_reg_554 <= f3_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ic_3_reg_508 <= ic_3_fu_284_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        kc_2_reg_544 <= kc_2_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kr_2_reg_531 <= kr_2_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        oc_3_reg_474 <= oc_3_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        r_5_reg_487 <= r_5_fu_230_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_278_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_21_cast_reg_513[5 : 0] <= tmp_21_cast_fu_290_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_26_reg_559 <= grp_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_278_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_30_reg_518 <= tmp_30_fu_202_p2;
        tmp_60_reg_523 <= tmp_60_fu_311_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_224_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_58_reg_492[7 : 1] <= tmp_58_fu_260_p2[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_320_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_63_reg_536[8 : 2] <= tmp_63_fu_362_p2[8 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5_fu_208_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_cast_reg_479[5 : 0] <= tmp_cast_fu_220_p1[5 : 0];
    end
end

always @ (*) begin
    if ((((exitcond5_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond5_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        f3_ce0 = 1'b1;
    end else begin
        f3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond5_fu_208_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond4_fu_224_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond3_fu_266_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond2_fu_278_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((exitcond1_fu_320_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((exitcond_fu_372_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign c_5_fu_272_p2 = (c_reg_111 + 4'd1);

assign exitcond1_fu_320_p2 = ((kr_reg_158 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond2_fu_278_p2 = ((ic_reg_135 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond3_fu_266_p2 = ((c_reg_111 == 4'd10) ? 1'b1 : 1'b0);

assign exitcond4_fu_224_p2 = ((r_reg_99 == 4'd10) ? 1'b1 : 1'b0);

assign exitcond5_fu_208_p2 = ((oc_reg_88 == 6'd32) ? 1'b1 : 1'b0);

assign exitcond_fu_372_p2 = ((kc_reg_181 == 2'd3) ? 1'b1 : 1'b0);

assign f3_address0 = tmp_94_cast_fu_412_p1;

assign ic_3_fu_284_p2 = (ic_reg_135 + 6'd1);

assign kc_2_fu_378_p2 = (kc_reg_181 + 2'd1);

assign kc_cast1_fu_368_p1 = kc_reg_181;

assign kr_2_fu_326_p2 = (kr_reg_158 + 2'd1);

assign kr_cast2_fu_316_p1 = kr_reg_158;

assign notlhs_fu_435_p2 = ((tmp_s_fu_421_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_441_p2 = ((tmp_fu_431_p1 == 23'd0) ? 1'b1 : 1'b0);

assign oc_3_fu_214_p2 = (oc_reg_88 + 6'd1);

assign out_r_address0 = tmp_87_cast_fu_467_p1;

assign out_r_d0 = ((tmp_31_fu_453_p2[0:0] === 1'b1) ? 32'd0 : sum5_reg_123);

assign p_shl1_cast_fu_256_p1 = tmp_57_fu_248_p3;

assign p_shl2_cast_fu_346_p1 = tmp_61_fu_338_p3;

assign p_shl3_cast_fu_358_p1 = tmp_62_fu_350_p3;

assign p_shl_cast_fu_244_p1 = tmp_56_fu_236_p3;

assign r_5_fu_230_p2 = (r_reg_99 + 4'd1);

assign sum5_to_int_fu_417_p1 = sum5_reg_123;

assign tmp_20_cast_fu_294_p1 = c_reg_111;

assign tmp_21_cast_fu_290_p1 = ic_reg_135;

assign tmp_22_fu_332_p2 = (kr_cast2_fu_316_p1 + r_reg_99);

assign tmp_24_fu_384_p2 = (c_reg_111 + kc_cast1_fu_368_p1);

assign tmp_25_cast_fu_390_p1 = tmp_24_fu_384_p2;

assign tmp_29_fu_447_p2 = (notrhs_fu_441_p2 | notlhs_fu_435_p2);

assign tmp_31_fu_453_p2 = (tmp_30_reg_518 & tmp_29_fu_447_p2);

assign tmp_56_fu_236_p3 = {{r_reg_99}, {3'd0}};

assign tmp_57_fu_248_p3 = {{r_reg_99}, {1'd0}};

assign tmp_58_fu_260_p2 = (p_shl1_cast_fu_256_p1 + p_shl_cast_fu_244_p1);

assign tmp_59_fu_298_p2 = (tmp_58_reg_492 + tmp_20_cast_fu_294_p1);

assign tmp_60_fu_311_p2 = (tmp_86_cast_fu_303_p3 + tmp_cast_reg_479);

assign tmp_61_fu_338_p3 = {{tmp_22_fu_332_p2}, {4'd0}};

assign tmp_62_fu_350_p3 = {{tmp_22_fu_332_p2}, {2'd0}};

assign tmp_63_fu_362_p2 = (p_shl2_cast_fu_346_p1 - p_shl3_cast_fu_358_p1);

assign tmp_64_fu_394_p2 = (tmp_25_cast_fu_390_p1 + tmp_63_reg_536);

assign tmp_65_fu_407_p2 = (tmp_21_cast_reg_513 + tmp_93_cast_fu_399_p3);

assign tmp_86_cast_fu_303_p3 = {{tmp_59_fu_298_p2}, {5'd0}};

assign tmp_87_cast_fu_467_p1 = tmp_60_reg_523;

assign tmp_93_cast_fu_399_p3 = {{tmp_64_fu_394_p2}, {5'd0}};

assign tmp_94_cast_fu_412_p1 = tmp_65_fu_407_p2;

assign tmp_cast_fu_220_p1 = oc_reg_88;

assign tmp_fu_431_p1 = sum5_to_int_fu_417_p1[22:0];

assign tmp_s_fu_421_p4 = {{sum5_to_int_fu_417_p1[30:23]}};

always @ (posedge ap_clk) begin
    tmp_cast_reg_479[12:6] <= 7'b0000000;
    tmp_58_reg_492[0] <= 1'b0;
    tmp_21_cast_reg_513[13:6] <= 8'b00000000;
    tmp_63_reg_536[1:0] <= 2'b00;
end

endmodule //conv4
