// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _maxpool2_HH_
#define _maxpool2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "topp_fcmp_32ns_32dEe.h"

namespace ap_rtl {

struct maxpool2 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<12> > out_r_address0;
    sc_out< sc_logic > out_r_ce0;
    sc_out< sc_logic > out_r_we0;
    sc_out< sc_lv<32> > out_r_d0;
    sc_out< sc_lv<14> > f2_address0;
    sc_out< sc_logic > f2_ce0;
    sc_in< sc_lv<32> > f2_q0;
    sc_signal< sc_lv<5> > ap_var_for_const0;


    // Module declarations
    maxpool2(sc_module_name name);
    SC_HAS_PROCESS(maxpool2);

    ~maxpool2();

    sc_trace_file* mVcdFile;

    topp_fcmp_32ns_32dEe<1,1,32,32,1>* topp_fcmp_32ns_32dEe_U17;
    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > ch_1_fu_189_p2;
    sc_signal< sc_lv<5> > ch_1_reg_528;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<15> > tmp_cast3_fu_195_p1;
    sc_signal< sc_lv<15> > tmp_cast3_reg_533;
    sc_signal< sc_lv<1> > exitcond4_fu_183_p2;
    sc_signal< sc_lv<13> > tmp_cast_fu_199_p1;
    sc_signal< sc_lv<13> > tmp_cast_reg_538;
    sc_signal< sc_lv<4> > r_1_fu_209_p2;
    sc_signal< sc_lv<4> > r_1_reg_546;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<5> > tmp_5_fu_215_p3;
    sc_signal< sc_lv<5> > tmp_5_reg_551;
    sc_signal< sc_lv<1> > exitcond3_fu_203_p2;
    sc_signal< sc_lv<10> > tmp_7_fu_231_p2;
    sc_signal< sc_lv<10> > tmp_7_reg_556;
    sc_signal< sc_lv<9> > tmp_1_fu_249_p2;
    sc_signal< sc_lv<9> > tmp_1_reg_561;
    sc_signal< sc_lv<4> > c_1_fu_261_p2;
    sc_signal< sc_lv<4> > c_1_reg_569;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<5> > tmp_9_fu_267_p3;
    sc_signal< sc_lv<5> > tmp_9_reg_574;
    sc_signal< sc_lv<1> > exitcond2_fu_255_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<2> > i_1_fu_335_p2;
    sc_signal< sc_lv<2> > i_1_reg_592;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<10> > tmp_22_fu_350_p2;
    sc_signal< sc_lv<10> > tmp_22_reg_597;
    sc_signal< sc_lv<1> > exitcond1_fu_329_p2;
    sc_signal< sc_lv<2> > j_1_fu_393_p2;
    sc_signal< sc_lv<2> > j_1_reg_605;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > exitcond_fu_387_p2;
    sc_signal< sc_lv<32> > v_reg_615;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > maxv_2_fu_518_p3;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<5> > ch_reg_98;
    sc_signal< sc_lv<4> > r_reg_110;
    sc_signal< sc_lv<4> > c_reg_121;
    sc_signal< sc_lv<32> > maxv1_reg_133;
    sc_signal< sc_lv<2> > i_reg_144;
    sc_signal< sc_lv<32> > maxv_1_reg_155;
    sc_signal< sc_lv<2> > j_reg_167;
    sc_signal< sc_lv<64> > tmp_19_fu_320_p1;
    sc_signal< sc_lv<64> > tmp_31_cast_fu_378_p1;
    sc_signal< sc_lv<64> > tmp_36_cast_fu_430_p1;
    sc_signal< sc_lv<5> > tmp_7_fu_231_p0;
    sc_signal< sc_lv<8> > tmp_s_fu_237_p3;
    sc_signal< sc_lv<9> > p_shl_cast_fu_245_p1;
    sc_signal< sc_lv<9> > tmp_6_cast_fu_227_p1;
    sc_signal< sc_lv<10> > tmp_cast_10_fu_275_p1;
    sc_signal< sc_lv<10> > tmp_3_fu_279_p2;
    sc_signal< sc_lv<1> > tmp_fu_284_p1;
    sc_signal< sc_lv<5> > tmp_6_fu_288_p3;
    sc_signal< sc_lv<9> > tmp_11_fu_302_p4;
    sc_signal< sc_lv<5> > tmp_8_fu_296_p2;
    sc_signal< sc_lv<14> > tmp_13_fu_312_p3;
    sc_signal< sc_lv<5> > i_cast2_fu_325_p1;
    sc_signal< sc_lv<5> > tmp_2_fu_341_p2;
    sc_signal< sc_lv<5> > tmp_22_fu_350_p0;
    sc_signal< sc_lv<9> > tmp_1_cast_fu_356_p1;
    sc_signal< sc_lv<9> > tmp_20_fu_360_p2;
    sc_signal< sc_lv<13> > tmp_30_cast_fu_365_p3;
    sc_signal< sc_lv<13> > tmp_21_fu_373_p2;
    sc_signal< sc_lv<5> > j_cast1_fu_383_p1;
    sc_signal< sc_lv<5> > tmp_4_fu_399_p2;
    sc_signal< sc_lv<10> > tmp_8_cast_fu_404_p1;
    sc_signal< sc_lv<10> > tmp_23_fu_408_p2;
    sc_signal< sc_lv<14> > tmp_24_fu_413_p3;
    sc_signal< sc_lv<15> > tmp_35_cast_fu_421_p1;
    sc_signal< sc_lv<15> > tmp_25_fu_425_p2;
    sc_signal< sc_lv<32> > v_to_int_fu_435_p1;
    sc_signal< sc_lv<32> > maxv_1_to_int_fu_452_p1;
    sc_signal< sc_lv<8> > tmp_10_fu_438_p4;
    sc_signal< sc_lv<23> > tmp_26_fu_448_p1;
    sc_signal< sc_lv<1> > notrhs_fu_476_p2;
    sc_signal< sc_lv<1> > notlhs_fu_470_p2;
    sc_signal< sc_lv<8> > tmp_12_fu_456_p4;
    sc_signal< sc_lv<23> > tmp_27_fu_466_p1;
    sc_signal< sc_lv<1> > notrhs7_fu_494_p2;
    sc_signal< sc_lv<1> > notlhs6_fu_488_p2;
    sc_signal< sc_lv<1> > tmp_14_fu_482_p2;
    sc_signal< sc_lv<1> > tmp_15_fu_500_p2;
    sc_signal< sc_lv<1> > tmp_16_fu_506_p2;
    sc_signal< sc_lv<1> > tmp_17_fu_178_p2;
    sc_signal< sc_lv<1> > tmp_18_fu_512_p2;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    sc_signal< sc_lv<10> > tmp_22_fu_350_p00;
    sc_signal< sc_lv<10> > tmp_7_fu_231_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_fsm_state1;
    static const sc_lv<9> ap_ST_fsm_state2;
    static const sc_lv<9> ap_ST_fsm_state3;
    static const sc_lv<9> ap_ST_fsm_state4;
    static const sc_lv<9> ap_ST_fsm_state5;
    static const sc_lv<9> ap_ST_fsm_state6;
    static const sc_lv<9> ap_ST_fsm_state7;
    static const sc_lv<9> ap_ST_fsm_state8;
    static const sc_lv<9> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<5> ap_const_lv5_10;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<4> ap_const_lv4_E;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<10> ap_const_lv10_1D;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_c_1_fu_261_p2();
    void thread_ch_1_fu_189_p2();
    void thread_exitcond1_fu_329_p2();
    void thread_exitcond2_fu_255_p2();
    void thread_exitcond3_fu_203_p2();
    void thread_exitcond4_fu_183_p2();
    void thread_exitcond_fu_387_p2();
    void thread_f2_address0();
    void thread_f2_ce0();
    void thread_i_1_fu_335_p2();
    void thread_i_cast2_fu_325_p1();
    void thread_j_1_fu_393_p2();
    void thread_j_cast1_fu_383_p1();
    void thread_maxv_1_to_int_fu_452_p1();
    void thread_maxv_2_fu_518_p3();
    void thread_notlhs6_fu_488_p2();
    void thread_notlhs_fu_470_p2();
    void thread_notrhs7_fu_494_p2();
    void thread_notrhs_fu_476_p2();
    void thread_out_r_address0();
    void thread_out_r_ce0();
    void thread_out_r_d0();
    void thread_out_r_we0();
    void thread_p_shl_cast_fu_245_p1();
    void thread_r_1_fu_209_p2();
    void thread_tmp_10_fu_438_p4();
    void thread_tmp_11_fu_302_p4();
    void thread_tmp_12_fu_456_p4();
    void thread_tmp_13_fu_312_p3();
    void thread_tmp_14_fu_482_p2();
    void thread_tmp_15_fu_500_p2();
    void thread_tmp_16_fu_506_p2();
    void thread_tmp_18_fu_512_p2();
    void thread_tmp_19_fu_320_p1();
    void thread_tmp_1_cast_fu_356_p1();
    void thread_tmp_1_fu_249_p2();
    void thread_tmp_20_fu_360_p2();
    void thread_tmp_21_fu_373_p2();
    void thread_tmp_22_fu_350_p0();
    void thread_tmp_22_fu_350_p00();
    void thread_tmp_22_fu_350_p2();
    void thread_tmp_23_fu_408_p2();
    void thread_tmp_24_fu_413_p3();
    void thread_tmp_25_fu_425_p2();
    void thread_tmp_26_fu_448_p1();
    void thread_tmp_27_fu_466_p1();
    void thread_tmp_2_fu_341_p2();
    void thread_tmp_30_cast_fu_365_p3();
    void thread_tmp_31_cast_fu_378_p1();
    void thread_tmp_35_cast_fu_421_p1();
    void thread_tmp_36_cast_fu_430_p1();
    void thread_tmp_3_fu_279_p2();
    void thread_tmp_4_fu_399_p2();
    void thread_tmp_5_fu_215_p3();
    void thread_tmp_6_cast_fu_227_p1();
    void thread_tmp_6_fu_288_p3();
    void thread_tmp_7_fu_231_p0();
    void thread_tmp_7_fu_231_p00();
    void thread_tmp_7_fu_231_p2();
    void thread_tmp_8_cast_fu_404_p1();
    void thread_tmp_8_fu_296_p2();
    void thread_tmp_9_fu_267_p3();
    void thread_tmp_cast3_fu_195_p1();
    void thread_tmp_cast_10_fu_275_p1();
    void thread_tmp_cast_fu_199_p1();
    void thread_tmp_fu_284_p1();
    void thread_tmp_s_fu_237_p3();
    void thread_v_to_int_fu_435_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
